### ISSUE TITLE
Support for TabBar in iOS10

### ISSUE THREAD

**Issue by simonpierreroy** [52inc/Pulley#100]
[Archive.zip](https://github.com/52inc/Pulley/files/1415989/Archive.zip)
There is a bug in iOS 10 with the PulleyViewController for the open position when the controller is embedded in a TabBar. See the videos. Also, the UI for the tableView in the DrawerContentViewController  is not updated correctly in iOS 10, see the blue view under the TabbBar in the videos.

Fix:

 func getBottomSafeArea() -> CGFloat {
         
         let safeAreaBottomInset: CGFloat
         
         if #available(iOS 11.0, *)
         {
             safeAreaBottomInset = self.view.safeAreaInsets.bottom
          }
          else
          {
           safeAreaBottomInset = self.bottomLayoutGuide.length
          }
          return safeAreaBottomInset
}

     override open func viewDidLayoutSubviews() {
         super.viewDidLayoutSubviews()
         if #available(iOS 11, *) {
            self.drawerScrollView.contentInsetAdjustmentBehavior = .always
         } else {
             self.automaticallyAdjustsScrollViewInsets = false
             self.drawerScrollView.contentInset = UIEdgeInsets(top: 0, left: 0, bottom:             self.bottomLayoutGuide.length, right: 0)
             self.drawerScrollView.scrollIndicatorInsets =  UIEdgeInsets(top: 0, left: 0, bottom: self.bottomLayoutGuide.length, right: 0) // (usefull if visible..)
         } 
}

**Comment by brendan09** [comment]
A UITTabbarController isn't an officially supported use-case for Pulley. I'm happy to accept fixes for it, however the 'official' use case for Pulley is as the rootViewController of a window. As a result, Pulley hasn't been optimized or tested for the scenario you're describing. I see you've made a PR, and I'm happy to consider merging it if it doesn't introduce issues with the standard use-case for Pulley.

**Comment by simonpierreroy** [comment]
Woow! Thank you, I hope everything works fine! If not, let me know, I could try to fix any issues.

**Comment by brendan09** [comment]
Everything tested well on iOS 10 + 11. It may interfere with some workarounds that people have been using in the past, so I've bumped Pulley a minor version so they won't get it automatically.

This was merged and will be in the next version of Pulley this afternoon. (2.1.0)

Thanks!

**Comment by simonpierreroy** [comment]
Thank you! :)
