### ISSUE TITLE
Use of undeclared type 'CGFloat'

### ISSUE THREAD

**Issue by ywkim** [52inc/Pulley#101]
I tried building a static library, but I'm getting lots of compiler errors from what look to be missing UIKit imports:

```
/ios/Pods/Pulley/PulleyLib/PulleyViewController+Nested.swift:11:67: error: use of undeclared type 'CGFloat'; did you mean to use 'CGFloat'?
    public func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
                                                                  ^~~~~~~
                                                                  CGFloat
```

**Comment by brendan09** [comment]
It compiles when using CocoaPods (or when adding the files manually to your project), using Xcode 9 and Swift 4.

These are the 2 officially supported ways of using Pulley. Make sure and check your Xcode setup / Xcode version to ensure you’re using the appropriate version of Pulley for your project.

If you’re using Xcode 9, and determine that adding a UIKit import to that file fixes your issue, you’re welcome to create a PR with the change.

**Comment by ywkim** [comment]
I use Xcode 9 and Swift 4, and I get errors when copying all .swift files to the project.

Adding a UIKit import to that file fixes the problem.
