### ISSUE TITLE
Swipe to close-position

### ISSUE THREAD

**Issue by domhof** [52inc/Pulley#105]
I would like to implement a way for the user to close the drawer by swiping it to the bottom. For this I listen to drawerPositionDidChange and if the right position is reached, then I programmatically set the drawer position to .close. This doesn't work however, since in .collapsed position the user cannot swipe the drawer further down.

Is it possible to allow scrolling to .close position?

**Comment by brendan09** [comment]
Although Pulley doesn't directly support it (for a few reasons), you can add support for this in your drawer content view controller.

Add a UISwipeGestureRecognizer to your drawer content view controller, and look for 'down' swipes in the area of the drawer that is showing (or that you want the gesture to be available in). When you detect a 'down' gesture, set the drawer position to closed.

Pulley won't provide a way for users to 'unhide' the drawer, so you'll need to incorporate that into your UI.

**Comment by awall1** [comment]
To future devs. My way around this was to set the collapsed height to 0.
My specific case called for two drawer positions: `.open` and `.closed`.
In order for this to work I still needed the .collapsed position as part of the `supportedDrawerPositions`
```swift
    func supportedDrawerPositions() -> [PulleyPosition] {
        return [.open, .collapsed, .closed]
    }

    func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
        return 0
    }
```
