### ISSUE TITLE
Adjust map center in pulley background 

### ISSUE THREAD

**Issue by pprevalon** [52inc/Pulley#106]
I have google maps in the background of the pulley. When I start to raise it lower the pulley I want to adjust the padding and center of the map. How can I complete that.

**Comment by brendan09** [comment]
I can't provide any Google Maps specific information, but for the Pulley part: You can implement the protocol `PulleyPrimaryContentControllerDelegate` on your primary content view controller and receive the current drawer height by implementing the protocol function `drawerChangedDistanceFromBottom(drawer:, distance:, bottomSafeArea:)` in your primary content view controller.

You can use the 'distance' value to make adjustments to your map.

**Comment by nchatharoo** [comment]
@pprevalon : I had the same problem, so I used this method : 
func drawerChangedDistanceFromBottom(drawer: PulleyViewController, distance: CGFloat) {
        if distance <= 268.0 {
            self.mapView.padding = UIEdgeInsets(top: 0, left: 0, bottom: distance, right: 0)
        }
}
