### ISSUE TITLE
Toolbar hidden by Primary Content View

### ISSUE THREAD

**Issue by apurvagoyal** [52inc/Pulley#107]
Hello,

I am using Pulley library in an iOS (phone only) app. I have my search controller as a title view of the navigation bar. I then added a UIToolbar under the navigation controller. Under toolbar I added my two container views to hold primary and drawer views. However my toolbar is always hidden and doesn't show at all.

I have enclosed the screenshot of how it looks like now and my original layout. please note that I don't see any toolbar below the search bar.

Thanks
AG

This is what I designed

![screen shot 2017-11-03 at 11 24 41 am](https://user-images.githubusercontent.com/552020/32381680-ae9bfb18-c089-11e7-83fb-1f60b30fb581.png)

This is what I see
![simulator screen shot - iphone 7 - 2017-11-03 at 10 55 41](https://user-images.githubusercontent.com/552020/32380093-9efacd28-c085-11e7-8fc5-c7aadf58b090.png)

**Comment by brendan09** [comment]
The Storyboard container view support for Pulley is a 'convenience' feature, and is not reflected of the subview structure or ordering of the subviews that Pulley manages.

You shouldn't add non-container views to the Pulley VC in the Storyboard, as the subview structure of Pulley is not meant to be manually altered. Pulley doesn't respect the ordering of subviews that it doesn't manage.

You should put any additional views into your primary content view controller.
