### ISSUE TITLE
- 'Pulley (~> 2.1)' required by 'Podfile'

### ISSUE THREAD

**Issue by Peter-GPower** [52inc/Pulley#108]
<img width="955" alt="2017-11-07 3 56 35" src="https://user-images.githubusercontent.com/22340787/32480899-5274d708-c3d4-11e7-88e8-7e7ea05d87d0.png">

Hi,

As you see above(attached image file), I'm facing the problem.
How can I handle this? :'(

**Comment by zackperdue** [comment]
run `pod update`

**Comment by Peter-GPower** [comment]
Thank you so much 👍
