### ISSUE TITLE
Passing nested PulleyViewController scroll events to topmost PulleyPassthroughScrollView

### ISSUE THREAD

**Issue by ethansinjin** [52inc/Pulley#109]
Hello!
I've been using nested `PulleyViewController`s in a project for a while now, and I've noticed a few rough edges with my original implementation that are probably going to be annoying to solve.

The Maps application nests the in-house equivalent of these controllers without showing any but the topmost card. This can be accomplished using this project by setting the `topInset` of the nested PulleyViewControllers to 0.0.

The Maps application has two main ways to interact with a pulley 'card': either tap the `X` button to close the card, or drag the card to scroll it. Both of these behaviors are matched in this project's sample app, but this behavior falls apart when using nested cards because the topmost `PulleyPassthroughScrollView` will always capture the scroll event. Thus, only the topmost visible (bottom-most in terms of view hierarchy) card will collapse by dragging, leaving the bottom card(s) in the same place.

The (IMO) ideal behavior of scrolling in a nested environment would be that the bottommost invisible card would collapse, which would match the behavior of the Maps application.

I've spent about an hour looking at how the PulleyPassthroughScroll view operates, and I can't think of a non-disruptive way to accomplish this behavior change; maybe I'm thinking of this the wrong way though. If anyone has any ideas, I can work on a PR this week.

// cc @brendan09

**Comment by brendan09** [comment]
Pulley isn't meant to be nested. To accomplish what it sounds like you're trying to do, take a look at the comment I left here: https://github.com/52inc/Pulley/issues/89

**Comment by ethansinjin** [comment]
Hey Brendan,

I’ll take a look, thanks.
By the way, I recently worked on https://github.com/52inc/Pulley/pull/61, which does allow PulleyViewControllers to be nested!

**Comment by brendan09** [comment]
It does allow it, but it's not an 'officially' supported use case. I'm happy to merge fixes for it, but it's not something that support will be guaranteed for in the future.

**Comment by ethansinjin** [comment]
The solution you linked works for me and prevents the view hierarchy from ballooning quickly. Thanks! 🙇 

I still think there are situations where nesting PulleyViewControllers can be useful, but I agree that is unwieldy and bug-prone. I may try to fix a few pain points for this use case in the future.
