### ISSUE TITLE
Can't access container.drawerContentViewController

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#11]
Hi the content and primary drawers are set to internal so we can't access it from outside of your project. Can you make these public or at least provide some getters ?

Is there another way to get reference to the primary from content or to the content from the primary ?

this is what i tried so far : 

<img width="926" alt="screen shot 2016-09-23 at 00 48 10" src="https://cloud.githubusercontent.com/assets/5930273/18768782/e755e43e-8127-11e6-9662-c11158fb33f8.png">

**Comment by brendan09** [comment]
I'll push an update to that later tonight. Sorry about that!

**Comment by brendan09** [comment]
Ok, it's over in the https://github.com/52inc/Pulley/tree/feature/supported-drawer-stops branch.

I'll merge that to master and put out a CocoaPods release once I've had time to confirm everything is stable.
