### ISSUE TITLE
Weird stuff happens in landscape on iPhone X

### ISSUE THREAD

**Issue by iKenndac** [52inc/Pulley#110]
Sorry for the terrible title. But, it's true! 

I'm using Pulley 2.1.0 in the `partiallyRevealed` state. In portrait, everything looks dandy:

![img_1781](https://user-images.githubusercontent.com/514900/32575634-da4245b6-c4d4-11e7-892e-e4e9c55ab162.PNG)

However, in landscape…

![img_1782](https://user-images.githubusercontent.com/514900/32575696-fd7f1ca2-c4d4-11e7-98bd-d2d84ce4b0d0.PNG)

Yikes! If you later adjust the height of the drawer, you do get your view controller back again, as seen in this little video (the drawer gets a couple of points higher during the navigation controller transition). 

![pulley](https://user-images.githubusercontent.com/514900/32575989-ddffe270-c4d5-11e7-8803-3eb980aa61cc.gif)

If you look really carefully in a screen recording, it looks like there's a background view that's fading away the background when it shouldn't.

![pulley2](https://user-images.githubusercontent.com/514900/32576054-15ec3a4e-c4d6-11e7-9a5c-2ff53cb21353.png)

**Comment by brendan09** [comment]
Merged! Thanks
