### ISSUE TITLE
Is there a way to get drawer position notices (like a willChangePosition) during dragging

### ISSUE THREAD

**Issue by akac** [52inc/Pulley#114]
There are some UI changes I'd like to animate during the dragging of the drawer.

**Comment by brendan09** [comment]
The delegate for Pulley provides callbacks for the drawer movement. Take a look at the example project to see how it’s used, and how some UI elements follow the movement of the drawer.

Let me know if you have any questions!

**Comment by akac** [comment]
Right - I'm using those delegates - but they only seem to get called when you let go of the drag. I'm not seeing those delegate calls *during* the drag.

**Comment by brendan09** [comment]
The method ‘drawerChangedDistanceFromBottom’ is called during scroll / drag, And is used by the sample project to allow UI to follow along with the drawer.

**Comment by akac** [comment]
OK I’ll look at that. I am not sure how I missed that one.
