### ISSUE TITLE
non-open delegate methods 

### ISSUE THREAD

**Issue by Patrick-Remy** [52inc/Pulley#115]
I can't override drawerPositionDidChange(drawer:bottomSafeArea:) in my PulleyViewController subclass. I am getting the error message `Overriding non-open instance method outside of its defining module`.

**Comment by brendan09** [comment]
PulleyViewController is not meant to be subclassed. In addition, the delegate implementations in PulleyViewController are written as extensions (and should not be overridden as a result). The delegate implementation on PulleyVC itself serves an important purpose with regards to nesting PulleyVC.

**Comment by adolfo** [comment]
@brendan09  Why this restriction that a `PulleyViewController` subclass cannot also be the 
`PulleyDelegate`? It's not marked `final`. We're currently migrating to Swift 4 and running into this same issue.

**Comment by brendan09** [comment]
Although I don’t officially support subclassing Pulley, complaints were made that people “wanted to do it anyway”. As a result, it isn’t marked final.

But, it isn’t an officially supported use case.

PulleyViewController implements portions of PulleyDelegate to support nested drawers.

I don’t necessarily mind a rework to make them not in an extension and overridable, but preserving subclasses isn’t a big priority for me. Lots of things change internally between some major releases, and I don’t want people relying or overriding behavior that may change.

**Comment by brendan09** [comment]
Just dropping a quick note before I close this issue:

Version 2.2.0 is now up on CocoaPods, if you'd like to use it, and includes open delegate methods. You may need to 'pod repo update' before running 'pod update Pulley' in order to get it.
