### ISSUE TITLE
Could not load Pullup into Swift code

### ISSUE THREAD

**Issue by 1trycode** [52inc/Pulley#116]
Iam able to get PulleyViewControl, and set primary & drawer viewcontroll. But how can I assign my primary ViewControll to pullup? I am trying to use pulley to display Image, and image description as drawer. Is there any sample?

**Comment by brendan09** [comment]
There is a sample project in the GitHub repo. Let me know if you have any questions on it.

**Comment by 1trycode** [comment]
sample is using bridge file, my code failed using "import ISHPullUp" saying "no such module"

**Comment by brendan09** [comment]
ISHPullUp Is not from this repository / project, and is not used by the sample project. I think you’re on the wrong repository.

**Comment by 1trycode** [comment]
You are right, I added Pulley, but looking at wrong sample code. Thanks.

**Comment by 1trycode** [comment]
OK, after getting the sample code, 
getting runtime error for headerSectionHeightConstraint
@ headerSectionHeightConstraint.constant = 68.0 + drawerBottomSafeArea
Where is the UI element for headerSectionHeightConstraint?

**Comment by brendan09** [comment]
You've deleted the constraint from Interface Builder that the sample project was using. You can delete that variable out of the code (instance variable and it's usages) and start replacing it with your own logic.

**Comment by 1trycode** [comment]
got it. thank you, but i applied to subview, worked fine
