### ISSUE TITLE
setting to change drawer Alqua value

### ISSUE THREAD

**Issue by 1trycode** [52inc/Pulley#117]
Is it possible to get transparent(alpha) drawer view controller? I have to display drawer text, with primary image display in background

**Comment by brendan09** [comment]
If you would like to remove the 'blur' view that's behind it by default you can do so by setting `drawerBackgroundVisualEffectView` to nil on the PulleyViewController.

This will leave your drawerContentVC entirely responsible for rendering the background. To remove the shadow behind the drawer, set the shadowOpacity property to 0.0 on PulleyViewController.

For most use cases, I recommend leaving the blur and shadow in place. Only using alpha generally doesn't look good on iOS.

**Comment by 1trycode** [comment]
ok. Worked changing drawerBackgroundVisualEffectView
what is the delegate i can use to update drawer content while change event on Primary?

**Comment by brendan09** [comment]
There’s not a delegate to do that, but you can set the drawer content view controller at any time.

**Comment by 1trycode** [comment]
can i set drawer content view controller from primary viewcontroller code?

**Comment by brendan09** [comment]
Yes

**Comment by brendan09** [comment]
It'll be something like this:

     (self.parent as? PulleyViewController)?.setDrawerContentViewController(controller: myNewDrawerViewController, animated: true, completion: nil)

Place this in your primary VC when you want to change it. `myNewDrawerViewController` is your new drawer VC.

**Comment by 1trycode** [comment]
got it, I am able to set the value from primary using
  if let pulley = self.parent?.parent as? PulleyViewController
and 
pulley.drawerContentViewController as? MyDrawerViewController 

Thanks
