### ISSUE TITLE
Multiple Drawer Views

### ISSUE THREAD

**Issue by simonnarai** [52inc/Pulley#118]
I am wondering if it is currently possible, or if you are planning to add support for, multiple drawer views in Pulley? The native maps app can have multiple cards / drawers overlaid on top of one another, eg when getting directions or tapping the info button, and this implementation would be very helpful for my use case.

**Comment by brendan09** [comment]
You can currently do something similar to that with Pulley. Take a look at the discussion here for an approach, and some follow-up with some tweaks by people who had success with it: https://github.com/52inc/Pulley/issues/89

Let me know if you have any questions.

**Comment by simonnarai** [comment]
Brilliant, I'll take a look and try that out, thank you!

**Comment by simonnarai** [comment]
That works very well, thanks again for your help!
