### ISSUE TITLE
TESTERS NEEDED: iPad support is available by pointing to 'master', please leave feedback on it here.

### ISSUE THREAD

**Issue by brendan09** [52inc/Pulley#119]

**Comment by genaks** [comment]
![simulator screen shot - ipad pro 9 7-inch - 2017-11-16 at 10 54 32](https://user-images.githubusercontent.com/8189786/32875196-8f2581c2-cabc-11e7-9cbd-7facc8a6c211.png)
This is how it looks on an iPad. Is that how it is supposed to be?

**Comment by brendan09** [comment]
Yes, that's what the sample project is supposed to look like. Checkout Apple's Maps app for a comparison to the Maps app on iPad, which is what this is trying to get closed to.

Please keep in mind that Pulley only attempts to emulate the drawer functionality itself, not the content or app itself.

**Comment by genaks** [comment]
Can I have it behave in a similar manner as on an iPhone in any way?

**Comment by brendan09** [comment]
Yes, you can set the property for displayMode to bottomDrawer and it will always be a bottom drawer.

However, the version on master is currently being tested. I don't recommend using it in an app. Instead, you should install the version on CocoaPods. It's more tested / stable and doesn't include support for the 'iPad' mode at all.

**Comment by genaks** [comment]
I don't plan on using it yet. I can test it as I go and then if everything seems ok, I may use it in my app. Still trying out other options as well of course. This came the closest to fulfilling my requirements :)

**Comment by brendan09** [comment]
Let me know if you have any questions / issues setting it up! Happy to help answer what I can.

**Comment by genaks** [comment]
Trying to set the displayMode to bottomDrawer in the viewDidAppear of the PrimaryContentViewController but it doesn't seem to be doing anything.

**Comment by brendan09** [comment]
Since we’re still testing and working out issues on this new version that you got from master (it’s not ‘released’ yet), try using the latest release from here: https://github.com/52inc/Pulley/releases

You won’t have to set the displayMode, as that version only does the bottom drawer.

**Comment by genaks** [comment]
Awesome. Thanks!

**Comment by genaks** [comment]
Have you thought about setting up a donation link and have it mentioned in the Readme? It might help you know :)

**Comment by brendan09** [comment]
Haha, no I enjoy doing it just for fun and hopefully people get some use out of it. Donations add too much pressure to make it perfect. :)

**Comment by genaks** [comment]
Well said my friend :)

**Comment by genaks** [comment]
Hey, it does not support orientation switching yet?

**Comment by genaks** [comment]
Don't mind the notification asking about the orientation thing. The simulator has been acting on me lately.

**Comment by brendan09** [comment]
It does, the sample app just doesn’t have it enabled. You can checkmark the other orientations in the target settings. iPhone X may have some landscape issues (portrait works fine) in the current “release” version, which will be accounted for in the next update.

**Comment by genaks** [comment]
Yes I figured. It's just that the whole app was taking time to adjust to the orientation. It may have been because of the slow speed of my simulators.

**Comment by brendan09** [comment]
Just dropping a quick note before I close this issue:

Version 2.2.0 is now up on CocoaPods, if you'd like to use it, and includes iPad support. You may need to 'pod repo update' before running 'pod update Pulley' in order to get it.
