### ISSUE TITLE
Make height adjustments when loading contentDrawer

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#12]
Hi, 

I have two drawer that have different collapsed size and I have no way to move the button in my primaryDrawer when the other one is loaded. It works asap I move the drawer but It is not considered as moved when its resized. I don't know if i'm clear enough.

In images : 
The first one is the starting state spacing : 
<img width="306" alt="screen shot 2016-09-23 at 20 15 16" src="https://cloud.githubusercontent.com/assets/5930273/18796649/8146daec-81ca-11e6-803a-c381ca31814c.png">

The second one is when I load a bigger collapsed size drawer : 
<img width="310" alt="screen shot 2016-09-23 at 20 15 23" src="https://cloud.githubusercontent.com/assets/5930273/18796655/8616cfaa-81ca-11e6-989b-eb67e448f016.png">

If I move the drawer my buttons move with the drawerChangedDistanceFromBottom but then if I load again the first one : 
<img width="309" alt="screen shot 2016-09-23 at 20 15 30" src="https://cloud.githubusercontent.com/assets/5930273/18796658/89944ce8-81ca-11e6-8079-c01874943304.png">

I think one solution would be that drawerChangedDistanceFromBottom(_:distance:) in the primaryDelegate should be called when the pulleyController is changing his content drawer. Or add methods to the delegate to respond to the contentDrawer collapsed size changes.

**Comment by Alex293** [comment]
As I know which controller I'm loading I can also use drawerChangedDistanceFromBottom(_:distance:) so I have a fix but it's kinda not the good way to go. It not automatic and if you just mix some height it fail.

**Comment by brendan09** [comment]
I just pushed a commit that _might_ fix it. If it doesn't, can you upload a mini sample project showing the error? That way I can ensure it's fixed.

Thanks!

**Comment by Alex293** [comment]
Sry was really busy this week couldn't try but I'll will give an update this weekend. Tho I think it's ok now

**Comment by brendan09** [comment]
This stuff has been merged to master (with some bug fixes) and is up on cocoapods. I'd recommend trying that one.

**Comment by Alex293** [comment]
Perfect closing the issue
