### ISSUE TITLE
How to receive delegate calls when drawer VC is embedded in a nav controller?

### ISSUE THREAD

**Issue by bmt22033** [52inc/Pulley#121]
Hi.  I'm trying to use Pulley with a drawer VC which is embedded in a navigation controller (solely for the purpose of having a navigation bar on the drawer VC).  Inside the drawer VC, I have a UISearchController (declared in code) and I'm assigning the UISearchController's search bar to the drawer VC's navigation bar like this:

`navigationItem.searchController = searchController`

This was working well enough but I wanted to change the height of the drawer when its collapsed so I made my drawer VC conform to PulleyDrawerViewControllerDelegate.  However, it didn't seem to be receiving any of the calls (collapsedDrawerHeight(), supportedDrawerPositions(), etc).  I eventually concluded that this is because the navigation controller is now the destination for the embed segue from the drawer container view (instead of the drawer view controller which was the case previously before I embedded it into a nav controller).

Is there any way to tell Pulley that my drawer view controller should get the delegate calls even though it's not a direct child of my Pulley VC anymore?

**Comment by brendan09** [comment]
You’ll need to implement the drawer delegate in a subclass of UINavigationController. If you need to pass it on to your view controller, you can do so by having your custom navigation controller forward the events on to the visible view controller of the navigation controller.

**Comment by brendan09** [comment]
On mobile, so I apologize that this doesn’t use correct names for things, which will keep it from compiling:

Inside one of the delegate methods in the navigation controller, you can do this to forward it on (if the visible view controller implements the drawer protocol):

if let visibleDrawer = self.visibleViewController as? PulleyViewControllerDrawerDelegate {

visibleDrawer.theDelegateMethod()
}

**Comment by bmt22033** [comment]
Ok, I think I understand that.  Thanks very much for the quick response!!
