### ISSUE TITLE
drawerContentViewController becomes unresponsive to touch on Plus-sized devices

### ISSUE THREAD

**Issue by worthbak** [52inc/Pulley#122]
First of all, thanks for providing and maintaining this library! It's both well thought-out and well implemented. Cheers! 

Unfortunately, we've run into one significant issue in our particular use-case. For context, we're setting a fairly standard UIViewController as the `drawerContentViewController`. This view controller has two main subviews: a horizontally scrolling collection view at the bottom of the view, and a vertically scrolling table view at the top (taking up most of the space in the view). 

As the user interacts with the app, we add cells to that vertically-scrolling table view, and calculate the total height of the table view based on the cells it contains. We then add that height to the height of the collection view (plus some margin) and manually set the `topInset` property on the `drawerContentViewController` using this derived height value. The effect is such that, as cells are added to the table view, the `drawerContentViewController` grows until it reaches the top of the screen, at which point the drawer stops moving and the table view begins scrolling its content off screen. I've included a dirty wireframe below to give you a visual idea as to what's happening: 

<img width="790" alt="screenshot 2017-11-21 08 50 18" src="https://user-images.githubusercontent.com/10028428/33082064-17a4203c-ce99-11e7-9822-d08bbb12097c.png">

On iPhone 8-sized devices, this system works quite well. However, on Plus-sized devices, updating the `topInset` value and then closing and re-opening the drawer (programmatically, in our case, by calling  `.setDrawerPosition(position: )`) causes all content inside the drawer to become unresponsive to touch (buttons, for example, don't fire a `touchUpInside` event, but rather a `touchCancelled` event in this state). The only successful touch event we receive is UITableView's `didSelectRowAt indexPath`. Other than that, all touches seem to be forward to the `PulleyPassthroughScrollView`, as scrolling the drawer down to `.collapsed` works just fine. 

Our direct management of the height of the view controller's content (via the `topInset` manipulation) is slightly different than your example project, but conceptually we don't see a reason that it shouldn't work in Pulley's system. That said, if you have hints or insight as to how our setup might conflict with Pulley's inner scroll view logic, it'd be greatly appreciated!

**Comment by brendan09** [comment]
Sure, happy to help see if we can figure out what’s wrong.

A few questions:

1. Are you using the version on CocoaPods, or a download from the master branch? (CocoaPods is recommended for stable use while we finish up iPad support on master)

2. Once it’s in this “broken” state, does manually dragging the drawer (just enough that it moves, and the system corrects it back to the topInset) fix the issue?

**Comment by worthbak** [comment]
Thanks for the quick response! 

We're using the CocoaPods version (`2.1.0`). And, once it's "broken", no, manually adjusting the drawer has no effect.

**Comment by worthbak** [comment]
@brendan09 we made one interesting discovery - when we calculate the total height of our view controller in order to derive a new `topInset` value, if we subtract 20pts from that value, the unresponsiveness issue goes away. However, our table view's height is then 20pts too small, and some of our content is clipped. It seems that we're mishandling the 20pt margin Pulley adds to the bottom of its `drawerContentViewController`?

**Comment by worthbak** [comment]
After debugging the issue for a while, we found that Pulley wasn't a good fit for this particular use-case in our app (we're still using elsewhere in the app, though, in spots where we can use it in a more standard configuration) - we wrote our own solution that is more tailored to our use. I'll close this issue - thanks for your help @brendan09 !
