### ISSUE TITLE
Drawer padding

### ISSUE THREAD

**Issue by skander300** [52inc/Pulley#127]
How could i add padding (from left and right) to drawer view controller ?

**Comment by brendan09** [comment]
Are you wanting to pad content _inside_ the drawer view controller, or padding between the drawer itself and the edge of the screen?

**Comment by skander300** [comment]
i want padding between itself and the edge of the screen.

**Comment by brendan09** [comment]
Pulley doesn't have a way to inset the drawer itself from the left and right, however you can accomplish this by adding PulleyViewController as a child view controller of an another View Controller, and adding PulleyViewController's view as a subview to the new parent view controller. You can then inset PulleyViewController's view as needed.
