### ISSUE TITLE
Last version is not downloaded

### ISSUE THREAD

**Issue by pablomarcos** [52inc/Pulley#128]
Hi everyone,
I can not get the last version of the pod (2.2) in my project.
Overtime I run pod install I get the version 2.1.0

This is the content of my Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'SmartComponents' do
    #of course, Pulley is not my only pod in my Podfile
    pod 'Pulley'
end
```

I have tried with everything:
pod install
pod update 
pod repo update
cleaning the cache of the pod repo...
....

Any clue?

I have tried also with:
pod 'Pulley' , '2.2' but does not work. Cocoapods give me an error:
None of your spec sources contain a spec satisfying the dependency: `Pulley (= 2.2)`.

Thanks

**Comment by brendan09** [comment]
There isn't a version 2.2 on CocoaPods, as it's still in development. The latest 'released' version is on CocoaPods and is version 2.1.0.

If you'd like to use the beta / dev version on master (2.2) you can manually point to master in your Podfile like this:

`pod 'Pulley', :git => 'https://github.com/52inc/Pulley.git', :branch => 'master'`

**Comment by pablomarcos** [comment]
Thanks very much brendan.
