### ISSUE TITLE
Drawer Position Delegate Callback Timing

### ISSUE THREAD

**Issue by CareerFairPlus** [52inc/Pulley#129]
Is there a reason why the `drawerPositionDidChange` delegate method is called in the animation block rather than in the completion block when animating between drawer changes?  

I was attempting to implement a use case where the drawer would animate closed, update its content off screen, and then animate open again.  Because the `drawerPositionDidChange` method is called before the drawer position animation has actually completed I ended up just adding an artificial delay to wait to update the drawer content.

Is there a better way to achieve what I want to do?

Thanks, and thanks for a great library!

**Comment by brendan09** [comment]
It's called inside the animation block in case someone wants to animate changes alongside the drawer animating to a new position.

Assuming you're calling 'setDrawer' to change the drawer position, there's an optional completion block you can pass it, and that'll be invoked in the completion block.

`func setDrawerPosition(position: PulleyPosition, animated: Bool, completion: PulleyAnimationCompletionBlock? = nil)`

**Comment by CareerFairPlus** [comment]
Ahh, ok.  I missed the version of setDrawer with the completion block.  I think what confused me is the wording, since callbacks with `did` are usually called after the event is completed.  Do you think there would be any benefit in changing the delegate callback to `drawerPositionWillChange`, just to clarify things?

**Comment by brendan09** [comment]
I do think it would be clearer, however it would also break everyone’s existing implementations. At this point I’ll probably leave it as-is for backwards compatibility.

**Comment by CareerFairPlus** [comment]
Thanks for the quick responses!
