### ISSUE TITLE
Support for navigationController

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#13]
Hi, 

As you recommended to not inherit from pulleyViewController directly how should we react for navigation controller bar button items ?

I'm gonna start by using buttons but I think its something useful

**Comment by brendan09** [comment]
You shouldn't put the pulley drawer inside a navigation controller. It was intended to be a parent VC only, like Apple's Maps app.

If you need to put it in a navigation controller (really not recommended from a UI / UX perspective) then you can just directly assign bar button items to the pulley drawer controller's navigationItem property.

**Comment by brendan09** [comment]
Also: You're welcome to try subclassing it, but it's not a scenario in going to provide explicit support for.

**Comment by Alex293** [comment]
You were right anyway one the UI/UX points, just wanted to use a transparent bar to keep only the bar buttons so if I open a new vc I have the back button for free.

**Comment by brendan09** [comment]
I would try subclassing it, or just assign bar buttons to the navigationItem of the existing one.

**Comment by Alex293** [comment]
OK thank you for your advices ! Closing this
