### ISSUE TITLE
gestures in partially revealed view 

### ISSUE THREAD

**Issue by skander300** [52inc/Pulley#130]
Is there a way to remove drag down gesture from partially revealed gesture in case i have inside it a view that demands some gesture recognition (for example : a table view, scroll view, signature view ...)
The problem is that i can't move a scroll or draw something inside a partially revealed view.
Any help ?

**Comment by brendan09** [comment]
If you have something scrollable inside of the drawer, it will remain scrollable regardless of the drawer position.

However: If you started with the sample project, or used code snippets from it, the drawer view controller disables it’s scrollview in all positions but “open” by setting isScrollEnabled. If you copied code from the sample project, you’ll need to find that line and remove it so your table view is scrollable in drawer positions other than “open”.

**Comment by brendan09** [comment]
You can also adjust canDelayContentTouches and canCancelContentTouches on Pulley. This may help you achieve what you’re looking for.
