### ISSUE TITLE
Bottom Up sheet support as in Maps

### ISSUE THREAD

**Issue by appsird** [52inc/Pulley#132]
Hi,

Thank you so much for this effort, this is very well done.

The bottom up sheet for search with table works well. when tapping the info button within Apple Maps, a sheet animates up from the bottom which keeps the map visible. in the sheet there is a segmented control to allow selecting a different map type. If one selects Satellite, the image changes below.

Though, inside Pulley, the info button segue's to a new view, and when exiting the view via "Go Back" button, the image is reloaded (i.e., viewDidLoad is called).

Would appreciate tips on an easy means to allow the bottom up sheet approach which does not remove the map, and require redraw.

**Comment by brendan09** [comment]
The buttons on the map in Pulley are just there to demo other features / ways you can interact with Pulley, not necessarily to imitate Maps.

I’m order to accomplish what you’re looking for, you can make a new view controller and present it modally “over full screen”. Make the background of that view controller the black with alpha color to dim everything, and then make a view with rounded corners to put your content in. You can make a button segue to presenting that view controller.

**Comment by appsird** [comment]
One other tip,

Note by moving the info/plus buttons down a bit, you can enable the Compass in default position in the upper right as per pic below - and place the scale in upper left.  I've been unsuccessful in attempting to place the compass as in Apple Maps (below the button pair), though this suffices. 

![img_0167](https://user-images.githubusercontent.com/8471833/33560027-7652e116-d8c3-11e7-8e4e-ee88e6cca547.PNG)

**Comment by brendan09** [comment]
The sample application’s UI isn’t really a concern for me. It’s meant to demo Pulley features, not necessarily to provide a fully functioning app to build on.

You can move the compass down by adjusting the topLayoutGuide for the view controller.

**Comment by appsird** [comment]
I coded 'over full screen' view controller approach you recommended, using segue/unwind segue. Thanks.

Regarding compass placement, it appears in Xcode 9 topLayouGuide is deprecated - and now there is the concept of the sage area:

https://developer.apple.com/documentation/uikit/uiview/2891102-safearealayoutguide

would appreciate a code snippet which demonstrates how to place the compass with this approach if possible. thanks again.

**Comment by brendan09** [comment]
topLayoutGuide is deprecated if you’re targeting iOS 11+ as your base OS. If you’re wanting to support any older version of iOS, you’ll need to continue using topLayoutGuide until your base OS is 11.

Although I haven’t tried it for the compass, you should be able to set a safe area the map compas will respect by setting the “additional safe area insets” property on your view controller.

**Comment by appsird** [comment]
Brendan,

Spent the last two days attempting to move the compass, with limited
success. Also, once moved, having proper placement on rotation seems a
separate issue to tackle.

Would appreciate if you might consider this enhancement at one point.
Xcode Version 9.2 (9C40b), Swift 4, iOS 11.2
I am only concerned with iOS 11, as there is already a 60% adoption rate on
devices.

Brian

**Comment by brendan09** [comment]
The sample project isn't an area that I consider to be under active development, as it's only meant to demo Pulley features (not provide a starting app infrastructure).

Unfortunately, I do have to support iOS 9+ for all of the other users.

This problem can / should be handled entirely within your app infrastructure, and isn't an issue with a component of Pulley itself. As a result, I'm going to close this issue as "won't fix", as it's external to Pulley.
