### ISSUE TITLE
Hide and show Drawer controller

### ISSUE THREAD

**Issue by alexsteinerde** [52inc/Pulley#133]
I have a quick question.

How can I dismiss the drawer at the bottom on initialisation and show again when an event happens?

**Comment by brendan09** [comment]
As long as it's listed as a supported drawer position in your delegate, you can set the drawer position to 'closed' in viewWillAppear.

You can then change the drawer position any time after that to a different supported state.

**Comment by alexsteinerde** [comment]
Thanks,
I have tried it in viewDidLoad but in viewWillAppear it works.

**Comment by brendan09** [comment]
For the future / anyone who stumbles upon this:

It doesn't work in viewDidLoad because _your_ view controller is loaded before Pulley is loaded, and isn't yet a 'child' of Pulley. As a result, configuration changes made in viewDidLoad won't take affect.
