### ISSUE TITLE
Adjust Physics of Drawer

### ISSUE THREAD

**Issue by mattbarker016** [52inc/Pulley#134]
Hey guys, really awesome work with Pulley! You saved me a lot of time and effort. This framework is incredibly customizable and powerful, but there's a few other tweaks I feel it could use that would go a long way.

The drawer is just a tad too heavy to move; I'd love to be able to **adjust the sensitivity** based on the number of points the drawer is moved. [DrawerKit](https://github.com/Babylonpartners/DrawerKit) has a great setting around this with values called `lowerMarkGap` and `upperMarkGap`. This creates a "band" above and below the current position, and when crossed, the drawer changes. Even just a basic enum to adjust sensitivity (e.g. `.heavy`, `.light`) would be appreciated!

The other small change would be **adjusting the speed** of using `setDrawerPosition`. I use a tap gesture to trigger drawer position changes, and would appreciate some control in using this function.

I may dig into the framework and make a fork for the project with values that work a better, but abstracting these options would go a long way into making this even more powerful! Thanks again.

**Comment by brendan09** [comment]
> The drawer is just a tad too heavy to move; I'd love to be able to adjust the sensitivity based on the number of points the drawer is moved.

Thanks for the complements! I'm not sure I understand what you're looking for, with regards to sensitivity. If it's concerning the difficulty to 'fling' the drawer open, it currently operates on the principle of "what drawer position is the estimated scroll stop position closest to?". If that's what you're looking for flexibility on, let me know and I can see what I can do. If you have any propositions for how the behavior could change for a 'light' mode, let me know. It currently operates using a UIScrollView, for reference.

> The other small change would be adjusting the speed of using setDrawerPosition

Good news here! Pulley does have a way for you to customize this. You can customize a variety of the animation options using these properties on PulleyViewController:

```swift

    /// The animation duration for setting the drawer position
    @IBInspectable public var animationDuration: TimeInterval = 0.3
    
    /// The animation delay for setting the drawer position
    @IBInspectable public var animationDelay: TimeInterval = 0.0
    
    /// The spring damping for setting the drawer position
    @IBInspectable public var animationSpringDamping: CGFloat = 0.75
    
    /// The spring's initial velocity for setting the drawer position
    @IBInspectable public var animationSpringInitialVelocity: CGFloat = 0.0

```

If those aren't sufficient, let me know and I can explore some other options.

Thanks!

**Comment by mattbarker016** [comment]
I'm so sorry I missed those variables; thank you!

After starting from an initial `.partiallyRevealed`, I changed my `supportedDrawerPositions` to two positions: `.open` and `.collapsed`. It's a big jump from the bottom to top of the screen, and I roughly need to move the drawer around 80 points before it goes from `.collapsed` to `.open`. If I don't do it enough, it'll bounce a bit in it's current position, almost like it's being stubborn (I love giving emotions to my UIViewAnimations). I think DrawerKit's implementation is ideal because it lets you decide just how much of a drag causes the motion to count, where it moves toward the next position in that direction.

Does that make sense?

**Comment by brendan09** [comment]
I think that makes sense. I’ll work through a few options this week and see what I can come up with. Thanks for the suggestion!

**Comment by mltbnz** [comment]
I would also love to see the drawer snapping into position when dragged over/under the `.open` or `.collapsed` position like it does in Maps. That is the only difference I feel when using it.

**Comment by brendan09** [comment]
Alright. I took a shot at implementing something to allow this in Pulley. It's currently on master, for anyone who wants to try it. (I'm not going to push it out to CocoaPods until I've had some favorable reports that it behaves how you'd like). You can set your current project to pull 'master' in your Podfile, if you'd like to try it in your current project.

I've added a new 'snapMode' variable + enum to Pulley.

By default, it's value is `.nearestPosition`. But, you can change this to `.nearestPositionUnlessExceeded(threshold: CGFloat)` to change the behavior to what I think you're looking for. I've found a threshold value of 20.0 seems to work well.

If anyone wants to give this a try and let me know if this is helpful to you, please do. I'll hold off on pushing to CocoaPods until I hear good things, or modifications I should make first.

Thanks!

**Comment by brendan09** [comment]
Tagging @mattbarker016 @mltbnz and @AAAstorga since you guys seem interested in this.

**Comment by mattbarker016** [comment]
Wow, the drawer feels so much more natural! This is a great enhancement. I think you should make the resulting physics from using `let threshold = 20.0` the new default!

**Comment by brendan09** [comment]
@mattbarker016 Excellent! Exactly what I was hoping. I'm open to changing the default, however I have concerns about backwards compatibility.

I'm dramatically refactoring the implementation of this now, so I may go ahead and set it as the default.

Thanks for the feedback!

**Comment by brendan09** [comment]
Okay, played with it a bit more and decided to go ahead and default the new behavior. Good call.

It's uploading to CocoaPods now, and should be available for a pod update later this evening.

**Comment by mattbarker016** [comment]
Awesome! Thanks for such a quick turnaround time, this is going to make our [AppDev](https://github.com/cuappdev) project demo for tomorrow!

This is a little off topic, but how would I go about increasing the gesture recognizer frame for the drawer? It's a bit tricky because it's not only a view controller, but the gesture recognizers themselves are hidden within Pulley (which I don't mind, my own attempt to mimic this view wasn't anywhere as good!) 

But basically, if a user wants to swipe up and misses the collapsed drawer by a bit, the gesture could still be recognized and fired. Any thoughts about that implementation?

**Comment by brendan09** [comment]
So, Pulley doesn't actually manage any gesture recognizers. It uses a UIScrollView for a more 'natural' scroll feel.

The scrollview is a custom subclass that makes certain areas of itself 'transparent' to touches. In Pulley's case this is anywhere there isn't a drawer, so the touches get passed on to your main content VC.

Pulley implements the protocol `PulleyPassthroughScrollViewDelegate` to tell the scrollview which areas should be transparent to touches, and which touches the scrollview should intercept (to scroll, or handle as it typically would).

This delegate implementation isn't marked as being 'open', because it uses internal-only variables to compute the touch regions. Without access to those, subclassing it and overriding it wouldn't be very useful. You'll (unfortunately) need to fork Pulley and modify that delegate implementation. If you get something that works well and has a little bit of a 'buffer' distance for grabbing touches, feel free to open a PR and I'm happy to consider merging it.

**Comment by brendan09** [comment]
I'm going to go a head and close this issue since it's resolved, but feel free to post any questions you have here and I'll keep answering.

**Comment by mltbnz** [comment]
Great addition. Thanks
