### ISSUE TITLE
Pulley Pod Installing with Wrong Swift Version

### ISSUE THREAD

**Issue by CareerFairPlus** [52inc/Pulley#136]
I'm having an issue where when installing Pulley through CocoaPods the Swift Language Version is always set to 3.2.  I then have to manually go change it to 4.0 or else I get several errors on build.

This doesn't seem to be a problem that other devs are having, so is there a configuration issue I might be having?

Thanks for any help!

**Comment by brendan09** [comment]
Is your project currently using Swift 3.2?

**Comment by CareerFairPlus** [comment]
No, I have the **Swift Language Version** set to 4.0.  The same is true for the Pods project.

**Comment by brendan09** [comment]
What version of CocoaPods are you using?

If you look in the repo at the .swift_version file, as well as the podspec file, they're both set to Swift 4.0. Those are the 2 things that CocoaPods looks for when configuring targets. 

I'd recommend making sure you're using the latest version of CocoaPods. The Cocoapods issue here concerns the problem that you're seeing: https://github.com/CocoaPods/CocoaPods/issues/6791

It looks like they're addressing the problem in the next release of CocoaPods, via this PR: https://github.com/CocoaPods/CocoaPods/issues/7134

In the mean time, you can work around it with a post_install hook in your podfile: 

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == '<insert target name of your pod here>'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by CareerFairPlus** [comment]
Yeah, this is exactly what I was looking for.  I'm on CocoaPods v1.3.1, which looks like the latest release version.  I see that they have a beta out for v1.4.0, so I'll try updating to that and see if that takes care of the issue.

**Comment by dnkoutso** [comment]
1.4.0.beta.2 does *not* include the `swift_version` DSL yet. It will be in 1.4.0.beta.3 or 1.4.0.rc.1.

**Comment by CareerFairPlus** [comment]
Thanks for your help with this.  The workaround you posted earlier worked well.
