### ISSUE TITLE
Crash when returning to pulley view controller 

### ISSUE THREAD

**Issue by skander300** [52inc/Pulley#138]
whenever i push another view controller from PulleyViewController then i go back to Pulley View via 

> navigationController.popToViewController(previousController, animated: animated)

where previousController is an object of PulleyViewController.

My app crashes.

Any help ?

**Comment by brendan09** [comment]
Can you post the stacktrace from your crash, as well as any console logs? There isn’t much I can do without more information, unfortunately.

**Comment by skander300** [comment]
I sounds a little weird , but xcode provides with no log.
It's like a pushed a view controlled with a bad storyboard id.

**Comment by brendan09** [comment]
There will be a stacktrace or _something_ in the console. It’ll give you some error (even if it’s a SIGABRT), and a stacktrace. 

I’ll need console logs / stacktrace or a sample project exhibiting the issue in order to be of any assistance.

**Comment by skander300** [comment]
Sorry, false alarm.
Another pod was was causing the crash.
