### ISSUE TITLE
Is it possible to skip one step when the drawer is pulled higher than the partially revealed height?

### ISSUE THREAD

**Issue by ima-tech** [52inc/Pulley#139]
Right now, you can only go from collapsed to partially open to fully open. Is there a way when you pull on the drawer from collapse to go directly to full screen?

**Comment by brendan09** [comment]
Yes. If you don’t want to support the partially revealed state you can remove that option from your supportedDrawerPositions that you provide in your implementation of PulleyDrawerViewControllerDelegate that your drawer view controller implements.

**Comment by ima-tech** [comment]
Ok sorry, maybe that’s not what I meant.

I want the following states:

- Collapsed
- Partially revealed
- Fully open.

However, when it is collapsed and I pull on it, it returns to partially revealed and I then have to pull it up again to get into the fully open position. I meant, is there a way to say: hey, if you’ve been dragged higher than the partially revealed height, go to state fully open?

**Comment by ima-tech** [comment]
I have an issue with doing an action twice, I don't particularly like that effect and would like to disable it. How would you recommend I do this?

![screenrecording_12-15-2017-14-00-25](https://user-images.githubusercontent.com/4521643/34056349-a29c1536-e1a0-11e7-9724-de5da41dad49.gif)

**Comment by brendan09** [comment]
Sure, you can set the snapMode property to .nearestPosition and that should give you what you’re looking for.

The default should do that too, but it looks like there’s a bug in the math causing the effect you’re seeing. Changing the snapMode will fix it, however.

**Comment by ima-tech** [comment]
Thank you!

**Comment by brendan09** [comment]
@ima-tech I just pushed an update to Pulley (2.2.3) that fixes the issue you saw with the default snapMode. If you'd like you can update Pulley and revert back to the default snapMode. You'll get some better behavior with swipes being able to more easily open the next drawer position.

**Comment by ima-tech** [comment]
Works perfectly thank you!
