### ISSUE TITLE
Is there a way to prevent the drawer from being in the fully open position

### ISSUE THREAD

**Issue by ima-tech** [52inc/Pulley#140]
I want to prevent the drawer from being in the "open" state. I tried to return only this:

```
public func supportedDrawerPositions() -> [PulleyPosition] {
       return [PulleyPosition.collapsed, PulleyPosition.partiallyRevealed];
    }
```

but that doesn't prevent the drawer from reaching maximal height. I would love to just have the collapsed and partially revealed state.

**Comment by brendan09** [comment]
Are you putting it in your drawer view controller? And marking that your drawer view controller implements PulleyDrawerViewControllerDelegate?

I just made that changed in the Drawer View Controller in the sample project and it worked as expected.

**Comment by ima-tech** [comment]
Ok, sorry for bothering. My issue was that I wasn't calling self.setNeedsSupportedDrawerPositionsUpdate(); since I was dynamically updating the 

> supportedDrawerPositions

.
