### ISSUE TITLE
Passing data between embedded ViewControllers

### ISSUE THREAD

**Issue by Nerkyator** [52inc/Pulley#141]
Is there a way to pass data between embedded view controllers? I'm just trying to do a little Apple maps clone and I'm wondering how to pass mapView region to the search view controller but I can't find a correct way...am I missing something?

**Comment by Nerkyator** [comment]
Using PulleyViewController var in delegate methods will do the trick.

**Comment by EmanueleVolpato99** [comment]
Can you explain with code please?
