### ISSUE TITLE
How to emulate Maps marker selected view

### ISSUE THREAD

**Issue by appsird** [52inc/Pulley#143]
Again, thank you for this very clean implementation.

Launch Apple Maps, then press and hold to create a new marker. Note when doing so, a new view appears from bottom which contains marker properties, e.g. long/lat, directions, etc.

How might this marker edit view behavior be emulated in the pulley example?

**Comment by brendan09** [comment]
There’s an issue discussing an approach to accomplish this here: https://github.com/52inc/Pulley/issues/89

I’ve pointed a few dozen people towards that conversation and they seem to have accomplished that effect. However, I’ve not tried it myself so your results may vary.

If you have any questions on that conversation, let me know and I’ll try to answer the best I can.

Thanks!
