### ISSUE TITLE
Pulley is missing the drag indicator?

### ISSUE THREAD

**Issue by sejr** [52inc/Pulley#149]
I have added Pulley to my project but, unlike the demo pictures on your repository, I don't see the little gray drag indicator. Is there something else I have to do to add this? Do I have to make it myself?

**Comment by brendan09** [comment]
The pictures are of the demo project, which includes some UI elements. You'll have to make this UI element yourself and add it to your view controller. You can look at the sample project for an example of how it was made.

Note: If you allow Pulley to do the iPad left-side presentation then your view controller is also responsible for making any UI adjustments necessary (including adjusting spacing and the location of the grabber).

**Comment by pkamb** [comment]
Had the same question. Here is the grabber in the demo app, for anyone else who's looking for it:

Storyboard: UIView `36x5`

    @IBOutlet var gripperView: UIView!

and:

    gripperView.layer.cornerRadius = 2.5
