### ISSUE TITLE
Content view controller distortion on device rotate

### ISSUE THREAD

**Issue by sejr** [52inc/Pulley#151]
When I rotate my device while on a view with this pulley controller, the content view frame doesn't adjust appropriately.

**Comment by brendan09** [comment]
Can you provide a screenshot or short video showing the issue? I believe the sample project has rotation working correctly. Ideally, if you could show the issue in the sample project that would be the most helpful as it would rule out any of your own implementation as the underlying issue.

Thanks!

**Comment by sejr** [comment]
That was a snappy reply! I was going to upload the image, but then I realized it was more likely an issue with the MapView I have inside my controller. I have fixed the issue by fixing constraints on that MapView.

Thanks though for all of your work on this!
