### ISSUE TITLE
Disable fully expand mode?

### ISSUE THREAD

**Issue by MiladFaridnia** [52inc/Pulley#152]
Hi
And Thanks for your perfect library.
I want two states for my bottomsheet 1- collapsed 2- partially Revealed. I don't need fully expand mode.
How can I disable it ?

**Comment by brendan09** [comment]
You can disable expanded mode by implementing `PulleyDrawerViewControllerDelegate` in your drawer view controller. 

Return array of the drawer positions you want to support for the function:

```swift

func supportedDrawerPositions() -> [PulleyPosition] { }

```

There's an example in the Sample project that returns 'all' here: https://github.com/52inc/Pulley/blob/master/Pulley/DrawerContentViewController.swift#L56
