### ISSUE TITLE
Adding different/more drawer positions

### ISSUE THREAD

**Issue by rdougan** [52inc/Pulley#153]
Thanks for the great library!

I'd like to support multiple drawer positions in an app I'm making. The way you have setup the code + delegate means that the drawer only supports collapsed, partially revealed, open and closed.

One way it could be done is by changing the delegate method supportedDrawerPositions to return Int values for the various supported positions, then other delegate methods that would enabled/disable the open/closed positions.

Is this something you have thought of before? Do you have any suggestions on how it could be implemented in the library? I can implement it and submit a PR, but I wanted to get your feedback before making any changed.

**Comment by brendan09** [comment]
I’ve considered it, however I’ve not been a fan of arbitrary drawer positions. Apple Maps generally uses a fixed number of positions for both consistency and coordinating “states”. 

There’s no easy way to add support for this to Pulley in its current form, and I’m not likely to accept a PR enabling it.

**Comment by rdougan** [comment]
Understood.

The UI I'm building needs 1 extra position, so I shall fork and modify as needed.
