### ISSUE TITLE
What's the proper way to query the drawer position?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#154]
I know about `func drawerPositionDidChange` but this is only called when the position changes.

In my scenario I simply need to check the current drawer state. Not sure how to do this from the Drawer Content View Controller.

Thanks

**Comment by brendan09** [comment]
From within your drawer content view controller or main content view controller you can reference PulleyViewController using self.parent:

```swift
let drawerState: PulleyPosition? = (self.parent as? PulleyViewController)?.drawerPosition
```
