### ISSUE TITLE
.closed not fully closed on iPad

### ISSUE THREAD

**Issue by daniel-choi** [52inc/Pulley#156]
Thank you very much for the neat library!

On iPads .closed doesn't fully close the drawer (Demo app as well as my own app). I simulated below screenshot by adding ```pulleyDrawerVC.initialDrawerPosition = .closed``` in the AppDelegate in demo app.
![simulator screen shot - ipad pro 9 7-inch - 2018-01-31 at 14 30 18](https://user-images.githubusercontent.com/2504659/35651202-b4ad5934-0693-11e8-9853-f635a92a2234.png)

**Comment by brendan09** [comment]
.closed isn’t currently supported for the iPad layout, as it doesn’t touch the edge of the screen (where it would ‘close’ into). 

Although this should be added to the documentation (it’s currently missing), it is expected behavior.

**Comment by daniel-choi** [comment]
Got it! Yes, documentation would be helpful as well :) 
Thank you!

**Comment by funkenstrahlen** [comment]
I just discovered this too. Is there any workaround for this issue?

@daniel-choi How did you solve it?

**Comment by funkenstrahlen** [comment]
I discovered a workaround! I change the display mode to drawer on closed position.

```swift
    func drawerPositionDidChange(drawer: PulleyViewController, bottomSafeArea: CGFloat) {        
        switch drawer.drawerPosition {
        case .closed:
            // on iPad the display mode is panel. However in panel mode the collapsed position is currently not supported. Therefore the panel is not actually hidden in collapsed position. Therefore we change the mode to drawer when closed to hide the panel. The mode is changed back to automatic / panel when the drawer position changes again to be displayed
            drawer.displayMode = .drawer
        default: drawer.displayMode = .automatic
        }
    }
```
