### ISSUE TITLE
How to set the drawer position from DrawerContentViewController?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#157]
I'm able to change the drawer position from PulleyViewController like this:

`self.setDrawerPosition(position: .partiallyRevealed, animated: true)`

But I want to set it from the DrawerContentViewController. I tried using it but it said it was deprecated. What's the best way to set the drawer position from another view controller?

Thanks

**Comment by brendan09** [comment]
You should use the non-deprecated version of that method:

‘’’Swift
public func setDrawerPosition(position: PulleyPosition, animated: Bool, completion: PulleyAnimationCompletionBlock? = nil)
‘’’

You can access Pulley from your drawer like this:

‘’’swift
let pulley = (self.parent as? PulleyViewController)
‘’’
