### ISSUE TITLE
Not able to access primaryviewcontroller items in XCUITesting

### ISSUE THREAD

**Issue by APavanKumar** [52inc/Pulley#162]
Integrated Pulley in my application. It is working well and good but when I am writing UITestcases for my project not able to access primaryviewcontroller uielements. Always getting empty results when I am accessing elements with there respective identifiers. 

Can any one suggest what is the solution.

**Comment by brendan09** [comment]
I'm afraid I can't offer much assistance, other than to mention that the primary view controller is actually _behind_ a transparent view that proxies touches through itself. This may interfere with how you're traversing the view hierarchy.

**Comment by ip19** [comment]
Hi, I have the same problem with Pulley when try to create XCUItests. So, "PulleyScrollView" just cover UIView by transparent container and all needed elements such as buttons, textFields aren't accessible to tap. Can you advice something how to solve current issue?

**Comment by brendan09** [comment]
@ip19 I don’t have any advice on solving the issue. I don’t know enough about XCUITest to help you traverse the view hierarchy.

The elements can be tapped, but because they aren’t directly in the top most view it makes traversing the view hierarchy to find them more difficult.

**Comment by grifas** [comment]
@APavanKumar  @ip19 Any solution for this issue ?

**Comment by ip19** [comment]
Hi @grifas I have resolved it using "tap on coordinate"

    func tapOnElementUnderPulley (_ XCUIElelment: XCUIElement, xCoordinate: Double, yCoordinate: Double) {
        XCUIElelment.coordinate(withNormalizedOffset: CGVector.zero)
            .withOffset(CGVector(dx:xCoordinate,dy:yCoordinate)).tap()
    }

where XCUIElement is your element which you have to tap. I tried 10;10 coordinates, please, try something inside of the element. Hope that it will help

**Comment by grifas** [comment]
@ip19 yeah I founded this solution too but maybe coordinates are not the same on others devices ?

**Comment by grifas** [comment]
I think I found the solution. I set to false the `isAccessibilityElement` property of the contentViewController's view. 

And in my test I recorded the tap action on the button to find it.
