### ISSUE TITLE
Customize the height of open state of the drawer

### ISSUE THREAD

**Issue by sasquatchgit** [52inc/Pulley#164]
Delegate methods provide a way to customize the height of the "Collapsed" or "Partially Revealed" states of the drawer, but I want to change the height of drawer when it is fully open. Is it possible?

**Comment by brendan09** [comment]
You can adjust the “topInset” property on PulleyViewController to change that. Note that unlike the delegate methods (which are height from bottom of the screen), this is distance from top of screen.

Make sure you change “topInset” and not “panelTopInset” as that’s something different.
