### ISSUE TITLE
Move down the drawer on iPad

### ISSUE THREAD

**Issue by daniel-choi** [52inc/Pulley#165]
Hello!
Is there a way to move the drawer little bit down on iPad? I have a view on top of the screen and the drawer is blocking the view when it's in default position.
I've tried to modify panelInset but this results breaking the actual drawer like the screenshot below. Is there more natural way to do this?

Thank you!

![simulator screen shot - ipad pro 12 9-inch 2nd generation - 2018-02-08 at 18 20 17](https://user-images.githubusercontent.com/2504659/36008573-c593545a-0cfc-11e8-8457-4fdd58948665.png)

**Comment by brendan09** [comment]
Hello! Sorry about that. I have 2 things for you that will help.

1. Yesterday I released version 2.2.6, which separated the panelInset property into separate leftPanelInset and topPanelInset properties. This will help the part where the drawer is shifting further right as you increase the value.
2. As I type this, version 2.2.7 is being pushed to CocoaPods. This will fix the issue you've found where setting the new topPanelInset property to a non-default value causes layout problems.

In the next few minutes you should be able to run `pod repo update` and then `pod update Pulley` to get the latest version (2.2.7).

Please let me know if you have any issues, and thanks for the bug report!

**Comment by daniel-choi** [comment]
Just updated and verified. It works great! Thanks!
