### ISSUE TITLE
I am getting a flickering whenever drag ends from collapsed to partially revealed. 

### ISSUE THREAD

**Issue by tennydesign** [52inc/Pulley#166]
I'm using a blur effect background (not the white UIView) and I also changed the controls inside the content area to a collection view. It's working just fine. Just whenever the drawer is about to collapse or about to reach the partially revealed state it blinks. This doesn't happen in the Open state. 
The blink is an: Alpha 0 -> 1 in 0.0xx seconds. Type of animation. Been hunting for the "animated: true" that I can turn off to solve the issue, been turning off lots of them. None seem to address the problem. 

I know why. But don't know how to solve it. Why: 
- drawer.drawerBackgroundVisualEffectView = nil  <- this is nil in my code. So, when transitioning the drawers I have no "backdrop" to protect the map to show in the "blink". If I comment the nil attribution, then it won't blink. I guess it will, but the backdrop will protect the user from seen the map through it. 

Now, I really need it to be nil. Cause I'm working with "floating cards".  So, how can I stop the content that goes above the drawer.drawerBackgroundVisualEffectView from blinking after the "end drag" release? 

(By the way, kick ass control! congrats!)

**Comment by tennydesign** [comment]
I am, thanks for the info, but I just found the animated: true I need to kill, this one: 
            switch snapModeToUse {
                
            case .nearestPosition:
                
                //Solved: Changed to false solved flickering.
                setDrawerPosition(position: closestValidDrawerPosition, animated: false)

Now, the bouncing is looking horrible (of course), as the drawer is snapping hard. But the alpha thing is over. Any idea what can I change inside the setDrawerPosition func to preserve animation, only not cross-fade. ? 
Thanks for the quick reply man.

**Comment by brendan09** [comment]
>  Any idea what can I change inside the setDrawerPosition func to preserve animation, only not cross-fade.

Calling setDrawerPosition _won't_ cause Pulley to crossfade anything. The only things that crossfade are setting a new drawerViewController or a new primaryContentViewController with animated: true.

However, setDrawerPosition _does_ reach out to your drawer / primary content delegates and allow them to run code. If you have any code in `drawerPositionDidChange` in your drawer VC, primary content VC, or PulleyDelegate that would cause a crossfade or change in alpha, then that may be your problem as it will be called _during_ the animation block if animated is set to true.

> I am, thanks for the info, but I just found the animated: true I need to kill, this one:

If you don't have any code in one of those delegate methods causing issues: Before changing too much else, I'd try removing the layer.cornerRadius rounding (leaving them square) and see if it changes anything.

**Comment by tennydesign** [comment]
Just did but the behavior persists. I'm not using the delegates at all.. So weird. Like that animated false kills it. So here is the structure I have: 
<img width="361" alt="screen shot 2018-02-17 at 16 41 38" src="https://user-images.githubusercontent.com/17029800/36347027-74457c70-1401-11e8-85a1-0f49a7406151.png">

Then that's the xib im loading: 
<img width="269" alt="screen shot 2018-02-17 at 16 42 28" src="https://user-images.githubusercontent.com/17029800/36347032-9f7f0122-1401-11e8-9023-714766ec0c8e.png">

So the collection view loads the xib. The corner radius in the second view in the hierarch. It's just incredible that if I turn the animation to false, it stops flickering, but also snaps to hard, loses its charm. 

But you are right, I can't seem to find anything related to alpha or anything. Is there a possibility this a delay on the swap of "drawers" ?

**Comment by tennydesign** [comment]
Solved it man. Commented THIS line: 

<img width="971" alt="screen shot 2018-02-17 at 16 48 16" src="https://user-images.githubusercontent.com/17029800/36347056-6270b55e-1402-11e8-82fc-c9efb8bedd5a.png">

Think its safe? That's the line causing the flickering.

**Comment by brendan09** [comment]
> That's the line causing the flickering.

This causes Auto Layout constraints to be updated and tells the view layout to update itself to be 'current' with respect to the constraints / current frame. I don't recommend commenting it out, as there may be unforeseen side-effects that occur from the view layout not being updated when it should be. setDrawerPosition is used in a wide variety of circumstances, for example: During orientation changes, during iPad resize events, and more. You may see problems in some of these (or other) scenarios.

Are you doing anything in -viewDidLayoutSubviews or -viewWillLayoutSubviews in your view controller? or in 'layoutSubviews' in your collection view cells? Calling layoutIfNeeded will cause the code in these methods to execute. I'd try to figure out if something in one of those places is actually what's causing your problem. Things that might be causing issues include: invalidating the collection view layout, altering selection state, creating or setting the drawer visual effect, etc. If you have code in these places, I would try commenting out various sections and see what happens. I would treat the solution you've found as a last resort and try to find the actual issue that causing a layout pass is triggering.

**Comment by tennydesign** [comment]
I don't have anything messing with the alpha on those delegates, but I saw this: https://stackoverflow.com/questions/31361842/why-layoutifneeded-allows-to-perform-animation-when-updating-constraints . And I'm wondering.. maybe the animation closure is setting a delay timer in the animation. So what I did is, I took it off and it looks like this now: 

            UIView.animate(withDuration: animationDuration, delay: animationDelay, usingSpringWithDamping: animationSpringDamping, initialSpringVelocity: animationSpringInitialVelocity, options: animationOptions, animations: { [weak self] () -> Void in
                
                self?.drawerScrollView.setContentOffset(CGPoint(x: 0, y: stopToMoveTo - lowestStop), animated: false)
                
                // Move backgroundDimmingView to avoid drawer background being darkened
                self?.backgroundDimmingView.frame = self?.backgroundDimmingViewFrameForDrawerPosition(stopToMoveTo) ?? CGRect.zero
                
                if let drawer = self
                {
                    drawer.delegate?.drawerPositionDidChange?(drawer: drawer, bottomSafeArea: self?.getBottomSafeArea() ?? 0.0)
                    (drawer.drawerContentViewController as? PulleyDrawerViewControllerDelegate)?.drawerPositionDidChange?(drawer: drawer, bottomSafeArea: self?.getBottomSafeArea() ?? 0.0)
                    (drawer.primaryContentViewController as? PulleyPrimaryContentControllerDelegate)?.drawerPositionDidChange?(drawer: drawer, bottomSafeArea: self?.getBottomSafeArea() ?? 0.0)
                    
               //     drawer.view.layoutIfNeeded()
                }

                }, completion: { [weak self] (completed) in
                    if let drawer = self {
                        drawer.view.layoutIfNeeded()
                    }
                    self?.isAnimatingDrawerPosition = false
                    self?.syncDrawerContentViewSizeToMatchScrollPositionForSideDisplayMode()
                    
                    completion?(completed)
            })
        }

Think its okay considering your logic? Now that the block is after the completion the delay is not happening anymore.

**Comment by brendan09** [comment]
> I don't have anything messing with the alpha on those delegates, 

There are more things than alpha that can cause UIVisualEffectView glitches. For example, clipping via the cornerRadius property (and others). Even adjusting frames can trigger some of these glitches, if the circumstances are correct. It's a _very_ touchy component.

> Think its okay considering your logic?

It will correct the layout afterwards, but it will prevent it from animating alongside other transitions. For example, alongside the orientation change or resizing events. It's something that I advise against. When designing Pulley, a good deal of effort went into making sure there weren't visual artifacts (like from Pulley's UIVisualEffectView) during live-resizing / drawer position animations. I would recommend figuring out what specifically in your code is causing the issue, and fixing that, rather than modifying Pulley (and therefore having to maintain your own fork / branch) to hide the underlying issue.

**Comment by tennydesign** [comment]
Will do. Thanks man. Just for the record, a negative visual result of my proposal above is the "bouncing" caused by the spring dumping acts weird in the simulator. On iphoneX it seems okay, but simulator for other models shows a crazy spring effect. So... code above is a no go. Will dig deeper and try to keep the source file clean. 
Hey, thanks a lot man. REALLY appreciated it. Have a great weekend. 🖖
T

**Comment by brendan09** [comment]
No problem! Happy to help. If you'd like a second set of eyes to take a look, feel free to post a sample project with the issue and I'll be more than happy to take a look.

Have a good weekend!

**Comment by tennydesign** [comment]
Hey @brendan09 update, got it fixed. Here is the cause, I was updating again the layout constraint in a late stage (after the layoutIfNeeded() executed). So it was a causing a late blink. It was about moving the headerSectionHeightConstraint.constant attribution to the viewWillLayoutSubviews() instead. And now its smooth. 
Just logging this here in case anyone falls into the same trap. 
Thanks buddy!
T
