### ISSUE TITLE
Transitioning from the primary view to the drawer view

### ISSUE THREAD

**Issue by nachonavarro** [52inc/Pulley#167]
Hi!

Is there a way to transition with Pulley from the primary view (e.g. a map) to the drawer view instead of having the primary view on the background even when the position is .open? Something like this app, where if the user keeps scrolling down, the drawer view becomes the only view available:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/15170903/36385169-b7dd037a-1589-11e8-9973-a63ed081172d.gif)

My apologies if this isn't the right place to ask.

**Comment by brendan09** [comment]
You can accomplish something similar to this, however _technically_ the primaryContentViewController will always be in the background behind the drawer.

You could accomplish something similar by changing the following settings:

* Change the `drawerCornerRadius` to 0.0
* Change the `shadowRadius` to 0.0
* Change the `topInset` to 0.0
* Change the `backgroundDimmingOpacity` to 1.0

Note: The `topInset` being set to 0.0 will stop it just under the status bar (or notch on iPhone X). Your primaryContentViewController should handle the background of the status bar, for example by using a solid color rectangle like your example gif.

Let me know if. you have any questions!

**Comment by nachonavarro** [comment]
Thank you, works like a charm!
