### ISSUE TITLE
Is there a way to make the collapsed drawer to do a little jump

### ISSUE THREAD

**Issue by zaehk** [52inc/Pulley#169]
Hi!

First of all let me thank you for all the effort you put in Pulley. I've been using it a bit and its perfect so far. My question is about the movement of the collapsed drawer. 

In my app i need to notify the user that the drawer has some change by making it do a little jump or bounce. Then the user will slide it up to view the view inside.. is there any way to achieve this effect? 

Thank you very much for your time, kind regards.

**Comment by brendan09** [comment]
There are a few ways that are a bit hacky that you could do it...rather than suggest those, I'm going to write a quick feature into Pulley itself to let you bounce the drawer. That way it'll be a simple call like "drawer.bounce()".

I'll comment back here once it's available. Thanks!

**Comment by brendan09** [comment]
@zaehk Alright, I've pushed a new version of Pulley to Github and CocoaPods (2.2.8). You may need to run `pod repo update` before running `pod update Pulley` for CocoaPods to find the new version.

You can see an example of it being used here: https://github.com/52inc/Pulley/blob/master/Pulley/DrawerContentViewController.swift#L64

There are also optional parameters to the function call that will let you customize the bounce height and speed.

Let me know if you have any questions!

**Comment by mattbarker016** [comment]
Lightning fast, man!

**Comment by zaehk** [comment]
Uoh that was fast, i dont know how to thank you enough for this! its perfect!
