### ISSUE TITLE
Search bar disappears after swapping drawers

### ISSUE THREAD

**Issue by daver234** [52inc/Pulley#173]
I have a drawer VC (VC1)  with a search bar at the top. The drawer has a container view below the search bar that loads a tableview with grouped static cells (the reason for the container).  I tap on a cell in the container and load a different VC...call it VC2.  That works fine

Then when I user hits the close button on VC2, I use setDrawerContentViewController to load VC1 again.  The problem is that the search bar doesn't show.  The gripper is there and the container view is there but not the search bar.  Might just be my issue but just checking to see if you have seen something similar.   Here are screen shots. 

![screen shot 2018-02-28 at 6 00 38 pm](https://user-images.githubusercontent.com/5413207/36823530-72b747da-1cb2-11e8-90ab-046cb819da75.png)
![screen shot 2018-02-28 at 6 00 54 pm](https://user-images.githubusercontent.com/5413207/36823533-77ca966e-1cb2-11e8-9545-ea16ca868a77.png)

**Comment by brendan09** [comment]
I haven’t seen anything similar, unfortunately. My recommendation would be to use the snapshot view hierarchy button and see if it’s in the layout somewhere (out of place) or log the frame in viewDidLayoutSubviews of your view controller and see where it’s trying to render.

**Comment by daver234** [comment]
One interesting thing I found is that when I set VC2 setDrawerPosition to .collapsed the searchBar displays.  It doesn't display if I use .partiallyRevealed when returning to VC1.  Any chance this could indicate that it is in Pulley?  

Also, when set to .partiallyRevealed, the search bar is there for a 1/3 second and then animates away towards the upper left corner of the drawer.  Any clues from this behavior?

**Comment by brendan09** [comment]
That typically indicates it’s an issue with your layout not resizing correctly. I’d recommend checking your Auto Layout constraints. Pulley doesn’t do anything with the sub views of your drawer view controller. It only manages adding the drawer view controller’s view to the screen and giving that view a frame/size. How your sub views layout for a given view frame is beyond what Pulley manages.

**Comment by daver234** [comment]
Ok I found a way to work around for now.  

By the way, is there any issue of using a tab bar controller and have the pulley view be one of the tabs?

Thanks for the great work.

**Comment by brendan09** [comment]
I don’t think it would be a problem, but I would recommend setting the tab bar to not be translucent (or else the bottom of the drawer will extend under the tab bar). 

However, I haven’t tried it so I don’t know for sure.

**Comment by daver234** [comment]
Just tried adding a tab bar.  No problem.  Simple.  Works.  Thanks.
