### ISSUE TITLE
Navigation doesn't work

### ISSUE THREAD

**Issue by adriaros** [52inc/Pulley#175]
Hello, first of all, congratulations for the pulley. Is wonderful!

I have put a button inside the "pulley" and when I click I want to see another ViewController but with "Back" button. The issue is that if I do it using the navigation controller, in xCode the upper navigation bar is shown but at the time of execution it is not displayed.
Do you know where the problem is?

In xCode:
<img width="324" alt="screen shot 2018-03-02 at 3 12 00 pm" src="https://user-images.githubusercontent.com/9952638/36902824-1d2946bc-1e2c-11e8-8ae2-c699e12890d7.png">

Iphone:
<img width="324" alt="screen shot 2018-03-02 at 3 13 12 pm" src="https://user-images.githubusercontent.com/9952638/36902873-413e123a-1e2c-11e8-9e6b-31923c4c504a.png">

Thanks!

**Comment by brendan09** [comment]
It looks like you haven’t setup Interface Builder properly for Pulley. Please see the instructions in the README and the sample project for how to use Pulley with Interface Builder. It’s important to note that you cannot place content directly into the PulleyViewController itself, instead you must place the content in the drawer view controller or primary view controller.

**Comment by adriaros** [comment]
Yes! The capture is not shown, but I have another view controller, so I think I followed the guide correctly. But if I want to embed the pulley in a navigation controller to show the Back button when I press the button that is on the pulley, in what class should I embed it?
You understand me?

**Comment by brendan09** [comment]
Based on your screenshot of Xcode, you haven’t setup your view controllers correctly. 

Take a look at the sample project. You’ll have the same setup as the sample project, but with a navigation controller embedding the PulleyViewController instead of PulleyViewController being the initial view controller.
