### ISSUE TITLE
Extend PulleyViewController with custom BaseViewcontroller

### ISSUE THREAD

**Issue by ankitnetwin** [52inc/Pulley#177]
Is it possible to extend PulleyViewController with my custom BaseViewcontroller. If yes then how?

**Comment by brendan09** [comment]
You’d need to download the source files to Pulley and include them in your project manually. Then you could change the class Pulley inherits from to your BaseViewController. However, I don’t recommend it and am unsure if you’ll encounter any issues.

**Comment by brendan09** [comment]
Closing this, as unfortunately it's not _possible_ to distribute a CocoaPod that does what you request. You'll have to include the code in your project.
