### ISSUE TITLE
Is there a way to change the collapsed height more times?

### ISSUE THREAD

**Issue by zaehk** [52inc/Pulley#181]
Hi! 

I've been using Pulley for over a month and i really love it.

The app i am working on needs to change the pulley collapsed height according to the main content VC items. Is there any way to change the Pulley collapsed (or partially revealed..) height once it is set up already in the "collapsedDrawerHeight()" delegate method? 

Kind regards and thank you for your good work.

**Comment by brendan09** [comment]
@zaehk Just checking in– I saw you closed this shortly after you created it. Did you get it figure out? Or do you still need assistance?

Thanks!

**Comment by zaehk** [comment]
Hi!

Thank you very much for your time. It was a mistake, i found the solution
right away.

What i've been struggling a little bit, is to make the Drawer bottom start
at some height in order to not be behind the tab bar of
PulleyViewController. ¿What delegate method or callback should i be using?
I am not sure if i am using the right approach.


My setup:

1. VC that uses the class PulleyViewController and inherits tab bar.
2. Container with VC that represents the drawer.
3. Container with VC with the content.


Result (the drawer and the table bottom inside is behind the tab bar):




Storyboard:


Again, thank you for your amazing work and time, i've been using swift only
for two months now and i apologize if i didn't understand the wiki.

Kind regards!





2018-03-16 21:32 GMT+01:00 Brendan Lee <notifications@github.com>:

**Comment by zaehk** [comment]
i am going to post the last commen on another issue if its Okay, so we can let this closed.
