### ISSUE TITLE
preventing the drawerVC from appear behind the PulleyVC tab bar.

### ISSUE THREAD

**Issue by zaehk** [52inc/Pulley#182]
Hi!

What i've been struggling a little bit with a problem. I need to make the Drawer bottom start
at some height in order to not be behind the tab bar of PulleyViewController. ¿What delegate method or callback should i be using?
I am not sure if i am using the right approach.

My setup:

1. VC that uses the class PulleyViewController and inherits tab bar.
2. Container with drawerVC.
3. Container with contentVC.

Result (the drawer and the table bottom inside is behind the tab bar):

<img width="307" alt="captura de pantalla 2018-03-17 a las 20 58 58" src="https://user-images.githubusercontent.com/9431971/37564629-18c82a8c-2a9a-11e8-9dd5-d8f5449a2492.png">

Storyboard:

![captura de pantalla 2018-03-17 a las 20 57 55](https://user-images.githubusercontent.com/9431971/37564642-5983957a-2a9a-11e8-8035-aa85d5a5cdba.png)

Again, thank you for your amazing work and time, i've been using swift only
for two months now and i apologize if i didn't understand the wiki.

Kind regards!

**Comment by brendan09** [comment]
You’ll need to implement PulleyDrawerViewControllerDelegate in your drawer VC and provide values in these 2 functions:

```func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat

    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat```

**Comment by zaehk** [comment]
You are right, in these two functions i get the correct height from the "bttomSafeArea" variable which is 49, but what should i do inside in order to make it start at that height?

now i have:

`    func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
     //
    }
    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
    //
    }
    func supportedDrawerPositions() -> [PulleyPosition] {
        return [PulleyPosition.collapsed, PulleyPosition.partiallyRevealed]
    }
    func collapsedDrawerHeight() -> CGFloat {
        return drawerHeight    //370
    }
    func partialRevealDrawerHeight() -> CGFloat {
        return 590
    }`

I understand that those functions are meant to set the drawer height but not the bottom inset in which the drawer start.

**Comment by brendan09** [comment]
You can’t adjust where the drawer starts. It will always start at the bottom of the view controller.

You have 2 options:

1. Set your view controller not to extend under the tab bar by using UIViewController’s edgesForExtendedLayout on PulleyViewController.

2. Offset the content inside your drawer by the value delivered as the bottomSafeArea.

**Comment by zaehk** [comment]
I though i could change where the drawer starts but your solution 2 works perfectly! 

I also wanted to disable and enable the shadow of the drawer when i move it. I set ShadowOpacity and Radius to 0.0 but they still present. Can this be done by code?

Thanks again, you are very helpful!

**Comment by brendan09** [comment]
Those properties change the drop shadow behind the drawer. However, what you’re looking for is not the drop shadow. You’re looking to change the background dimming view color. I would recommend reverting the changes you made to those properties, and then set backgroundDimmingColor to clear.

**Comment by zaehk** [comment]
I did that and set the dimmingColor to:

.backgroundDimmingColor = UIColor.clear 

But the shadow is still visible, i dont know if i am doing something wrong here.

**Comment by brendan09** [comment]
Try setting backgroundDimmingOpacity to 0.0.

**Comment by zaehk** [comment]
I tried but the result is the same.

2018-03-19 14:32 GMT+01:00 Brendan Lee <notifications@github.com>:

**Comment by brendan09** [comment]
I confirmed in a checkout of the Sample project that setting`backgroundDimmingOpacity` to 0.0 does solve the problem.

Make sure you're setting in viewWillAppear (or later) in the view controller life cycle. Note: You can't attempt to set it in viewDidLoad.

**Comment by zaehk** [comment]
oh, okay that was the problem. I wanted to change it when the app is
running and the tray was in state "open". Thank you very much anyway, kind
regards!

2018-03-20 22:51 GMT+01:00 Brendan Lee <notifications@github.com>:

**Comment by brendan09** [comment]
> I wanted to change it when the app is running and the tray was in state "open"

Doing it how I suggested will ensure that the background doesn't show while "open", or during the transition from partiallyRevealed to open.
