### ISSUE TITLE
Close DrawerViewController when performing segue

### ISSUE THREAD

**Issue by asher636** [52inc/Pulley#184]
Hi, I really appreciate your hard work on this library. I am using it in my project and finding it much easy and helpful to use. 

One thing I need to ask is; how can I close the DrawerViewController when performing segue from PrimaryContentViewController? I have done the following * which (in my knowledge) hides the DrawerVC, but actually it is present there and showing white space on the bottom.

* `if let pulleyViewController = self.parent?.parent as? PulleyViewController {
            pulleyViewController.setDrawerPosition(position: .closed, animated: true)
            self.performSegue(withIdentifier: "gymDetailSegue", sender: self)
        }`

**Comment by brendan09** [comment]
Unless you’ve embedded a controller inside of Pulley’s PrimaryContentViewController, Pulley should be accessible as self.parent _not_ self.parent.parent. That may cause you an issue. 

I would need to see a screenshot (or short video clip) of the problem you’re having in order to provide any assistance. There are a lot of ways your app could be setup, and not enough detail in your issue to narrow it down.

In theory, that line of code should close the drawer _as long as .closed is one of your supported drawer positions._

**Comment by asher636** [comment]
I actually embedded Pulley’s PrimaryContentViewController in a navigation controller that's why I'm using self.parent.parent. 

Below are the screenshots of my storyboard and the app running on the simulator (showing white space at the bottom). 

1. Storyboard: 
<img width="1154" alt="storyboard" src="https://user-images.githubusercontent.com/17403246/37959988-b2c9cc3c-31b4-11e8-8113-047ca84c7b36.png">

2. White space at bottom after closing DrawerContentViewController:
<img width="531" alt="white_space_bottom" src="https://user-images.githubusercontent.com/17403246/37959888-7e26f1d0-31b4-11e8-88b9-f51f3f0cf13a.png">

Thanks.

**Comment by brendan09** [comment]
This appears to be an issue with the constraints / scaling mode on your UIImageView.

If you change the background color of the view controller containing the image view, it will probably show that the view controller is properly extending to the bottom. In that case, you’ll need to adjust your constraints or scaling mode on the imageview.

With or without the drawer visible, the primary content view controller always extends to the bottom of the screen.

**Comment by asher636** [comment]
Thanks, it was an issue at my end. 

Really appreciate your help.

**Comment by asher636** [comment]
Actually I just saw that DrawerContentViewController is not letting the my ViewController (which I'm pushing from PrimaryContentViewController) to resize after it's being closed. I have checked there's no issue with the constraints, even the ViewController itself is leaving space at the bottom. I have attached two screenshots below, if you can check and let me know what the issue is. 

I would be really thankful. 
1. This image is before segue to a new ViewController. 

![image1](https://user-images.githubusercontent.com/17403246/37983391-a4abe254-31f3-11e8-9c13-39233d2748d9.png)

2. After pushing a new ViewController, keeping DrawerContentViewController closed. 

![image2](https://user-images.githubusercontent.com/17403246/37983397-a68659c4-31f3-11e8-9bd5-798565db6f55.png)

**Comment by brendan09** [comment]
That's a result of your tab bar controller, not Pulley. You can see in the hierarchy that the 'gap' at the bottom traces back to how the UITabBarController is laying out it's content view.

Pulley does not put a gap at the bottom of the primary content view controller, for any reason. Even when the drawer is there, it _covers_ it. It doesn't move or resize it.

You need to set your view controllers (entire hierarchy) to extend _under_ the bottom bar of the UITabBarController.

**Comment by asher636** [comment]
Awesome ! I already checked under Bottom Bars from storyboard but for some reason it wasn't working. I did it through the code and it worked. 

Really appreciate your help and time. 

Thank you.

**Comment by brendan09** [comment]
No problem! Glad it worked. :)
