### ISSUE TITLE
How to check whether pulleyviewcontroller is in stack or not

### ISSUE THREAD

**Issue by ankitnetwin** [52inc/Pulley#185]
I have a side menu from which i can navigate to different screens. My pulley view controller is the home screen. So if i am already on home view controller i do not want create a new instance and push that controller. I want to check the screen which is show is pulleyviewcontroller or not.

**Comment by brendan09** [comment]
This is outside the domain of Pulley itself, so I will be unable to offer assistance.

However, you can generally check if a class is a type you want by using the “is” keyword. 

If you had a variable (VC) you wanted to check, you could check it like this “if VC is PulleyViewController”.
