### ISSUE TITLE
Adding a border to the drawer?

### ISSUE THREAD

**Issue by skeeJay** [52inc/Pulley#187]
The Apple Maps app (on iOS 11, at least) has a very slim (0.25px?) border that also wraps around the corner radius. When I attempt to add a border to my drawer content view controller, it does indeed add a border to the edges, but it is cut off by the border radius. Is there a recommended way to add this border so it wraps around the corners as well?

**Comment by brendan09** [comment]
You can use the view's `layer` property.

Set the `borderColor` and `borderWidth` as normal, then set the cornerRadius property to match the drawer. You can get / set the cornerRadius for the drawer using `PulleyViewController`'s `drawerCornerRadius` property. It's available any time after `viewWillAppear` in your drawer view controller's life cycle (assuming it's Pulley loading the view, and not one loaded already).

**Comment by skeeJay** [comment]
Ah, didn't occur to me to add a border radius to the view's `layer` to match the drawer's. That works nicely, thanks.

**Comment by brendan09** [comment]
Great to hear! I'll close this issue then.
