### ISSUE TITLE
Dynamic shadowOpacity and shadowRadius

### ISSUE THREAD

**Issue by skgwazap** [52inc/Pulley#188]
These values are set only once in `loadView()`. I need to change them depending on current position. So, as I understand this is not currently possible.

**Comment by brendan09** [comment]
Ok, Pulley 2.3.2 is now available on CocoaPods.

You may need to run `pod repo update` before running `pod update Pulley`. If you've version locked the pod, you'll need to modify that as well.

Please let me know if you have any questions! Thanks
