### ISSUE TITLE
Segue Question

### ISSUE THREAD

**Issue by sdevo619** [52inc/Pulley#190]
First and foremost, thank you for creating this. I have one question. Is the process for passing data into the primaryContentViewController different from a normal segue. In my app I have an initial vc that segues to the PulleyViewController, and am trying to pass a variable through to the map ViewController, and am trying to figure out if it is similar to passing data in segue through a navigation controller, but some instructions would be greatly appreciated. Thank you very much!!!

**Comment by brendan09** [comment]
It’s very similiar, however unlike a navigation controller you’ll need to call loadViewIfNeeded() on PulleyViewControllers view before you can access the primaryContentViewController property. 

When using Interface Builder, those values aren’t set until the view is loaded, and that occurs (by default) after the prepareForSegue call. Calling loadViewIfNeeded() on PulleyViewController’s view in prepareForSegue _before_ you attempt to access primary / drawer view controllers will ensure they’re populated and ready for your data.

**Comment by sdevo619** [comment]
guard let pulley = segue.destination as? PulleyViewController else{
                
                print("no pulley vc")
                return}
            
            //print("...Is pulley vc...")
            
            pulley.loadViewIfNeeded()
            
            guard let vc = pulley.primaryContentViewController as? myPrimaryContentViewController else{
                
                print("pulley primary is not find vc in page")
                return}
            
            guard let myVar = currentVar else{
                print("no current var")
                return
            }
            vc.currentVar = myVar


Thank you for the very fast response!!! Still having an issue though. Any ideas?

**Comment by brendan09** [comment]
What problem are you having with the above code? Which guard statement isn’t working?

**Comment by sdevo619** [comment]
The guard statements are actually all working, but the variable isn't showing up in the primaryContentViewController when it loads. Do I need to give the storyboard embed segues identifiers for this to work?

**Comment by sdevo619** [comment]
Working great now!!!! Thank you very much!!!! It would probably be good to include that segue issue with loadViewIfNeeded in the documentation. I ended up needing both, 1. moving my code to didSet and 2. putting the the loadViewIfNeeded inside of prepare for segue, to get it working. I'll let you know if I find anything else. Thank you again very much!!! I was attempting to achieve similar functionality with using a single container view on top of the map, and a pan gesture recognizer, but this is far superior!!!! Great work!!!

**Comment by brendan09** [comment]
Great to hear! I'm going to go ahead and close this issue. Let me know if you have any other questions.
