### ISSUE TITLE
setContentOffset inside animation block causing problems

### ISSUE THREAD

**Issue by cschandler** [52inc/Pulley#197]
Greetings,

I was trying out this repo (both release and 2.4.0) on a small test project, and had some problems when running on an actual device (iPhone X, iOS 11.3). The drawer view would disappear during the animation block of the `setDrawerPosition(position:animated:completion)` function. It's worth noting that this behavior did not display in the simulator. Eventually I tracked the problem down to the line 

```
drawerScrollView.setContentOffset(CGPoint(x: 0, y: stopToMoveTo - lowestStop), animated: false)
```

inside the UIView animation block in the function. Pulling that line outside the animation block and using the native animation for it (by just passing in true), seems to fix the problem, but now I don't get that sweet spring and animation curve.

I'm attaching a screen recording of the problematic behavior I was seeing on device.

![pulley-test](https://user-images.githubusercontent.com/6569832/39764843-7c81d7a8-52ae-11e8-9ef3-cbd4142e2a82.gif)

**Comment by brendan09** [comment]
I just tested the current version of Pulley (sample project) on an iPhone X running iOS 11.3 and don’t see the issue you’re describing. 

Generally whenever I see reports of problems like this it traces back to some piece of code being present in the delegate methods you implement that are called by Pulley during the animation block. (Roughly 5 reports of your similar issue have traced back to some piece of code implemented in a delegate callback, or viewDidLayoutSubviews that doesn’t support animation or glitches during animation). 

My first advice would be to check that, and try removing code from those places in your drawer and main content view controllers. 

Please try testing on a device with the sample project as-is and let me know your results. Unless an issue can be replicated in the sample project (or with tweaks to the sample project), I generally consider it to be specific to your implementation and don’t prioritize it for fixes or development.

Thanks!

**Comment by cschandler** [comment]
The issue persists even when the primary and drawer view controller have no delegate functions implemented. I will continue to test other things, but since this is just a test project, everything is pretty bare bones.

**Comment by brendan09** [comment]
If you don’t mind sharing the test project, I can take a look and try to help better troubleshoot.

**Comment by cschandler** [comment]
Here is a simple test project I am using. I've modified some stuff in `PulleyViewController` since we only need the bottom orientation, but the animation code is still the same.  Again, I was not able to reproduce this issue in the simulator, only on device (which is odd in and of itself).

[CardUITest2.zip](https://github.com/52inc/Pulley/files/1984947/CardUITest2.zip)

**Comment by brendan09** [comment]
You do not need to modify Pulley in order to only support the bottom drawer display mode. 

I’ll take a look, but I definitely don’t support / leave open issues for modified versions of Pulley. If it can’t be replicated in the sample project, then it’s generally an issue you’ve introduced.

**Comment by cschandler** [comment]
True, we don't need to, but I was just experimenting. FWIW I did try the test project on my device, and it worked without issue. I'm pretty baffled right now.

**Comment by cschandler** [comment]
I think I'm going to try and walk the test project back to the state that my test project is in, and see where the two meet.

**Comment by brendan09** [comment]
I found your issue. In Interface Builder for PulleyViewController you put a '0' for "Animation Spring Damping". 

What you're seeing is what Apple's spring animation API does when you provide a '0' for Spring Damping.

Remove that and it works fine.

<img width="263" alt="screen shot 2018-05-08 at 1 55 13 pm" src="https://user-images.githubusercontent.com/1717860/39773938-749f411a-52c7-11e8-8ce3-5e1c0d95688f.png">

**Comment by cschandler** [comment]
Oh wow, welp, thanks for the extra pair of eyes!

**Comment by brendan09** [comment]
No problem! Let me know if you have any other questions.

**Comment by cschandler** [comment]
Also, thank you for being a responsive maintainer. It's good to see open source projects like this!
