### ISSUE TITLE
Allow for full screen 

### ISSUE THREAD

**Issue by daxfrost** [52inc/Pulley#198]
Hi there,

I’d like to have the ability to expand the content to full screen - is this something on roadmap or even likely to fit the implementation at all?

Many thanks
Dax

**Comment by brendan09** [comment]
The drawer can currently expand to full screen. You can adjust the distance from the top of the screen for the .open position with the -topInset property, and you can adjust the cornerRadius to 0.0 to fill the edges.

Let me know if this isn't what you're looking for.

**Comment by daxfrost** [comment]
Wow, great! Let me take a look and let you know. Thanks Brendan

**Comment by daxfrost** [comment]
Thanks this works great!
