### ISSUE TITLE
DrawerContentView differences between .open and .partiallyRevealed?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#200]
I added a collectionView to the drawer that I can swipe horizontally. It fills the drawer except for its top constraint which is the bottom of the headerView. Each collectionView cell contains its own tableView that I can swipe vertically. 

I had all of this working fine when with the supported drawer positions ".partiallyRevealed" and ".collapsed". But I recently added ".open" which has broken the layout.

I tried several things but ended up modifying the height of the collectionView cells by subtracting "collectionView.adjustedContentInset.top" to get the layout back to normal.

I'm still having trouble with the tableView inside the collectionView cells. When the table loads its contentOffset is no longer zero. I'm changing its "contentInsetAdjustmentBehavior" and trying to adjust the offset manually but am having trouble. When I transition from ".partiallyRevealed" to ".collapsed" and back again things really get messed up (testing on iPhone X which causes the headerView size to change).

I'm just trying to understand what changes with the ".open" position. It looks like the "layout scrollView" in PulleyViewController is different.

Thanks

**Comment by brendan09** [comment]
The only thing that open really changes is the height of the drawer. It only makes the drawer as tall as it’s highest supported position, and open makes it the height of the view controller, minus top inset, minus the extra bottom padding.
