### ISSUE TITLE
iPhone X extending drawer to edge of screen in landscape.

### ISSUE THREAD

**Issue by sushant40** [52inc/Pulley#201]
Hi, I have an app that displays a pulley drawer when in landscape and portrait. However... when the drawer is displayed in landscape on iPhone X it's background does not extend underneath the notch and chin (left and right) of the phone.

When inspecting with the debug navigator I can see that the plugin is making my app appear as it is.

From the screenshot below you can see the green nav bars in the corners (from the main view controller) and the drawer with blur background.

Screenshot:
![simulator screen shot - iphone x - 2018-05-22 at 16 37 02](https://user-images.githubusercontent.com/3006286/40345922-6367bc52-5dde-11e8-8be5-75445b1284b3.png)

**Comment by brendan09** [comment]
Yes, this is intended.

**Comment by sushant40** [comment]
doesn't look very nice - is there any easy way to override?

**Comment by brendan09** [comment]
No, there’s not a way at this time. If you’d like, I can add an option to disable it. It would be a week or so before it lands in the repo.

**Comment by sushant40** [comment]
Thanks!... I'd appreciate it if you can make an option to disable it. Let me know when I can use it :)

**Comment by brendan09** [comment]
@sushant40 Hello! An update to Pulley is now available on CocoaPods and master supporting this. Pulley version 2.4.1. You may need to run `pod repo update` and then `pod update Pulley` to see the update, as long as you haven't locked your Pulley version.

PulleyViewController now has the variable `adjustDrawerHorizontalInsetToSafeArea` that you can set to false. Let me know if you have any questions!

**Comment by sushant40** [comment]
Hi Brendan - looks like that worked!

Thanks for the fast turnaround.
