### ISSUE TITLE
Can't get "nearestPosition" to work right

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#202]
When the drawer is "collapsed" and I swipe up from the bottom I'd like the next drawer position to **always** be "partiallyRevealed". But in some situations, even when I swipe up slightly from the "collapsed" position, the drawer jumps straight to "open".

I've tried adjusting "nearestPosition" and the "nearestPositionUnlessExceeded" threshold value but I haven't been able to accomplish what I need.

Any suggestions?

Thanks

**Comment by brendan09** [comment]
Assuming you're using the latest version of Pulley, that should only happen if you're providing a value for partiallyRevealed height that is _less_ than the collapse height. 

The height order must be (lowest to highest): collapsed, partiallyRevealed, open.

If you can replicate it in the sample project in the repository (without modifying PulleyViewController), let me know and I'm happy to take a look.

**Comment by brendan09** [comment]
You should only change those values if you _immediately_ call `setNeedsSupportedDrawerPositionsUpdate()` after doing so. You can't have them dynamically defined.

**Comment by joeuelk** [comment]
So I discovered that if I change the supported positions to the following that the swipe up behavior I mentioned earlier occurs. I'm not sure if this is a bug but I wanted to mention it.

```
func supportedDrawerPositions() -> [PulleyPosition] {
        return [.open, .partiallyRevealed, .collapsed]
    }
```

Changing it back to .all does not allow me to jump from collapsed straight to open which is the expected behavior:

```
func supportedDrawerPositions() -> [PulleyPosition] {
        return PulleyPosition.all
    }
```

And the snapMode setting doesn't seem to make a difference.

**Comment by brendan09** [comment]
The behavior may be related to this, which a fix was merged for: https://github.com/52inc/Pulley/pull/215

I haven't pushed it out to CocoaPods yet, but you can try it on master and see if it helps.
