### ISSUE TITLE
Inconsistent distance in drawerChangedDistanceFromBottom for iPhone x

### ISSUE THREAD

**Issue by sadanro100** [52inc/Pulley#205]
Hello, first of all thank you for making this lib!

I'm using the distance from drawerChangedDistanceFromBottom to update the bottom constraint of a view to give the impression it's docked to the bottom the Drawer View Controller.

It works perfetctly on all devices except for the iPhone X, probably due to how the distance is calculated on iPhone X taking into consideration the bottomSafe area (for some reason it doesn't happen on the simulator)

This is how I uptade the constraint

    func drawerChangedDistanceFromBottom(drawer: PulleyViewController, distance: CGFloat, bottomSafeArea: CGFloat) {
        
        let dockDistanceFromBottom = self.contentView.frame.size.height - distance
        self.constraintDockViewBottom.constant = dockDistanceFromBottom
    }

There's some sort of delay on how drawerChangedDistanceFromBottom is called on iPhone X, this is what happens, notice the view holding the "Dirigir até lá" button, it bounces as the Drawer View Controller changes position:

![mp80b-vzhxn](https://user-images.githubusercontent.com/14843839/40622841-e619a6ac-6279-11e8-835b-f4d785520071.gif)

**Comment by sadanro100** [comment]
I can confirm it happens on all devices, but more frequently on iPhone X.

**Comment by brendan09** [comment]
It looks like what you’re seeing is the result of using a spring animation on views animating opposite directions from each other. 

I would guess that if you logged the bottomSafeArea / distance delivered to you by Pulley they would be consistent.

If you’d like, you can adjust the spring animation settings on Pulley to essentially disable the spring behavior.

**Comment by sadanro100** [comment]
I see what you mean. Maybe drawerChangedDistanceFromBottom doesn't get called during the animation to consider the value updates that cause the animation itself?


How can I disable the spring animation please? Setting animationSpringDamping to 0 made everything behave in a very strange way.

**Comment by brendan09** [comment]
It does get called during the animation block. Use 1.0 for Spring damping to stop oscillating. 0.0 is the opposite direction and adds more oscillation.

**Comment by sadanro100** [comment]
tried

self.pulleyViewController?.animationSpringDamping = 1

and I still have the same behaviour. To me, it looks like it like it's related to the snap effect of the drawer.

Thank you for the patience and helo anyway @brendan09

**Comment by brendan09** [comment]
You can't put it in PulleyViewController itself, you'll need to use a child-parent setup for your view controller. 

Here is a sample project showing the setup. Note that this is an older version of Pulley, so you shouldn't use the Pulley code...but you can see in the Storyboard how it's setup to accomplish this trick and you can mirror it in your project: https://www.dropbox.com/s/hurzxag6tx64zbp/Pulley-Floating%20Content.zip?dl=0

**Comment by sadanro100** [comment]
Wow!! 😳
Exactly what I needed! Thank you very very much @brendan09 !
I'm closing this issue now
