### ISSUE TITLE
modifying prototype table cell

### ISSUE THREAD

**Issue by appsird** [52inc/Pulley#206]
in IB, when I click on the Title or Subtitle in DrawerContentViewController, then width and height are greyed out in the Size Inspector. Also, when I attempt to drag the position of the Title, a green plus sign appears, and a new label is created outside the proto cell.

I removed all constraints on the entire Drawer Content View Controller and the same behavior persists. There appears something unique about this proto cell. Can you please explain how I can move and/or add new items to this photo cell, change table positions, or other.

I am using Xcode Version 9.4 (9F1027a)

Thanks,

**Comment by brendan09** [comment]
There’s nothing special about the prototype cell. If you’re wanting to customize it, make sure you’ve set the cell type to custom instead of leaving it set at one of the system provided ones.

**Comment by appsird** [comment]
Thanks so much for your prompt response... 

 I set cell type to Custom and now I am able to customize the proto cell.

thanks again for this very clean project.
