### ISSUE TITLE
Make PulleyPassthroughScrollView public?

### ISSUE THREAD

**Issue by jaybayley** [52inc/Pulley#207]
Hey guys, thanks a ton for such a great library - it's been fantastic to work with!

As the title suggests, is it possible to make `PulleyPassthroughScrollView` and `PulleyViewController.drawerScrollView` public access?

My reason for asking is i'm trying to do the following in my `primaryContentContainerView`:

```
if let scrollView = self.pulleyViewController?.drawerScrollView {
    view.addGestureRecognizer(scrollView.panGestureRecognizer)
}
```

Essentially this allows the user to pan the `primaryContentContainerView` (if it doesn't already contain a view with a `UIPanGestureRecognizer` attached) to bring up the drawer content. I appreciate this library was built to provide a drawer mechanism over a map, so my use case may be somewhat niche, but others may benefit from similar functionality.

Please let me know if there is a better way of achieving the effect i'm after.

Thanks again!

**Comment by brendan09** [comment]
That’s an interesting use case I hadn’t considered. I’ll look at exposing the scroll views gesture recognizer, however I don’t want to expose the scroll view as pulley can’t  handle people interfering with its configuration or view hierarchy.

**Comment by jaybayley** [comment]
Thanks for the Swift reply @brendan09!

Since posting i've noticed that adding a `UIGestureRecognizer` to a view removes it from any previous views the recognizer was added to. This has the unfortunate side effect of preventing Pulley's lovely "pan down to close" functionality when the tableview reaches the top.

I'll keep playing and report back if I can come up with a solution. Any idea's always welcome!

**Comment by jaybayley** [comment]
Thanks to Pulley's excellent delegates, this was trivial to implement:

```
extension PrimaryContentContainerView: PulleyPrimaryContentControllerDelegate {
    
    func drawerPositionDidChange(drawer: PulleyViewController, bottomSafeArea: CGFloat) {
        guard drawer.currentDisplayMode == .bottomDrawer else {
            return
        }
        
        let recognizer = drawer.drawerScrollView.panGestureRecognizer
        if drawer.drawerPosition == .open {
            drawer.drawerScrollView.addGestureRecognizer(recognizer)
        } else {
            view.addGestureRecognizer(recognizer)
        }
    }
}
```

With the above and the public `panGestureRecognizer` i've got the best of both worlds for my specific use case. If you do implement the public access, i'll put together a small demo and submit as a PR.

**Comment by brendan09** [comment]
Nice job! What all did you have to make public in order to accomplish this? I think its definitely a great feature.

**Comment by jaybayley** [comment]
For the time being I made both the `PulleyPassthroughScrollView` class and `PulleyViewController.drawerScrollView` public. If you didn't want to expose these, perhaps something like this on `PulleyViewController` would be better:

```
public var panGestureRecognizer: UIPanGestureRecognizer {
    get {
        return drawerScrollView.panGestureRecognizer
    }
    set {
        drawerScrollView.addGestureRecognizer(newValue)
    }
}
```

Then my extension above could be rewritten as:

```
extension PrimaryContentContainerView: PulleyPrimaryContentControllerDelegate {
    
    func drawerPositionDidChange(drawer: PulleyViewController, bottomSafeArea: CGFloat) {
        guard drawer.currentDisplayMode == .bottomDrawer else {
            return
        }
        
        let recognizer = drawer.panGestureRecognizer
        if drawer.drawerPosition == .open {
            drawer.panGestureRecognizer = recognizer
        } else {
            view.addGestureRecognizer(recognizer)
        }
    }
}
```

**Comment by brendan09** [comment]
I added the ability to get the drawer gesture recognizers and add/remove drawer recognizers to Pulley.

It's in version 2.4.3 (now on CocoaPods) and should resolve this. If you have any issues / questions, let me know.

Thanks!
