### ISSUE TITLE
drawerChangedDistanceFromBottom method not called sometimes when you setDrawerContentViewController

### ISSUE THREAD

**Issue by returnzer0** [52inc/Pulley#208]
First of all. This is a really cool framework that you guys have developed, so thank you very much!

My issue is the following:

I am using 2 drawer view controllers with different restrictions on the `supportedDrawerPositions` and `partialRevealDrawerHeight`.

Drawer A VC:
- `supportedDrawerPositions` -> [All of them]
- `partialRevealDrawerHeight` -> Default

Drawer B VC:
- `supportedDrawerPositions` -> [partiallyRevealed, open]
- `partialRevealDrawerHeight` -> 2/3 of the height of the user's device

When I swap out drawer A with drawer B, my drawerChangedDistanceFromBottom doesn't get called all of the times, it only gets called on certain occasions. 

If drawer A is partially reveled, the method is called perfectly fine, but when drawer A is in the collapsed position, it never calls the delegate method at all. I am not sure why that is.

A workaround that I am currently using is to simply make Drawer A become partially open right before I swap them out, but that doesn't look as good.

**Comment by brendan09** [comment]
Here are 2 things you can try:

1. Call setNeedsSupportedDrawerPositionsUpdate() on Pulley after changing out the drawer.
2. If you need to know the current position for your layouts, make sure you're using the latest version of Pulley and you can use the `drawerDistanceFromBottom` property on PulleyViewController.

If neither one works (or is useful) for you, let me know and I'll see about making that method get called in more circumstances.

**Comment by returnzer0** [comment]
Unfortunately, none of them work, the delegate method doesn't get called.

I tried `setDrawerPosition(position: .partiallyRevealed, animated: false)` and by setting `animated:false`, the change isn't that noticeable and the delegate method does get called.

**Comment by brendan09** [comment]
The second option to get the drawer distance isn’t meant to trigger a delegate callback. You should use that property to do your layout, and only listen to the delegate for changes that don’t trigger a full layout pass.   
  

  
If calling setDrawerPosition works for you, that’s definitely also an option.
  

  
  

  
  
>

**Comment by returnzer0** [comment]
My layouts are done inside the container VC by listening to `drawerChangedDistanceFromBottom` method. How could I go about changing it from the PulleyViewController by using `drawerDistanceFromBottom`? I think it might be a bit too tedious...

**Comment by brendan09** [comment]
You should layout the current UI in -viewDidLayoutSubviews in your view controller. You can query pulley for the values you need. This is for frame based layouts.   
  

  
If you’re using constraints, you should do the same thing but update the constraints in the updateConstraints method of your view controller. You can query pulley for the values you need.
  

  
This should be the case for any layout code in your VC, not just for Pulley. It should be fairly simple to move the mode.   
  

  
The delegate method is there to let you modify your layout in real-time. It’s not there to drive your layout or work as something to cause the layout of your view to happen initially.   
  

  
  

  
  
>

**Comment by returnzer0** [comment]
Ok, I'm sorry, I mistyped. I don't do my actual layouts for all of my views inside this method. I simply update my layout and move some items in the container view based on the method. 

I am following the given example of how the temperature label stays on top of the drawer in certain positions and I am extending off from that. And just like in the example given, the views only follow the drawer in certain distances.

**Comment by brendan09** [comment]
The example project doesn’t really follow best practice for that. You can see some side effects of it as a result. It needs to be updated to use the new distance property so that it eliminates that problem.
  

  
All of the things you modify in that delegate callback should also be considered / modified in the appropriate layout methods based on Pulley’s current distance value, which you can access via the property mentioned before.   
  

  
You can get the current distance info from Pulley by accessing the property anytime, rather than waiting on it to be delivered to you. You can use that to make layout decisions in the layout methods.   
  

  
  

  
The delegate method is only called for drawer changes. It’s not called any time that value may change (such as changing view controllers, window / view resizing, etc). These things trigger a layout pass, which is where you should add logic to get the current value and make UI decisions / alterations.   
  
  
>

**Comment by returnzer0** [comment]
Thank you so much, your explanation is very informative!
