### ISSUE TITLE
Manual Installation - Use of unresolved identifier 'parent'

### ISSUE THREAD

**Issue by iRick92** [52inc/Pulley#209]
Hi. I was having trouble with manually installing this library. I have dragged the files from the PulleyLib folder to my project but I'm getting ht following errors: 

<img width="1113" alt="screen shot 2018-06-09 at 2 16 19 am" src="https://user-images.githubusercontent.com/13518088/41169091-31e171fe-6b8b-11e8-9061-a0540a4b4cd9.png">

**Comment by brendan09** [comment]
You need to import UIKit, it looks like. Add an import statement for UIKit to the top of the files. I’ll leave this issue open and make a commit that fixes the need for that sometime next week.

Note: The recommended way to install Pulley is Cocoapod.
