### ISSUE TITLE
change drawer background color to clear

### ISSUE THREAD

**Issue by aelbarji** [52inc/Pulley#210]
Hi, i i set  pulleyViewController programmatically without storyboards; And i can't change the drawer content background color to clear? can you please tell me how to do it? or how to remove extra sides?
![img_0364](https://user-images.githubusercontent.com/10722948/41235662-80a8ed8e-6d8f-11e8-9740-21178197c55a.PNG)

**Comment by brendan09** [comment]
Here are the recommended PulleyViewController settings for what you're doing:

* drawerCornerRadius = 0.0
* shadowOpacity = 0.0
* drawerBackgroundVisualEffectView = nil

**Comment by aelbarji** [comment]
Hey @brendan09! Thank you for your fast response! it's works for me :)
