### ISSUE TITLE
Have 2 drawers 

### ISSUE THREAD

**Issue by lahavamir27** [52inc/Pulley#211]
Is it possible to have more then one drawer?

**Comment by aelbarji** [comment]
Hi, if you mean change drawer as you like.. 
yes it's possible with this `pulleyViewController?.setDrawerContentViewController(controller: viewController, animated: true)`

**Comment by brendan09** [comment]
@lahavamir27 Did @aelbarji answer your question? If so, let me know and I'll close the issue. Thanks!
