### ISSUE TITLE
API Question

### ISSUE THREAD

**Issue by lightsprint09** [52inc/Pulley#212]
Hey. Just getting started with Pulley.

I am a bit confused. What is the difference between `pulleyController.initialDrawerPosition` and `pulleyController.drawerPosition`

It feels like a redundant API, which introduces confusion.

First I tried to set `pulleyController.drawerPosition` noticing that it is get only. After that I used `setDrawerPosition` which did not work as well. 

After looking into the source code I found `initialDrawerPosition`. It felt like this makes the API harder to understand.

**Comment by brendan09** [comment]
`pulleyController.initialDrawerPosition` can be set before the views are loaded and doesn't trigger loading the view or child view controllers.

You can set the drawerPosition using the `setDrawerPosition` method. You can't directly set the property.

**Comment by lightsprint09** [comment]
This is confusing. Why I am not able to use `setDrawerPosition ` instead of `pulleyController.initialDrawerPosition`

**Comment by brendan09** [comment]
You can. `initialDrawerPosition` exists for a completely different reason. It may not apply to your use case.

You can access PulleyViewController and set the position any time after "viewWillAppear" in your drawer/main view controllers.
