### ISSUE TITLE
PulleyPassthroughScrollViewDelegate not receiving touches?

### ISSUE THREAD

**Issue by joeuelk** [52inc/Pulley#213]
I was trying to debug why the .nearestPositionUnlessExceeded behavior wasn't what I expected and discovered that scrollViewDidEndDragging in PulleyViewController: UIScrollViewDelegate isn't being called.

Touches aren't being received in PulleyPassthroughScrollView either.

I have a "rootViewController" that sits on top of everything and pulley is loaded like this:

```
let storyboard = UIStoryboard(name: "Main", bundle: Bundle.main)
        let pulleyVC = storyboard.instantiateViewController(withIdentifier: "PulleyViewController")
        addChildViewController(pulleyVC)
        self.view.addSubview(pulleyVC.view)
        if let appDelegate: AppDelegate = UIApplication.shared.delegate as? AppDelegate {
            appDelegate.rootVC = self
        }
```

I can swipe the drawer up and down without issue and everything seems like it is working except for the "nearestPositionUnlessExceeded" behavior.

Any idea what could be causing this? How can I drag the drawer up and down if the PulleyPassthroughScrollView receives no touches?

Thanks

**Comment by brendan09** [comment]
Are you using a subclass of PulleyViewController or PulleyViewController directly? If you're using a subclass, it's possible something isn't calling 'super' implementation when needed.
