### ISSUE TITLE
Keyboard handling suggestion

### ISSUE THREAD

**Issue by sadanro100** [52inc/Pulley#217]
Does anyone have a suggestion on how to deal with textfields in the drawer view controller?

I tried calculating the desired distance to come with the correct height for the drawer, then I set it to a variable which I  return in partialRevealDrawerHeight.

It did work to make the drawer come up or down to follow the keyboard, but since I'm just returning it in partialRevealDrawerHeight, there's no animation in the hight change.

Has anyone used a textfield in the drawer?

**Comment by alexandrubeck** [comment]
Hi @sadanro100, did you find a solution for it?

**Comment by sadanro100** [comment]
@objc func keyboardWillShow(notification: Notification) {
        
        self.setTopInsetForKeyboard(notification: notification)
        self.pulleyViewController?.setDrawerPosition(position: .open, animated: true)
    }


     func setTopInsetForKeyboard(notification: Notification) {
        
        guard let primaryVc = self.getPrimaryVc() else { return }
        
        var topInset = primaryVc.view.frame.size.height
        if #available(iOS 11.0, *) { topInset -= primaryVc.view.safeAreaInsets.top }
        if let keybordHeight = self.getKeyboardHeight(notification: notification) { topInset -= keybordHeight }
        if let firstResponderBottomY = self.getFirstResponderBottomY() { topInset -= firstResponderBottomY }
        
        if self.isLastFieldFirstResponder(), let firstResponder = self.getFirstResponder() {
            
            topInset -= firstResponder.keyboardDistanceFromTextField
        }
        else { topInset -= IQKeyboardManager.shared.keyboardDistanceFromTextField }
        
        guard let minimumTopInset = self.getMinimumTopInset() else { return }
        
        if topInset > minimumTopInset { self.pulleyViewController?.topInset = topInset }
        else { self.pulleyViewController?.topInset = minimumTopInset }
    }

**Comment by alexandrubeck** [comment]
Hi @sadanro100, thank you for your solution.
But seems my Pulley version isn't compatible with your, because I'm getting some errors:

![image](https://user-images.githubusercontent.com/53875891/72134347-7df70480-338c-11ea-9254-721cf9380614.png)

Can you please send me extensions for those errors which are highlighted here?

**Comment by sadanro100** [comment]
I could share my entire project with you and perhaps it still wouldn't solve your problem.

I only pasted my code to illustrate how I managed to get around this issue.

Long story short, you have to calculate how far you want the drawer view controller to be from the top, set the topInset, then call serDrawerPosition to animate the change.

Good luck
