### ISSUE TITLE
scrollView moveTo

### ISSUE THREAD

**Issue by VolkovaKatie** [52inc/Pulley#218]
Hello guys!
Is there any way to change drawerScrollView maximum stopToMoveTo point?

**Comment by brendan09** [comment]
The positions considered for that are determined by your delegate implementation. Their locations are as wel.

If you’d like to adjust the top “open” position, you can adjust the topInset property on PulleyViewController. That is the distance from the top that it stops at.

**Comment by VolkovaKatie** [comment]
Yes, thank you. Just asked you and found it next minute!
Thanks!
