### ISSUE TITLE
Drawer bounce animation

### ISSUE THREAD

**Issue by Mazorati** [52inc/Pulley#219]
Hello!
How to disable bounce animation?

**Comment by brendan09** [comment]
The bounce animation only occurs if you explicitly call the bounce function. 

If you’re working from the example project, remove the call to the bounce function from the drawer view controller. It’s in viewDidAppear (on a timer), I believe.

**Comment by Mazorati** [comment]
@brendan09  No i don't have such timer in my drawer.
I my drawer closed state i use button and call:
`drawer.setDrawerPosition(position: PulleyPosition.open, animated: true)`
This forses drawer to be opened with little bounce ~20 pt. I don't want this bounce.

**Comment by brendan09** [comment]
Ah, I understand now. 

You can eliminate that by adjusting the animation options on PulleyViewController. Try a spring damping value of 1.0.

Note: You’ll still need to handle the fact that 20pt of your drawer content is off-screen when presented, as it does still require you to account for the possibility of the animation. If you don’t need it, you could constrain things to the bottom of your drawer VC with a constant value of 20.

**Comment by Mazorati** [comment]
@brendan09 thanks! Now its ok!
How could i reduce velocity of appear animation?

**Comment by brendan09** [comment]
There are a wide variety of animation settings you can modify on PulleyViewController. Try adjusting the duration to make it slower.

**Comment by Mazorati** [comment]
oh thanks! i confused with animationDelay and wonder why its not working 👍

**Comment by brendan09** [comment]
Delay will postpone the start, but leave everything else the same. Most people probably won’t need it, but it’s there if anyone does.
