### ISSUE TITLE
Set height of DrawerView

### ISSUE THREAD

**Issue by marcjulianfleck** [52inc/Pulley#220]
Hey guys!
Is it somehow possible to set the height of the drawer to the height of the drawer position. 
E.g. to see the whole view controller in the drawer while the the position of the drawer is set to "partiallyRevealed"?

Thanks in advance!

**Comment by brendan09** [comment]
You’ll have to manage that yourself using constraints in your view controller. You can use the drawer delegate callbacks to be notified of position / distance changes and you can adjust your constraints accordingly.

**Comment by marcjulianfleck** [comment]
Sometimes it is so simple. 
Thanks!
