### ISSUE TITLE
Pulley from top

### ISSUE THREAD

**Issue by nmrapoport** [52inc/Pulley#221]
Hey!

I just started using pulley and I've been trying to adapt it to be essentially upside-down, a pull down view. This would function sort of like the old iPhone notification center, with a visible tab slide down; it would literally be the "top" version of this pulley. 

I tried switching all the "top" words with "bottom," and vice versa (but not simply the variable names), but that didn't work.

Any idea how to go about doing that?

**Comment by brendan09** [comment]
You should be able to do this without altering Pulley. I recommend not trying to alter it, as you’ll most likely break some of the math on how the drawer works.

Instead, I’m viewWillAppear: of your drawer or primary content controller you can apply a transform to the PulleyViewController view.

So, it’d look something like this:

self.pulleyViewController?.view.transform = CATransform3DMakeScale(1.0, -1.0)

You’ll need to then flip your drawer and primary view controllers back, as they’ll be upside down too...to do that, apply the same transform to their view controller’s view as well. It’ll flip them back to normal.

**Comment by nmrapoport** [comment]
Got it! Thanks fo much!

**Comment by ipoogleduck** [comment]
Hi, I tried doing this and it came back with an error: 
"Missing argument for parameter #3 in call
Insert ', <#CGFloat#>"

Then if I click fix it says:
"Cannot assign value of type 'CATransform3D' to type 'CGAffineTransform'"

**Comment by brendan09** [comment]
That’s vecyase you’re trying to use a CATransform3D to a variable that is of type CGAffineTransform. These 2 transforms are not interchangeable. 

I recommend checking out the UIKit and CoreGraphics documentation on transforms and UIViews, as that will be more helpful because this issue isn’t related to Pulley.
