### ISSUE TITLE
Compile Error on version 2.4.2

### ISSUE THREAD

**Issue by cookeri6** [52inc/Pulley#223]
Seems to be a compile error on version 2.4.2 lines 1544 and 1546 complaining about these two methods not being accessible because they are private:
`backgroundDimmingView.frame = backgroundDimmingViewFrameForDrawerPosition(scrollView.contentOffset.y + lowestStop)
syncDrawerContentViewSizeToMatchScrollPositionForSideDisplayMode()`

**Comment by brendan09** [comment]
That sounds like you’re using Swift 3 (which will have that issue). Make sure you’re building it with Swift 4. 

As an example, try downloading the sample project and running it with Xcode 9.4.1.

**Comment by cookeri6** [comment]
Ahhh, indeed, this fixed the issue. Thanks again!
