### ISSUE TITLE
Demo UI initial state does not show the "degrees" placeholder label?

### ISSUE THREAD

**Issue by jtayler** [52inc/Pulley#230]
Does anyone know why the initial state of the UI does not show the "Degrees" placeholder label? If you pull up and down, it appears, and I was wanting to use it for important UI details and after a bit of looking, I did not see exactly how that all works, but I liked the effect of hiding and showing based on sizing.

**Comment by brendan09** [comment]
It’s a bug due to how the sample project waits on a delegate callback before configuring the constraint correctly. You can avoid the sample projects issue by getting the bottom drawer height from the property on PulleyViewController.

**Comment by jtayler** [comment]
hi, thanks so much! I could set the frame in viewDidAppear, but it wouldn't bounce with the slide - it seems like there is a constraint but I don't see where that gets wired up or how that all works?

**Comment by brendan09** [comment]
The bounce animation in the sample project is done with Core Animation and won’t cause the delegate methods to be called, so the temperature label won’t track with the bounce animation from the .bounce call.
