### ISSUE TITLE
Latest update miscalculates the `open` height on iPad

### ISSUE THREAD

**Issue by hyerra** [52inc/Pulley#235]
I've noticed that the latest release of Pulley is apparently miscalculating the height of how big the iPad's `open` height should be. I've even tested it on the Demo project and the height is too big. I've attached a screenshot.
![simulator screen shot - ipad pro 12 9-inch 2nd generation - 2018-07-29 at 12 08 31](https://user-images.githubusercontent.com/16071306/43368782-4edbd172-9328-11e8-8e49-581adaf629d7.png)

**Comment by hyerra** [comment]
Awesome! Thanks so much for an awesome tool :).. if I have time tonight I'll look into making a pull request to!

**Comment by brendan09** [comment]
The latest version of Pulley has this addressed. 2.4.4. You may need to run `pod repo update` before `pod update Pulley` in order to get it.
