### ISSUE TITLE
Presenting a Modal VC with Dynamic Type leads to VC not taking up full height

### ISSUE THREAD

**Issue by hyerra** [52inc/Pulley#239]
Hey there!

For some reason, when I use Pulley to present a view controller set to the max font of dynamic type the view doesn't start at the top as shown in these two pictures. The one on the top is the presenting view controller (with correct height) and the middle is the presented view controller (with an incorrect height). For some reason, however, when set to the default font, this issue goes away as shown in the third picture.

![simulator screen shot - iphone x - 2018-08-01 at 19 56 59](https://user-images.githubusercontent.com/16071306/43556487-8db4c864-95c5-11e8-94ad-acfd52c781bf.png)
![simulator screen shot - iphone x - 2018-08-01 at 19 57 07](https://user-images.githubusercontent.com/16071306/43556488-8de7eb4a-95c5-11e8-92d0-b8341632ab83.png)
![simulator screen shot - iphone x - 2018-08-01 at 19 59 02](https://user-images.githubusercontent.com/16071306/43556490-8e73fc70-95c5-11e8-8fff-af48f40fa392.png)

**Comment by brendan09** [comment]
Presenting a modal view controller on Pulley is not an officially supported behavior and as a result, there's not much I can do to help.

It doesn't occur in the sample project with a standard drawer setup. I would recommend not using a modal presentation, or checking your layout constraints and how they're affected when the font is large.

**Comment by hyerra** [comment]
Also upon further analysis the `PulleyPassthroughScrollView` is the correct height on the problem view controller (confirmed using the view debugger). However, the content views (as shown in the picture with the arrows pointing at them) seem to be drawn at starting at a y below the top of the drawer scroll view.
<img width="300" alt="screen shot 2018-08-01 at 8 08 44 pm" src="https://user-images.githubusercontent.com/16071306/43556744-f65fd826-95c6-11e8-9701-c90f15878ac6.png">

**Comment by hyerra** [comment]
Ohh I see @brendan09, I'll take a look at it and see if I can come up with a fix.

**Comment by brendan09** [comment]
Pulley won't manage the height / Y coordinate of your modally presented VC, so I'm not surprised it doesn't layout correctly. I'd recommend avoiding modal presentations if you can't find a workaround.

**Comment by hyerra** [comment]
Hmm do you support like having a navigation controller and then pushing view controllers on top of that?

**Comment by brendan09** [comment]
I've seen people do that, and it seems to have some success. I generally recommend using the API on Pulley to set a new drawer view controller, as it's the easiest. However, navigation controllers seem to work okay as long as you aren't try to use the 'large title style' in iOS 11+. It's also not officially supported, but people seem to be having good luck with it.

**Comment by hyerra** [comment]
Ahh I figured it out! The issue turned out to be simple.. what I was doing right was dynamically calculating heights and stuff because obviously it can vary. However, the view hadn't been laid out yet so it wasn't returning the correct height for the collapsed view. As a result, the solution was to call `view.layoutIfNeeded()` if the height varies that way the view has the chance to calculate the height of the collapsed view and return the appropriate height.

**Comment by brendan09** [comment]
Ah! That makes sense. Good catch!
