### ISSUE TITLE
Does it possible to make list table view bg color white ?

### ISSUE THREAD

**Issue by kristoff2016** [52inc/Pulley#24]

**Comment by brendan09** [comment]
Yes. You can make the tableview background color white.

**Comment by kristoff2016** [comment]
Hey @brendan09 thank you for reply! 
I have the last question. I tried to change UISearch Bar height but it deosn't work currently. 
Could you help me and send me the link downlaod your code. I wanted it like image link below: 
https://drive.google.com/file/d/0B3E-jC5U2bcwajI4WWF5dXljSms/view?usp=sharing

I think there are someone would like this also. 

thank you so much for your help 
Awesome Developer

**Comment by brendan09** [comment]
The height of UISearchBar can't be changed without diving into the private view hierarchy of the control. Customizing UISearchBar is outside the scope of the help I can offer you here, as it isn't related to the PulleyViewController.
