### ISSUE TITLE
Extra tags?

### ISSUE THREAD

**Issue by Nonnus** [52inc/Pulley#241]
When updating using carthage and not specifying any version,
i got version 2.4.4 wich caused some errors on my project,
when checking the project releases it seems that lastest release is 2.3.2,
wich built fine and caused no errors

is this expected?

**Comment by brendan09** [comment]
The latest release is 2.4.4.

**Comment by brendan09** [comment]
I'd been creating the tags for Cocoapods via git locally and pushing them, which apparently doesn't enter them as a release. I've went ahead and added a release for 2.4.4.

**Comment by Nonnus** [comment]
awesome, thanks a lot for your super quick response!
