### ISSUE TITLE
Setting properties in prepareForSegue

### ISSUE THREAD

**Issue by mickmgit** [52inc/Pulley#244]
I have a PulleyVC that is pushed onto a navigation stack. Working just fine.  However, when the segue is executed, I want to pass some properties from the current VC to the VC that is the primaryContentViewController.  In the prepare(for segue: NSStoryboardSegue, sender: Any?) method, the segue.destiniation is the PulleyVC, but at this point the primaryContentViewController (as well as the drawerContentViewController) are still nil.

Is there a way to pass properties from a segue?

**Comment by brendan09** [comment]
Yes, call “loadViewIfNeeded()” on the PulleyViewController instance before attempting to work with those properties. At the point prepareForSegue is called, the view hasn’t been loaded from Interface Builder. That line forces it to load.

**Comment by brendan09** [comment]
You'll need to set the right bar button item property on PulleyViewController. Your bar button item can be created with your primary content VC as the target, with one of it's functions as the action/selector.

**Comment by mickmgit** [comment]
Thanks,  got that.  Kept thinking of the primaryContentContainerView, forgot we also have the primaryContentViewController.

**Comment by milosnk** [comment]
Hello there, can you please explain me how to connect bar button action with primary content VC?
