### ISSUE TITLE
iOS 12 Xcode 10 support

### ISSUE THREAD

**Issue by appsird** [52inc/Pulley#246]
Would appreciate an update for iOS12

Thanks.

**Comment by brendan09** [comment]
Please see the swift-4.2 branch for Xcode 10.

**Comment by appsird** [comment]
Try to integrate using Podfile with:

  pod 'Pulley', :git => 'https://github.com/52inc/Pulley.git', :branch =>
'Swift-4.2'

Though, receive an error:

Analyzing dependencies

Pre-downloading: `Pulley` from `https://github.com/52inc/Pulley.git`,
branch `Swift-4.2`


[!] Error installing Pulley

[!] Failed to download 'Pulley'.

**Comment by appsird** [comment]
Disregard, works using:

  pod 'Pulley', :git => 'https://github.com/52inc/Pulley.git', :branch =>
'swift-4.2'

Thanks.

On Thu, Aug 16, 2018 at 10:45 PM, Brian Balthazor <brian.balthazor@gmail.com
