### ISSUE TITLE
Customize height of drawer when open

### ISSUE THREAD

**Issue by Farbod909** [52inc/Pulley#248]
Is it possible to customize the height of the drawer when it's open? If not, is there any work around for having 3 different possible heights for the drawer?

**Comment by brendan09** [comment]
You can adjust the height of the open drawer using the topInset property.

**Comment by Farbod909** [comment]
It's not possible to adjust the height using a fixed height from the bottom?

**Comment by brendan09** [comment]
No, but you can calculate a value for it and update it in viewDidLayoutSubviews of your drawer view controller.

**Comment by grifas** [comment]
I tried to do as you said, calculate and set topInset in `viewDidLayoutSubviews` of the drawer but there is a weird behaviour (iPhone 6s):

The PulleyViewController is a pushed view controller, when I want to go back to parent with the slide gesture and, on the way, cancelled the gesture to stay on the PulleyViewController, the drawer updates the `collapsedDrawerHeight` and `partialRevealDrawerHeight` with a bottomSafeArea equal to 49 and does shit with the drawer. I don't know where 49 comes :/

**Comment by brendan09** [comment]
49 is the height of a UITabbar. If the screen you’re going back to has a tab bar that’s translucent (with VC edges extending underneath it) then the safe area will update when it becomes (Or is about to become) visible.

**Comment by grifas** [comment]
Yes it's exactly that ! Have you an idea how to disable this ?

**Comment by brendan09** [comment]
Make your tab bar opaque and make sure view controllers aren’t set to appear underneath opaque bars. However, that may it give you the effect you want and may introduce other issues. 

Ultimately you may just have to use something like the window safe area rather than the view controllers...that way it doesn’t account for the tab bar.

**Comment by grifas** [comment]
Thanks a lot !
