### ISSUE TITLE
Keep drawer on bottom when `displayMode = .automatic`

### ISSUE THREAD

**Issue by bsudekum** [52inc/Pulley#249]
If `displayMode` is equal to `.automatic` or `.leftSide`, it'd be helpful to be able to keep the drawer on the bottom of screen instead of it being pinned to the top left. 

In our case, we'd like to customize the drawer to remain in the lower left while in landscape mode. As far as I can tell, the drawer is pinned to the top of the screen by this line:

https://github.com/52inc/Pulley/blob/257915a1d2992a0df523677e33226e748093840a/PulleyLib/PulleyViewController.swift#L872

**Comment by brendan09** [comment]
This project aims to imitate Apple Maps, which is how these settings currently behave. This behavior won’t be changed, however you’re welcome to fork it and modify it for your own use.

**Comment by bsudekum** [comment]
@brendan09 what do you think about adding a `selectedCorner` property that allows the developer to specify a `corner` enum?

**Comment by brendan09** [comment]
It’s something I’m happy to consider a PR for, however since it’s outside the feature set of Apple Maps it’s not something I’d prioritize developing myself.
