### ISSUE TITLE
Does it possible to create multiple DrawerContentViewController ? 

### ISSUE THREAD

**Issue by kristoff2016** [52inc/Pulley#25]
I would like to do like Apple App Maps that When I click on Icon Details on the top it show new DrawerContentViewController overlay DrawerContentViewController default.

**Comment by brendan09** [comment]
Yes. Please look at the example project. It includes examples of how to change the DrawerContentController, with an optional animation.

**Comment by kristoff2016** [comment]
Hello @brendan09  thank you for your reply and value time. My question is I wanted when I click Icon (Apple Name Icon: Info Light) in your project it can change to do like DrawerContentViewController. it will work like DrawerContentViewController from bottom to top. it is difficult handle if I followed your example because if I used navigationController it does not work on navigationBar Button. it would be great if we have function work the same DrawerContentViewController. thank you so much

**Comment by brendan09** [comment]
Usage with a UINavigationController is an unsupported use case. However, people I've spoken it to have managed to get it to work without issue. You'll probably need to subclass the pulley drawer to do what you're looking for, which is another unsupported scenario.

**Comment by kristoff2016** [comment]
Please have look my image here: https://drive.google.com/file/d/0B3E-jC5U2bcwZER5d3VUc2JzcDg/view?usp=sharing
thanks for your answer !

**Comment by brendan09** [comment]
I don't see anything here that can't be accomplished with PulleyViewController as-is. I'm not understanding what you're asking.

**Comment by kristoff2016** [comment]
The link above is what I wanted to do. in your project you have primary DrawerContentViewController but the link above is New DrawerContentViewController if I click on somewhere button it will overlay primary DrawerContentViewController default.  thank you so much @brendan09

**Comment by brendan09** [comment]
Please take a look at the README file, as it has code samples showing example how to do what you're asking. It covers most usage scenarios.

You can use the _setDrawerContentViewController_ API to change the drawer contents.

**Comment by kristoff2016** [comment]
yes, Thank you so much! if I have done I will let's you know
