### ISSUE TITLE
Pinning to the visible bottom of the pullover

### ISSUE THREAD

**Issue by bendodson** [52inc/Pulley#253]
I'm trying to pin a UIPageControl to the bottom of the visible area of the pullover sheet but having some difficulty. If I pin to the bottom constraint, then this is only visible when the sheet is fully displayed as it looks like the sheet is always rendered at it's .open height offscreen (+20pt). What I ideally need is a way to pin an element to the bottom of the visible area of the sheet so it would display at the bottom both in partiallyRevealed and open states without moving yet would disappear with the content when animating to the .closed state. Is this possible?

**Comment by brendan09** [comment]
You would want to embed Pulley in a container view in another UIViewController. You can put elements on top of that container view that will remain stationary.
