### ISSUE TITLE
allowUserDrawerPosition not working?

### ISSUE THREAD

**Issue by xx3987** [52inc/Pulley#255]
Hey!
I've trying to initiate allowUserDrawerPosition because I want the pulley to behave differently to the user on different viewcontrollers, but this setting seems to be global? 
The only way to control it is from PulleyViewController.swift itself

Am I missing something or is it supposed to be like that?

**Comment by xx3987** [comment]
solved by adding this to the CollapsibleTableViewHeaderDelegate

    func drawerDisplayModeDidChange(drawer: PulleyViewController) {
        if drawer.allowsUserDrawerPositionChange == true {
            drawer.allowsUserDrawerPositionChange = false
        } else {
            print("somethinghappened")
        }
        
    }

**Comment by brendan09** [comment]
Glad you found a solution!
