### ISSUE TITLE
Pulley.h not in the project

### ISSUE THREAD

**Issue by arashk72** [52inc/Pulley#258]
Hi, 
I have used your library in two different projects since two years ago, and this is the third one.
Actually previously I could smoothly install and use it, but now, I am stuck with an issue. 
When I try to install the lib via pod, it doesn't create all files. It creates only "PulleyPassthroughScrollView.swift" and "PulleyViewController.swift".
And when I manually copy the file into the project, I am not able to add Pulley.h to my target (as it's a header file), so I am getting:
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIViewController 0x143d485f0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key drawerContentContainerView.

**Comment by brendan09** [comment]
Make sure you’re running the latest version of CocoaPods, and then run “pod repo update”, and then run “pod update Pulley”. Make sure you haven’t locked the version of Pulley in your Podfile.

**Comment by arashk72** [comment]
Still same, Please refer to screen shot (it's after installing the pods)
<img width="269" alt="screen shot 2018-09-03 at 2 08 05 pm" src="https://user-images.githubusercontent.com/7631785/44970157-dccf9100-af82-11e8-859d-fe741b453f2d.png">

**Comment by brendan09** [comment]
Try removing Pulley from your Podfile, running pod install, then re-adding Pulley and pod install again.

Unfortunately, this is an issue with your specific setup / local cocoapods config/installation. The podspec is setup to use all Swift files in the PulleyLib folder, so if they’re not there or not including in then project then it’s an issue somewhere in your local setup. There’s limited troubleshooting I can do from here, aside from mention that I’ve had similar issues with other pods that required me to try miscellaneous things (like remove and re-add) until cocoapods would set it up correctly. Sorry I don’t have a better answer.

**Comment by arashk72** [comment]
It's very strange. 
Can you please take a look at following screen shots? I have tried to do exactly what is done in sample project. 


<img width="816" alt="screen shot 2018-09-03 at 2 35 40 pm" src="https://user-images.githubusercontent.com/7631785/44971106-e4913480-af86-11e8-9c63-01158d1248b2.png">
<img width="478" alt="screen shot 2018-09-03 at 2 35 51 pm" src="https://user-images.githubusercontent.com/7631785/44971108-e529cb00-af86-11e8-9235-3c9fed53bc93.png">
<img width="519" alt="screen shot 2018-09-03 at 2 36 02 pm" src="https://user-images.githubusercontent.com/7631785/44971110-e529cb00-af86-11e8-828b-f4ab75777c6d.png">
<img width="750" alt="screen shot 2018-09-03 at 2 36 10 pm" src="https://user-images.githubusercontent.com/7631785/44971112-e529cb00-af86-11e8-9ea7-ec0c92c7a24e.png">
<img width="723" alt="screen shot 2018-09-03 at 2 36 16 pm" src="https://user-images.githubusercontent.com/7631785/44971114-e529cb00-af86-11e8-9e4e-5e701e91a1ca.png">
<img width="240" alt="screen shot 2018-09-03 at 2 36 28 pm" src="https://user-images.githubusercontent.com/7631785/44971115-e5c26180-af86-11e8-85b4-2e46e079cce1.png">

The error I am getting is:
Unknown class _TtC6Pulley20PulleyViewController in Interface Builder file.
Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIViewController 0x7f9670e096e0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key drawerContentContainerView.'

**Comment by arashk72** [comment]
It turned out that I am so silly. 
I had the module wrongly.
