### ISSUE TITLE
Strange behavior when tapping the status bar

### ISSUE THREAD

**Issue by carlo-** [52inc/Pulley#26]
First of all thank you for sharing this amazing library!

I've noticed a strange behavior that is probably unwanted in most cases; if you tap the status bar while the drawer is open, the scroll view scrolls to the top, effectively closing the drawer without getting rid of the dimming view, meaning that you have to tap once more to interact with the content view.

This can be solved by setting `drawerScrollView.scrollsToTop = false`

**Comment by brendan09** [comment]
Nice catch. I'll fix that in the next release.

**Comment by brendan09** [comment]
Fixed in upcoming release.
