### ISSUE TITLE
how to embed a navigation controller into drawer and still get delegate callbacks

### ISSUE THREAD

**Issue by MadeByDouglas** [52inc/Pulley#266]
my drawer content VC is inside a nav controller. it works but I don't get the delegate callbacks. I tried setting them manually (see below), but it doesn't seem to work. Advice?

```
let navigation = UINavigationController(rootViewController: drawerContentVC!)
let pulleyController = PulleyViewController(contentViewController: mainContentVC!, drawerViewController: navigation)
pulleyController.delegate = drawerContentVC
```

**Comment by brendan09** [comment]
Call setNeedsSupportedDrawerPositionsUpdate() when the screen changes so pulley refreshes the drawer position configs.

**Comment by MadeByDouglas** [comment]
Ohh, like if I rotate device or if I wanted an event like tapping a button or a delegate firing to change the drawer position?

**Comment by MadeByDouglas** [comment]
oh ok got it. thanks for your help.
