### ISSUE TITLE
present and dismiss modal from within pulley

### ISSUE THREAD

**Issue by MadeByDouglas** [52inc/Pulley#268]
So in the demo you show how you can overload main content VC with something else to have a model and keep the drawer menu. However, I want a modal that covers everything, including the drawer, and then just dismisses like normal.

How do I do this? Currently, when presenting a VC modally, then dismissing it, it seems I dismiss pulley and the drawer VC gets dropped.

**Comment by brendan09** [comment]
Set your presentation to be overFullScreen. If you don’t, it’ll be current context and overlay the drawer VC. In the sample project you can see either the segue configuration or modal presentation setup in code. I don’t recall how the sample project is written.

**Comment by MadeByDouglas** [comment]
What do you mean set presentation overFullScreen? Is that a property on pulley, or in UIKit? I’m not familiar sorry.

**Comment by brendan09** [comment]
It’s a property on your view controller (Or segue, if you’re using segues in interface builder).

**Comment by MadeByDouglas** [comment]
Ah! I see its the modalPresentationStyle. Ok thanks!

**Comment by jtayler** [comment]
MadeByDouglas? I think you can present from the root VC rather than the drawer to get the effect you describe -- a modal can present from different roots, like a tab panel or something lower.
