### ISSUE TITLE
Cannot find protocol declaration for 'PulleyDrawerViewControllerDelegate'

### ISSUE THREAD

**Issue by thomas-oo** [52inc/Pulley#27]
I'm a bit new to iOS dev, I'm writing my program in objective c and I used pods to install Pulley using the use_frameworks! flag. I can find PulleyDelegate but I cannot find PulleyDrawerViewControllerDelegate. I'm trying to follow your instructions to change the drawer dimensions dynamically. I imported the framework using #import "Pulley-Swift.h"

**Comment by brendan09** [comment]
Unfortunately PulleyDrawerViewControllerDelegate uses features not available in Objective-C (array of enums). As a result, it isn't available in Objective-C. Without that support, it's unlikely that you'll be able to use Pulley in Objective-C in a meaningful way.

**Comment by thomas-oo** [comment]
aww :( anyways thanks for the quick answer, looks like a sweet library

**Comment by brendan09** [comment]
Although not ideal, you could always write the components touching it in Swift (or write a wrapper around it).
