### ISSUE TITLE
code signing failed when uploading to App Store 

### ISSUE THREAD

**Issue by MadeByDouglas** [52inc/Pulley#271]
I installed Pulley via Carthage

in the logs it says

```
Didn't find archived user entitlements
Error Domain=NSCocoaErrorDomain Code=4
"Frameworks/Pulley.framework" did not contain a "archived-expanded-entitlements.xcent" resource"
```

I have Pulley embedded, should it just be linked? (I believe it doesn't work if its just linked, since its a swift framework and needs to be compiled along with the app, right?)
Is Pulley.framework static or dynamic?

**Comment by brendan09** [comment]
That’s something specific to your Carthage setup, unfortunately. Although Pulley can generate a dynamic framework for Carthage, it’s not a recommended manner of including Pulley as Carthage specific issues tend to pop up frequently (that also happen with other open source projects) and the help material / community is lacking. 

I’m not aware of anyone using Pulley via Carthage in a shipping project, so I’m unable to help and it’s unlikely anything but a Carthage focused community would know how to fix. Sorry about that!

**Comment by MadeByDouglas** [comment]
so if I use cocoa pods or manually add it will work?

**Comment by MadeByDouglas** [comment]
im on a quick schedule I don't have time to figure out the details unfortunately

**Comment by brendan09** [comment]
Cocoa pods or manually is what we recommend.

**Comment by MadeByDouglas** [comment]
hmm ok
