### ISSUE TITLE
Animate the drawer view from partially open to full size on the tap of the search bar on the drawer

### ISSUE THREAD

**Issue by pratyush0211** [52inc/Pulley#275]
Hi,

I have a drawer with a search bar. When the user taps on the search bar, the drawer should animate from partially open to full size state. 

Is there any way we can implement this and get a call back to extend the drawer to full size on any given action (here searchbar tap)? 

Thanks.

**Comment by brendan09** [comment]
Checkout the sample project, it does this.

**Comment by pratyush0211** [comment]
Thanks, I will try this.
