### ISSUE TITLE
Present Modal Like Maps, Stocks etc.

### ISSUE THREAD

**Issue by jtayler** [52inc/Pulley#276]
Pulley works well for my use, but I wonder if there is a bit of further UI in modal presentation? Stocks and Maps have modal views that seem to have this navigation bars and use an "X" close button in the upper right -- 

Is there suggestion or example of this type of modal operation within the pulley? Seems that nearly every fully complete UI would have a need to push further view controllers onto that stack?

Thanks for suggestions or comment -

**Comment by brendan09** [comment]
Most people are doing this, and it seems to work fine for them:

     drawerContentViewController.definesPresentationContext = true

Configure modal presentation styles

     modalViewController.modalTransitionStyle = .coverVertical
     modalViewController.modalPresentationStyle = .currentContext

Present view controller modally

     drawerContentViewController.present(modalViewController, animated: true, completion: nil)

**Comment by jtayler** [comment]
For reference, use Maps app to search a location, then tap on the location and a modal style presentation brings up an inspector. 

This modal inspector has an X marker on the rightbarbuttonitem, and a somewhat thin navigation bar size - it seems - plus a pulley gripper view that seems to disappear when you scroll up and the Navbars title adjusts.
