### ISSUE TITLE
how to show content outside of drawer bound

### ISSUE THREAD

**Issue by kaungsoe** [52inc/Pulley#277]
<img width="236" alt="screenshot 2018-10-15 at 4 00 36 pm" src="https://user-images.githubusercontent.com/10142384/46937299-82eadc80-d093-11e8-8f4a-cbf5126efa4f.png">

how do I show the red circle view outside of drawer view.

**Comment by brendan09** [comment]
You’ll need to make the drawer transparent, disable the shadow (set opacity to zero), set corner radius to 0.0, and set the drawer visual effect view to nil. 

You’ll then need to re-add all of those things manually in your VC to recreate them. 

Pulley can’t have your circle stick out, so the solution is to disable all of pulleys effects (and make it transparent) and put your circle entirely inside the drawer. Then, you can add a white (or blurred) background halfway down the circle and add back shadows, corner rounding, etc manually.
