### ISSUE TITLE
How do we make a UI Element (button/view/etc) appear on top of both the Primary and Drawer view controller?

### ISSUE THREAD

**Issue by vvavepacket** [52inc/Pulley#279]
How do we make a button appear on top of both the Primary and Drawer view controller?

I tried inserting the button on the Primary View Controller, but the problem is as soon as the drawer view is swiped up, the button is hidden on the back because the Drawer view is sitting on top of the Primary View. Basically I want a button that should stay on that view no matter if the drawer view is scrolled up or down.

![image](https://user-images.githubusercontent.com/8295642/47274790-11b99680-d577-11e8-9712-abd7b28fde0e.png)

So I tried putting the Hamburger button inside the Pulley View Controller, but it is not showing up? Are we missing something?

**Comment by vvavepacket** [comment]
closing this issue. this was a duplicate. there was a github outage issue which caused these duplicate posts to occur.

**Comment by sasquatchgit** [comment]
What is the solution to this?

**Comment by brendan09** [comment]
You need to have Pulley as a child view controller of another view controller. In the parent you can overlay things above PulleyViewController view. 

However, it takes a bit of effort as you’ll have to pass through button events to the VCs still contained in Pulley. There are a few other Github issues with the same question that have more info.

**Comment by sasquatchgit** [comment]
Thanks @brendan09. But it really looks like an ugly hack

**Comment by brendan09** [comment]
It’s not a hack, as it’s well within how the parent/child view controller relationship is supposed to work. However, many people under-use view controllers which is probably why you have that impression. View controllers aren’t just for a single screen, and using many parent/child view controllers for various purposes is a much better pattern.

As an example of something similar, you would need to do this exact same thing if you wanted buttons to float on top of a UINavigationController or a UITabBarController. It’s not a hack, it’s simply how the relationship between views and view controllers is designed to work.
