### ISSUE TITLE
making a UI Element sit on top of both Primary and Drawer Controller

### ISSUE THREAD

**Issue by vvavepacket** [52inc/Pulley#281]
How do we make a UI Element (in this case the orange view) sit on top of both Primary and Drawer Views?

![image](https://user-images.githubusercontent.com/8295642/47274927-9822a800-d578-11e8-9c29-ef844afcd1da.png)

I tried putting the UI Element inside the Primary View Controller, but we can see that the Drawer controller is on top of the Orange view. I think that is expected behavior, but how do we make the orange view sit on top of the Drawer too?

I tried instantiating the view on the Pulley View Controller itself but it seems its not allowing and anything we put on the Pulley View Controller's viewDidLoad() is not being called.

Any ideas or suggestions? Thank you.

**Comment by ngohongthai** [comment]
in `viewDidLoad()` function of PrimaryViewController:
`
var orangeView = UIView()
// Configure orangeView
self.pulleyViewController?.view.addSubview(orangeView)
`
orangeView will be on top of your view.

**Comment by brendan09** [comment]
You shouldn’t do what @ngohongthai mentioned. Pulley’s view hierarchy shouldn’t be altered. 

Instead, create a view controller with a container view that takes up the full size of the view controller. Use an embed segue to put your PulleyViewController in that container view. Then, in your new VC, you can put content on top of the container view (note: make sure you don’t try and put it in the container view). 

This will make it float over Pulley and not introduce side effects.
