### ISSUE TITLE
How can I disable scrolling / changing position drawer while a user is interacting with content within drawer?

### ISSUE THREAD

**Issue by notohiro** [52inc/Pulley#282]
I'd like to disable scrolling / changing position drawer while a user is interacting with its contents of inside.
I manually imported Pully and changed `drawerScrollView` to `internal` from `fileprivate`, then set `drawerScrollView.isScrollEnabled` when I need.
Do you have any ideas?

**Comment by notohiro** [comment]
Sorry for your misunderstanding.

I'd like to lock ONLY while a user is interacting with contents within drawer.

https://twitter.com/notohiro/status/1054359801373720577

This is a prototype of my application.
My App shows bar charts in drawer.
Each bars of the bar chart can be select and its selection affects a main content.
I'd like to lock / disable scrolling only while a user selecting bars of the bar chart.

**Comment by brendan09** [comment]
Are you using a gesture recognize? If so, implement the delegate for your gesture recognizer and require all other gesture recognizes to fail if yours is recognized.

**Comment by notohiro** [comment]
No, this chart is implemented by JBChartView, and it doesn't require Gesture Recognizer.
https://github.com/Jawbone/JBChartView

If add Gesture Recognizer to JBChartView, JBChartView will not be able to handle touch events.

**Comment by brendan09** [comment]
Use Pulley's `allowsUserDrawerPositionChange` property in place of your 'isScrollEnabled' call. It'll do the same thing.

**Comment by notohiro** [comment]
That's I'm lookin for!! Works perfectly. Thx!
