### ISSUE TITLE
animationDuration has no effect

### ISSUE THREAD

**Issue by murad1981** [52inc/Pulley#283]
when changing animationDuration value to a different value other than the default 0.3 value, it will have no effect, is. there a way to change the animation duration for changing position of the drawer ?

**Comment by brendan09** [comment]
What value are you changing it to? The animation value will only change the programmatic speed of changing the drawer position.

**Comment by murad1981** [comment]
I changed to 1.5 so the drawer must take 1.5 seconds during its position change, but unfortunately its default speed (0.3 second) doesn’t change

**Comment by brendan09** [comment]
You can only access Pulley to set the value after viewWillAppear is called on your drawer/primary VC. If you attempt to set the value before that (like in viewDidLoad) the pulleyViewController variable on your VCs will be nil so you’ll be attempting to set it on nil, which won’t work.

**Comment by murad1981** [comment]
thank you, moving the code from viewDidLoad to viewWillAppear solved the problem.
