### ISSUE TITLE
How to remove line at the top of drawerViewController?

### ISSUE THREAD

**Issue by bizibizi** [52inc/Pulley#285]
This one https://imgur.com/a/4nv4oOm
2.6.0 swift 3

**Comment by brendan09** [comment]
Pulley doesn’t have a built-in line. If you started with the sample project, you may have forgotten to delete the line in the drawer view controller interface builder screen.

**Comment by bizibizi** [comment]
I have it even in a test project

**Comment by bizibizi** [comment]
@brendan09 make black background color for 2 VCs and you will see it

**Comment by bizibizi** [comment]
and add

        pulleyDrawerVC.drawerCornerRadius = 0
        pulleyDrawerVC.shadowOpacity = 0
        pulleyDrawerVC.backgroundDimmingOpacity = 0
         pulleyDrawerVC.initialDrawerPosition = .collapsed

**Comment by brendan09** [comment]
Pulley doesn’t add a separator line or alter the drawer view controllers content in any way. If there’s a line there, it’s coming from the drawer view controller.

The sample projects drawer view controller has a line view in it. You can delete the line from the drawer view controller’s view. A large number of people use Pulley without a line showing

**Comment by brendan09** [comment]
If you’re seeing a border line color, you can set the border line width to zero or the color to clear.

**Comment by brendan09** [comment]
Use the view hierarchy inspector to see where the line is coming from. If it’s coming from Pulley, please post a picture of what the view hierarchy inspector is showing (at about a 45 degree angle) with the line highlighted.

**Comment by bizibizi** [comment]
issue is here because of white color:

            let cardMaskLayer = CAShapeLayer()
            cardMaskLayer.path = borderPath
            cardMaskLayer.frame = drawerContentContainer.bounds
            cardMaskLayer.fillColor = UIColor.white.cgColor
            cardMaskLayer.backgroundColor = UIColor.clear.cgColor
            drawerContentContainer.layer.mask = cardMaskLayer
            drawerShadowView.layer.shadowPath = borderPath

**Comment by brendan09** [comment]
Mask layers don’t render, so the white won’t render. It’s just used for cutting (it only checks alpha channel).

**Comment by bizibizi** [comment]
@benjaminfischer any way to remove that without editting original code?

**Comment by bizibizi** [comment]
@brendan09 but i can see it on device and simulators...

**Comment by brendan09** [comment]
Changing the fillColor of the mask layer won’t have an effect, as it doesn’t render the color. It’s not in the view/layer hierarchy.

If you want to use your own mask, assign a mask view to your drawer view controllers view. It’ll replace the one Pulley uses.
