### ISSUE TITLE
Reload Pulley

### ISSUE THREAD

**Issue by bizibizi** [52inc/Pulley#288]
I changed height in 
PulleyDrawerViewControllerDelegate  
func collapsedDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat 

how can I reload it now?

**Comment by bizibizi** [comment]
@brendan09

**Comment by brendan09** [comment]
When you change settings you can use setNeedsSupportedDrawerPositionsUpdate() on Pulley to reload the configuration.
