### ISSUE TITLE
Switch background color to clear

### ISSUE THREAD

**Issue by bizibizi** [52inc/Pulley#290]
I have a black blick https://imgur.com/a/1K6BjGI

My code:

        let mainContentVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "PrimaryContentViewController")
        let drawerContentVC = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "DrawerContentViewController")
        let pulleyViewController = PulleyViewController(contentViewController: mainContentVC, drawerViewController: drawerContentVC)
        pulleyViewController.drawerCornerRadius = 1
        pulleyViewController.shadowOpacity = 0
        pulleyViewController.backgroundDimmingOpacity = 0
        pulleyViewController.drawerBackgroundVisualEffectView = nil

        extension DrawerContentViewController: PulleyDrawerViewControllerDelegate {

    func drawerChangedDistanceFromBottom(drawer: PulleyViewController, distance: CGFloat, bottomSafeArea: CGFloat)
    {
        if distance > 300
        {
            view.backgroundColor = .white
        } else {
            view.backgroundColor = .clear
        }
        
            }

**Comment by bizibizi** [comment]
@brendan09

**Comment by brendan09** [comment]
That’s a UIKit rendering artifact, nothing that can be fixed in Pulley.

**Comment by bizibizi** [comment]
Any way to fix that?
