### ISSUE TITLE
setDrawerPosition never called

### ISSUE THREAD

**Issue by lahavamir27** [52inc/Pulley#291]
hey,

Thank for your awesome framework!
For some reason setDrawerPosition stop working.
When i flick the drawer up with my finger its not animate.

do you have any suggestion?

**Comment by brendan09** [comment]
Can you provide a video of what happens?

Have you altered or subclassed Pulley in any way? What code is in your delegates?

**Comment by lahavamir27** [comment]
for some wierd reason it works again!
thank for quick replay
