### ISSUE TITLE
how to know if pulley is opened fully?

### ISSUE THREAD

**Issue by vvavepacket** [52inc/Pulley#292]
Is there any property or any event handler we can tapped/use wherein if the user fully swipes up the Pulley, we will get notified?

**Comment by vvavepacket** [comment]
I'm trying to use the delegate, but why is that it is not finding the drawerPosition attribute?

![image](https://user-images.githubusercontent.com/8295642/48480556-dfe3ca80-e7d8-11e8-8ab3-efd1bc1c7fd6.png)

**Comment by brendan09** [comment]
Make sure you’ve imported Pulley in that file. You’re also getting a warning for the delegate method, so verify that’s implemented correctly.

**Comment by vvavepacket** [comment]
@brendan09 

Yes I'm sure I imported Pulley in the file properly. :/

![image](https://user-images.githubusercontent.com/8295642/48524199-60dca980-e84d-11e8-8a88-df24d2e962f8.png)

**Comment by brendan09** [comment]
What is the warning on your delegate method?

The only reasons it wouldn’t be able to find it are:

1. Not imported
2. Pulley isn’t a part of the current target.

**Comment by vvavepacket** [comment]
![image](https://user-images.githubusercontent.com/8295642/48524354-faa45680-e84d-11e8-8894-efafbe20798e.png)

**Comment by brendan09** [comment]
You need to fix the warning or the delegate won’t be called.

**Comment by vvavepacket** [comment]
@brendan09 

Its fixed now. I used the same file name which is PulleyViewController. I renamed it to PulleyViewController2 so that it does not conflict with PulleyViewController
