### ISSUE TITLE
Calling prepare() on Feedback Generator Earlier

### ISSUE THREAD

**Issue by hyerra** [52inc/Pulley#302]
Just thought of a suggestion. According to Apple's [documentation](https://developer.apple.com/documentation/uikit/uifeedbackgenerator/2369818-prepare), there should be some time in between when the `prepare()` method is called and when the haptic engine triggers feedback in order to improve latency. If there is no time period difference, calling `prepare()` doesn't help much. Is there any way to call the `prepare()` method a bit earlier in the code so the haptic engine has more time to get ready?

https://github.com/52inc/Pulley/blob/cb0c9daaa8a0fcf7c09cc8a5fb8a745a01bd5987/PulleyLib/PulleyViewController.swift#L1022-L1032

**Comment by hyerra** [comment]
To be honest, I'm actually not sure if there are any issues as I'm stuck on the iPhone 6s which doesn't have haptics haha. Just thought it'd be good practice though as it's in the docs. Do you have any ideas @ulmentflam?

**Comment by ulmentflam** [comment]
@hyerra I will do some testing to see if there is any significant latency improvement by calling `prepare()` in the willBeginDecelerating method while I am fixing a few other outstanding issues. I will let you know if there is a significant latency difference between calling it in willBeginDecelerating and right before triggering.

**Comment by florianbuerger** [comment]
I was about to add a PR for to trigger `prepare()` in `scrollViewWillEndDragging`. Glad I saw the discussion. 

I can feel a slightly reduced latency on iPhone X / iPhone X🅂 so I'd say it should be changed.

**Comment by ulmentflam** [comment]
I just merged the trigger for `prepare()` in `scrollViewWillEndDragging` into master.
