### ISSUE TITLE
Rotation causes viewdidlayoutsubviews to fire repeatedly, creating a glitch when panning

### ISSUE THREAD

**Issue by ksinghal** [52inc/Pulley#307]
I have an app that is only used in portrait mode, with the only allowed drawer positions as `[.partiallyRevealed, .open]`. When I slightly rotate the device while panning, even though the interface stays in portrait, the PulleyViewController's `viewDidLayoutSubviews` is called which triggers `setDrawerPosition` on line 914 of `PulleyViewController.swift`. If I am in the middle of opening the drawer, it resets to the bottom during the pan, creating a glitch in the scroll.

**Comment by brendan09** [comment]
Does this occur in the sample project as well?

**Comment by ksinghal** [comment]
no, because the sample project doesn't do much beyond show the drawer. However, I have autolayout constraints that need to be adjusted programmatically, and so I call `setNeedsLayout` on my pulley's `primaryContentViewController` which then triggers viewDidLayoutSubviews, at least I think that is the culprit according to [this](https://stackoverflow.com/a/27050776/6500768) SO post. I think there may be a better place to move the code that is currently in `viewDidLayoutSubivews`, since in real-world use cases some subviews may need to be laid out without triggering a relayout of the drawer

**Comment by brendan09** [comment]
Calling setNeedsLayout on your view controllers view shouldn’t impact Pulley, as PulleyViewController’s view didn’t perform a layout pass. If you’re calling it on PulleyViewController’s view then that would definitely create an issue.

**Comment by ksinghal** [comment]
As another suggestion, perhaps before calling `setDrawerPosition` you could add a check to see if the pan is in progress?

**Comment by brendan09** [comment]
Regardless of if a pan is in progress, the drawer position needs to be updated and rendered at that time. 

If it wasn’t, rotating would result in the drawer width not changing to match the width of the screen. This would cause more problems than it solves, most likely. 

If panning causes issues during rotation or resizing, cancelling the gesture recognizer upon rotation / willLayoutSubviews might be a better option.

**Comment by ksinghal** [comment]
Thank you for your quick responses. This project is truly awesome by the way. I am trying to track down what is causing viewDidLayoutSubviews to fire repeatedly when rotating my device, since I am unable to replicate this issue immediately in the example application. I will update you and either close the issue or add additional details when I have

**Comment by ksinghal** [comment]
Ok I found the issue. If you simply replace the MKMapView in the example project with Mapbox's MGLMapView, and uncheck all orientations except Portrait, you get the same exact issue I described at first. Turns out the `setNeedsLayout` I described above wasn't the issue. Somehow it's the MGLMapView from Mapbox that is triggering PulleyViewController's `viewDidLayoutSubviews` even though it is in the primary content view controller. Now obviously this is not something caused directly within the Pulley library, but it would make Pulley more universally compatible if we were able to find a workaround here

**Comment by brendan09** [comment]
This sounds more like an issue with MGLMapView. A view should never trigger a layout of a parent view in its hierarchy (especially not across view controllers). 

This isn’t really a compatibility issue, so much as MGLMapView doing something it shouldn’t. (No view should do this.)

**Comment by ksinghal** [comment]
I'm sure you are right, there are a number of bugs with Mapbox, but I have found it to fit my particular use case. For clarification though, since we are using container views in Pulley, the MGLMapView is subview of the PulleyViewController. Thus, if MGLMapView's frame is adjusted then it follows that the PulleyViewController's `viewDidLayoutSubviews` would fire, correct?

**Comment by brendan09** [comment]
No, it would be a subview of your primary view controller’s view. Pulley would embed your primary view controller’s view in another view that Pulley manages (the container view). 

Even if it were a direct subview of Pulley, it still shouldn’t cause viewDidLayoutSubviews to be called.

viewDidLayoutSubviews is _only_ called when a view controller’s view completes a layout pass. Its not called when a subview of that view completes a layout pass.

For some reason, it appears that MGLMapView is invalidating the entire view hierarchy not just its own view.

**Comment by ksinghal** [comment]
ok great, thank you for the education. I will be forwarding this thread along to the Mapbox team for review and hopefully they can make a fix. Thank you for your assistance in helping me dig though this glitch! I wonder if you could suggest a temporary workaround in the meantime?

**Comment by brendan09** [comment]
Without knowing exactly what it’s doing, it’s hard to come up with a workaround. My only idea is to cancel mapbox’s panning gesture when a rotation occurs.

**Comment by ksinghal** [comment]
By the panning glitch I was referring to panning the drawer to open it while also rotating the device. The mapbox panning gesture shouldn't have anything to do with this - I believe Mapbox is, as you said, invalidating the view hierarchy and thus causing a glitch while panning the drawer

**Comment by ksinghal** [comment]
I will close this issue, but if you have any ideas please do let me know!
