### ISSUE TITLE
Changing the background effect of the drawer from another swift file

### ISSUE THREAD

**Issue by ipoogleduck** [52inc/Pulley#308]
Sorry if this is a stupid question, I'm new to swift. I was wondering if it's possible to change the drawerBackgroundVisualEffectView variable from extraLight to dark and so forth within my class for the drawer in a separate swift file. I am trying to make it switch between a light and dark theme at a certain time.

**Comment by brendan09** [comment]
Yes, you can modify it as long as you have a reference to Pulley. 

If you’ve imported Pulley in your file (and you’re trying to modify it from within your drawer or primary content view controller) you can use the convenience accessory of “self.pulleyViewController” to access the nearest PulleyViewController that contains your view controller.

**Comment by ipoogleduck** [comment]
Sorry, I'm still confused
If I wanted the drawer to  turn dark would I put "drawerBackgroundVisualEffectView = .dark" ? And then where would "self.pulleyViewController" fit in?

**Comment by brendan09** [comment]
self.pulleyViewController.drawerBackgroundVisualEffectView =

However, it doesn’t take a value of “.dark”. You’ll need to create an instance of UIVisualEffectView. Take a look at the apple docs on UIVisualEffectView for how to set that up.

**Comment by ipoogleduck** [comment]
Thanks! It works now!
