### ISSUE TITLE
Subclasses PulleyViewController

### ISSUE THREAD

**Issue by ahoang** [52inc/Pulley#31]
I'm implementing the controls from IB and subclassed PulleyViewController and set the VC to my subclass in IB. But when I navigate to the VC, I get a crash:

```Terminating app due to uncaught exception 'NSUnknownKeyException', reason: '[<UIViewController 0x7f9991607900> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key drawerContentContainerView.```

Things run perfectly if I don't set the class to my subclass, but I need to subclass it to customize the drawer height.

**Comment by brendan09** [comment]
PulleyViewController doesn't support subclassing. You should use the delegate methods available to adjust the drawer height.

See `func partialRevealDrawerHeight() -> CGFloat` on PulleyDrawerViewControllerDelegate.

**Comment by ahoang** [comment]
@brendan09 How do I set the drawer as the delegate?

**Comment by brendan09** [comment]
You don't have to set anything. As long as the drawer VC implements the protocol (and the method) then it will be called automatically.

**Comment by brendan09** [comment]
Take a look at the sample project for an example setup.

**Comment by ahoang** [comment]
This doesn't work because my drawer VC is embedded in a navigation controller. is there anyway I can do it without subclass uinavigation controller?

**Comment by brendan09** [comment]
No, you'll need to subclass UINavigationController and provide an implementation there to return values or proxy it to the currently visible VC in the nav controller.

**Comment by ahoang** [comment]
okay thanks.
