### ISSUE TITLE
Documentation Not Clear

### ISSUE THREAD

**Issue by DrBeta** [52inc/Pulley#310]
I tried to follow the README.md but I can't figure out what you are trying to get me to do.

**Comment by brendan09** [comment]
There’s a sample project in the repo you can use to help.

**Comment by DrBeta** [comment]
I can not find the project.

**Comment by brendan09** [comment]
There’s an Xcode project named “Pulley” in the root of the repo. I’m not sure how you can’t find it. 

The documentation is also step-by-step with pictures, and matches the sample project as an example. 

If you’re unable to locate the sample project in the repo, I’m not sure I’ll be able to provide you any further assistance.

**Comment by DrBeta** [comment]
I meant I don't see the storyboard files, for example

**Comment by brendan09** [comment]
Open the project in Xcode. The storyboard files are there. There’s only a handful of files in the sample project. The Storyboard file should be easy to find in the project, you’ll just need to look in the file list on the left.

**Comment by brendan09** [comment]
In the repo, Main.storyboard is in the Pulley folder. I’m unable to provide further assistance if you can’t do some basic searching.

Please only open an issue have you have a bug or a specific usage question.

**Comment by DrBeta** [comment]
Thanks
