### ISSUE TITLE
push view into drawer view with some transition

### ISSUE THREAD

**Issue by kunusiths** [52inc/Pulley#314]
Hi Sir,
is it possible to push another viewcontroller in sliding view on tapping of table view cell in that slide view.please answer

**Comment by brendan09** [comment]
Pulley supports a fade transition for switching drawers. If you want to present it sliding up you’ll need to present a new instance of PulleyViewController with the presentation style set to “over current context” and present it from the drawer view controller. 

There are others discussion modal presentation of Pulley to create this effect in other issues. I’m currently on mobile so I can’t provide a link.

**Comment by kunusiths** [comment]
Please provide as early as possible.it will be very helpful

**Comment by brendan09** [comment]
See the discussion at this link: 
https://github.com/52inc/Pulley/issues/89
