### ISSUE TITLE
Changing a drawer position from Another VC

### ISSUE THREAD

**Issue by black-magk** [52inc/Pulley#317]
The question I have is what is the best way to adjust the drawer via another view controller?

The situation is as follows:

A button is located in the VC of the primaryContainerView. I would like this to be able to toggle from the all the way “collapsed” position to only “partially”. Any help would be greatly appreciated.

**Comment by brendan09** [comment]
You should be able to use the convenience accessor to access Pulley.

In your primaryContentViewController: self.pulleyViewController.setDrawerPosition()

**Comment by black-magk** [comment]
Thank you! This worked flawlessly.
