### ISSUE TITLE
TopInset Animation

### ISSUE THREAD

**Issue by sadanro100** [52inc/Pulley#325]
Is it possible to set TopInset for open state with animation? 

The height of the content in my primaryContentViewController changes, so I update the TopInset to avoid scrolling within primaryContentViewController if there's actual avaible room on the top of the viewcontroller.

I expand and collapse the content with animation within the viewcontroller, so I'd like to update the topInset with animation as well

**Comment by brendan09** [comment]
You should be able to animate it as long as you set the top inset inside an animation block and then call layoutIfNeeded() on PulleyViewController’s view immediately after (while still in the animation block).

If that doesn’t work, there may not be a way to do it. But, I think there’s a good chance it will work.

**Comment by sadanro100** [comment]
That worked!!! Thank you!
