### ISSUE TITLE
new warning in Xcode 10.2

### ISSUE THREAD

**Issue by appsird** [52inc/Pulley#326]
fyi: This Xcode release arrived today and elicits a new warning per below:

<img width="1573" alt="Screen Shot 2019-03-25 at 3 55 31 PM" src="https://user-images.githubusercontent.com/8471833/54959499-858d1000-4f16-11e9-9fd6-e42c4ea96fc8.png">

**Comment by ulmentflam** [comment]
@appsird Thanks for the heads up! I shall be working on updating pulley for the Xcode 10.2 update and Swift 5.0 in the coming weeks.

**Comment by appsird** [comment]
thanks!
