### ISSUE TITLE
dynamic height for partiallyRevealed

### ISSUE THREAD

**Issue by hixfield** [52inc/Pulley#336]
I want to use the drawer only in [.collapsed, .partiallyRevealed] mode.
In partiallyRevealed mode I use the partialRevealDrawerHeight delegate method to signal the height I need. However this height changes (via some event that is fired based on result of web service).
How can I tell the drawer to take the new height into account?
If the drawer is partialRevealed at moment of update, how can I make it animate to the new partialRevealDrawerHeight?

**Comment by brendan09** [comment]
You can call setNeedsSupportedDrawerPositionsUpdate() on PulleyViewController to refresh the supported positions and sizes.

**Comment by hixfield** [comment]
Will this animate to the new height?

**Comment by hixfield** [comment]
This works perfectly and is animated too. Thanks for the fast reply!
