### ISSUE TITLE
How to make drawer (partially) transparent?

### ISSUE THREAD

**Issue by hixfield** [52inc/Pulley#338]
What are the steps to make the drawer partially transparent so that eg. a map on the content vc is still somewhat visible through the drawer?
(config via storyboard)

**Comment by brendan09** [comment]
A blur effect like maps is enabled by default. This lets some of the color come through.

If you want partially transparent (without blur) you can set the visual effect property on PulleyViewController to nil and handle it all in your drawer view controller.
