### ISSUE TITLE
Is it possible to pull the PulleyDrawerViewController down to open, when placed at the top of the window?

### ISSUE THREAD

**Issue by ojacevedo** [52inc/Pulley#34]
This would be the same as maps on iPad. Could not tell from the documentation and source if it is possible.

Other than this it is a great PulleyViewController API.

Thanks,

Orlando

**Comment by brendan09** [comment]
It's not a built in feature, but you could accomplish this using CALayer transforms to invert the view. Then use an inverse transform on your drawer VC so it still looks upright to the user.

Pulley VC is meant to be full screen, so it won't provide the "side" view that you get on iPad without some custom containers or alteration.

**Comment by brendan09** [comment]
@ojacevedo The master branch now includes support for this, in the form of mimicking the iPad Maps layout, if you're still interested. It's not _identical_ to Maps, but it's fairly close and tweaking the options can probably get you the rest of the way there. 

Right now it's more of a 'test' version, as it required a lot of changes. It should work, but I'm not confident enough to push it out to everyone yet. If you feel like giving it a try, I'm looking for feedback / bug-testing before pushing it out to CocoaPods. 

Looking forward to any feedback you may have. Thanks!
