### ISSUE TITLE
can this be added behind the tabbar instead of window?

### ISSUE THREAD

**Issue by pprevalon** [52inc/Pulley#35]
can this be added behind the tabbar instead of window?

**Comment by brendan09** [comment]
I haven't tried it, but I think it would probably work. I would recommend using an opaque tabbar, instead of translucent, as I don't believe it takes into account the bottom layout guide.

**Comment by darianjug** [comment]
I have managed to place it behind the tab bar with no problems. As Brendan
said it dosen't take in account the bottom layout guide so you need to set
the bottom constraint in the pulley view programmatically based on bottom
layout guide. You can use the translucent tab bar then.

**Comment by brendan09** [comment]
@darianjug Thanks for the confirmation!

**Comment by pprevalon** [comment]
@darianjug can you show an example of how you added the Pulley to the view controller. @brendan09 why not subview the pulley instead of window. I thought it would be easier

**Comment by brendan09** [comment]
You put the UITabbarController as the primary content view controller of PulleyViewController. Don't put the Pulley VC in the tab bar controller.

**Comment by brendan09** [comment]
@darianjug Use the UITabbarController as the root of the window. Use the Pulley VC as one of the view controllers in the tab bar. This will make sure the tab bar is in front of the tab bar.

You shouldn't need to add anything (explicitly) as a subview to UIWindow in this setup.

**Comment by pprevalon** [comment]
This work great Thanks for the help.
