### ISSUE TITLE
Dependencies in Primary

### ISSUE THREAD

**Issue by viktas** [52inc/Pulley#353]
Hey, so I'm pushing the PulleyViewController, everything is working, but I also need to inject dependencies to the PrimaryContentViewController, from the current class, where I push the PulleyViewController. How can I do that?

            let vc:PulleyViewController? = UIStoryboard.init(name:"myName", bundle: Bundle(identifier: "myBundle"
            )).instantiateViewController(withIdentifier: "PulleyViewController")
                as?PulleyViewController
            navigationController?.pushViewController(vc!, animated: true)

**Comment by viktas** [comment]
What I'm asking is that I have a repository instance in the class, that this is code is in, and I need to pass that instance to my PrimaryContentViewController.

**Comment by brendan09** [comment]
There is a property on PulleyViewController that is the current primary content view controller. There’s also one for the drawer.

You can cast that to your class type and access it as normal.

You do need to make sure the view has been loaded before accessing it, so if it’s before your presentation you’ll need to call loadViewIfNeeded on Pulley.

**Comment by viktas** [comment]
So I can just do that?

            vc = UIStoryboard.init(name:"myName", bundle: Bundle(identifier: "myBundle"
            )).instantiateViewController(withIdentifier: "PulleyViewController")
                as?PulleyViewController
            let primary = vc?.primaryContentViewController as! MyPrimaryViewController
            primary.injectDependencies(repository: repository)
            navigationController?.pushViewController(vc!, animated: true)

**Comment by viktas** [comment]
Yeah, I need to call loadViewIfNeeded, it worked. Thanks!
