### ISSUE TITLE
change collapsed drawer height while visible

### ISSUE THREAD

**Issue by thebrandontyler** [52inc/Pulley#354]
Hey there.  I've looked through the issues/readme, etc and can't seem to find an answer to this question.  Is there a way to have the pulley view controller visible and dynamically change the height of the collapsed position?  I have a UIView (container) above a tableview in the drawer and this container can have multiple/different views in it depending on what the user is doing.  I'd like to be able to make the container view visible always in collapsed position but because its height is dynamic, I need to have the drawer move up and down slightly while staying in collapsed position.

I tried collapsedDrawerHeight(bottomSafeArea: CGFloat), and while this does create additional height, the drawer doesn't slide up to the top of the additional height created (for example, in your demo, the temperature label would move up but the drawer would not).  Any help would be appreciated.  Thank you!

**Comment by brendan09** [comment]
Yes, call there’s a function you can call to tell Pulley that you’ve updated the drawer positions. This will re-query the positions and update the UI.

**Comment by thebrandontyler** [comment]
![Image from iOS](https://user-images.githubusercontent.com/5687291/62978382-01a8c700-bdd6-11e9-82de-3f77bde4226b.jpg)

Here's the issue I'm running into when I update collapsedDrawerHeight(bottomSafeArea: CGFloat).  I'm also using drawerPositionDidChange delegate method, but I am having issues getting the drawer to slide up (although this transparent view in the image is showing).  Thanks for the help.

**Comment by thebrandontyler** [comment]
I think I resolved this problem just now.  I'm calling setNeedsSupportedDrawerPositionsUpdate which forces the drawer to update the UI (this is probably the function you were talking about).  Thanks again!
