### ISSUE TITLE
Xcode 11/SPM: Pulley has no Package.swift manifest

### ISSUE THREAD

**Issue by RamblinWreck77** [52inc/Pulley#358]
Pretty much the title. We're attempting to move from Cocoapods > SPM with Xcode 11 GM, would it be possible to add a Package.swift file so SPM can download Pulley?

Thanks for a great tool!

**Comment by ulmentflam** [comment]
Hey @RamblinWreck77, If you check out the Xcode 11 branch we have the Package.swift file coming down the pipeline. Now that we are on the Xcode 11 GM, I will be looking into getting a release out for the SPM with the next version of Pulley.
