### ISSUE TITLE
Problem when UINavigationController is primary controller

### ISSUE THREAD

**Issue by fuad-adetoro** [52inc/Pulley#364]
Hey guys, I have an issue I can't seem to rectify. I have a UITabBarController with 4 tabs, one of those tabs is a PulleyViewController. The primary controller is a UINavigationController, when I click on the tab everything is in order, but when I go to another tab and then return the primary controller goes blank / shows a white view. 

I managed to fix it by making the primary controller the top view controller of the navigation controller but that's not what I want.

**Comment by ulmentflam** [comment]
How did you initialize your PulleyViewController? Did you use interface builder or initialize it in code? Is it possible that when you segue to the view the embedded references to the subviews are being deallocated and when you return to the view they are not being reallocated? If you could post a code snippet it would  be helpful in helping you debug.
