### ISSUE TITLE
Bug with UIVisualEffectView (pre iOS 10) 

### ISSUE THREAD

**Issue by toohotz** [52inc/Pulley#37]
So before getting into the meat of things, I dug through the old closed issues as I figured that I would find the reason as to why this seems to work on iOS 10 for iPad devices specifically.  

Came across this closed issue where the `UIVisualEffectView` implementation had changed with iOS 10 where I came across the same issue as well myself.  [https://github.com/52inc/Pulley/issues/5](url)

I noticed that on actual device testing and on simulator as well (testing against iOS 9.3), the `UIVisualEffectView` is broken on the UITableViewCells as the effect isn't being rendered.

Screenshots:

`iOS 9`
![iOS 9](http://i.imgur.com/yU3hx9b.png)

`iOS 10`
![Imgur](http://i.imgur.com/T80wHPL.png)

Wondering if the pre iOS 10 solution that worked on 9 could be used here with a conditional `#available(<iOS Version here>)` would be a possible work around.

**Comment by brendan09** [comment]
So, that doesn't have anything to do with the UIVisualEffectView. That most likely has something to do with tableview or cell (or cell content view) background color not being set in a way that iOS 9 likes.

If the UIVisualEffectView was broken you wouldn't be seeing a correct blur behind the top part of the drawer (near the search bar).

So, you should look at why the cells / tableview aren't rendering transparently...not at the visual effect view handling.

**Comment by toohotz** [comment]
*Sigh* trivial thing I feel like but setting the background color on the `UITableViewCell` itself from a storyboard or xib file apparently is broken so setting it explicitly on in `celForRow:` works..  Made a code fix for this on another branch if you're interested.
