### ISSUE TITLE
Display Over UITabBar

### ISSUE THREAD

**Issue by Infinity-James** [52inc/Pulley#38]
What would be the ideal way to display the drawer content over that `tabBar` of a `UITabBarController`?

**Comment by brendan09** [comment]
Use a UITabbarController as the main content view controller.

**Comment by Infinity-James** [comment]
I have to basically embed my entire UI hierarchy within a PulleyViewController?

**Comment by brendan09** [comment]
If you want the drawer to appear over the tabbar, then yes. The main content VC is a child of the PulleyDrawerController, similar to how UIViewControllers can be children of a UINavigationController or UITabbarController. As a result, you'll have to use the UITabbarController as the main content VC.

But, you also need to consider that (unless you're setting the drawer to hidden) that it will cover your tabbar when it's visible.

All of that "how to do it" being said, I would discourage you from doing it as it's not a great UI pattern, and the Pulley API doesn't lend itself to switching drawer VCs based on the currently shown tab in a UITabbarController. It can be done, but it definitely isn't what it was built for.
