### ISSUE TITLE
drawer View in collapsed position under TabBarController 

### ISSUE THREAD

**Issue by MoElnaggar14** [52inc/Pulley#383]
how I can set drawer height when launched Pulley ViewController

**Comment by brendan09** [comment]
It queries the drawer VC for the height for a given position. Please see the README or sample project.

**Comment by MoElnaggar14** [comment]
I have a UITabBarController contain PulleyController so the drawer VC in the collapsed position appear under the TabBar

**Comment by brendan09** [comment]
As I said before, your drawer VC is responsible for returning the height in the delegate method.

It doesn’t matter that it’s contained in a UITabBarController.

See the README or sample project for how to change the height of the drawer positions.
