### ISSUE TITLE
Top spacing issue

### ISSUE THREAD

**Issue by AshutosQuickride** [52inc/Pulley#386]
Hi there i am using this pulley its a great library.

But i am facing some issue like if my drawer view is opened fully and i am going to other screen and coming back the drawer view is taking some top space.How i can avoid that. state is open

**Comment by triztian** [comment]
You can use the `.partiallyRevealed` state instead of `.open` to control the height:

```swift
extension MyDrawer: PulleyDrawerViewControllerDelegate {
    func partialRevealDrawerHeight(bottomSafeArea: CGFloat) -> CGFloat {
    99.0 // define your custom height here
    }
}
```
