### ISSUE TITLE
Memory Leak on iPhone 11 when changing orientation

### ISSUE THREAD

**Issue by fabiomd** [52inc/Pulley#387]
I got a issue in that seans to happen only in iPhone 11.

I have a sequence of screens stacked using a navigationController.
Among the stacked screens I have a PulleyViewController type screen that implements the willTransitionTo method,
inside the method i change the navigationBar visibility based on the app current orientation.
However the i rotate the app from landscape to portrait and back to landscape , the app starts to increase the memory.
Using the memory debugger, I saw that during access the PulleyViewController maskBackgroundDimmingView method is being triggered infinitely, adding infinite borderPath.

**Comment by ulmentflam** [comment]
@fabiomd I have not been able to replicate this memory leak on my iPhone 11, can you let me know if you are still experiencing it on the current release?
