### ISSUE TITLE
click on statusbar open drawer

### ISSUE THREAD

**Issue by fariz-siracli** [52inc/Pulley#39]
Hello guys. Thanks for sach amazing tool. have got two questions.
1. I have implemented PulleyDrawer and on app start i'm setting it to closed, but when i click to statusbar pulley becomes visible to collapsed position. What could be the reason for this.
2. When i load results to Drawer tableview all results are duplicated in table view. So if my drawer should show,  for ex ["apple", "ios", "ipad", "iphone"] then it shows  drawer with result ["apple", "ios", "ipad", "iphone", "apple", "ios", "ipad", "iphone"] 

Thank you for attention.

**Comment by brendan09** [comment]
1. Older versions of Pulley have the UIScrollView in the PulleyViewController configured with scrollsToTop set to true. If you update to the latest version of Pulley, this should be resolved.

2. That's an issue with your UITableViewDelegate / UITableViewDataSource implementation, and is not related to the functionality of Pulley.
