### ISSUE TITLE
Xcode12: "No such module Pulley"

### ISSUE THREAD

**Issue by triztian** [52inc/Pulley#392]
After installing and opening my project with Xcode12 I started seeing that message in files that had `import Pulley` statements.

My project used to build with Xcode 11.7 and I realized that newly pod init'd project did not have this issue when I tried to replicate. The min iOS version for my project is 10.

I'm still seeing the issue, when try to build to run on a iOS 14 simulator target. I've tried the following:

```bash
# 1. Clear out the workspace:
rm -rf MyProject.xcworkspace 
mv Podfile Podfile.bak

# 2. Deintegrate cocoapods
pod deintegrate

# 3. Install Xcode 12 support cocoapods
gem install cocoapods -v 1.10.rc.1
mv Podfile.bak Podfile
```
Before running `pod install` I have the following pulley version in my `Podfile`:

```ruby
pod 'Pulley', :git => 'https://github.com/52inc/Pulley.git', :branch => 'xcode12'
```

**Comment by ulmentflam** [comment]
@triztian Did you do a `pod install --repo-update`?

**Comment by triztian** [comment]
@ulmentflam no but I just tried it, it installs successfully:

```bash
pod install --repo-update
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Generating Pods project
Integrating client project
Pod installation complete! There are 23 dependencies from the Podfile and 43 total pods installed.
```

but same result on build.

One thing to note though is that my project has the following setting:

```bash
VALID_ARCHS=$(ARCHS_STANDARD_64_BIT) # VALID_ARCHS = arm64 arm64e
```

**Comment by triztian** [comment]
@ulmentflam I was able to solve this issue by doing the following, instead of setting `VALID_ARCHS` in Xcode 12 we have a new setting: `EXCLUDED_ARCHS` which I set to `i386 armv7` and changed my main project's `Architecture` setting to `$(STANDARD_ARCHS)`.

This is based on finding this in the [Xcode 12 Release Notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-12-release-notes/):

> Deprecations
>  * The Build Settings editor no longer includes the Valid Architectures build setting (VALID_ARCHS), and its use is discouraged. Instead, there is a new Excluded Architectures build setting (EXCLUDED_ARCHS). If a project includes VALID_ARCHS, the setting is displayed in the User-Defined section of the Build Settings editor. (15145028)
>   * The legacy build system is deprecated, and will be removed in a future release. (62742902)

I also added the following my pod file to remove a bunch of warnings:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
    end
  end
end
```
