### ISSUE TITLE
Set PulleyDrawerViewController scrolling enable.

### ISSUE THREAD

**Issue by Danielthenew** [52inc/Pulley#4]
Hallo first of all Thank you so much for this example it is very nice. So to the question how can i set the PullyDrawerView to enable for scrolling so the user must click a button too get back to normal mode ?
So i have it in open mode and have set a view in the PullyDrawerView (scrolling must be enable) then user must select more things and must click done and then drawer view get back to the normal mode with scrolling. 
Thank you for your answer.

**Comment by brendan09** [comment]
The scrollview is not accessible through the PulleyViewController public interface, so right now that isn't possible. I wouldn't recommend it, as that isn't how the control was designed / used in Apple apps.

However, if you _have_ to have this functionality:

Fork / modify the library and remove "private" from the 'drawerScrollView' variable in PulleyDrawerController. You can then set scrollEnabled = true or scrollEnabled = false as needed on the scrollview, and that will allow / disallow scrolling.

**Comment by Danielthenew** [comment]
I have it, Thank you :)
