### ISSUE TITLE
[QUESTION] Help with error: "When instantiating from Interface Builder you must provide container views with an embedded view controller.

### ISSUE THREAD

**Issue by sophiagatliff** [52inc/Pulley#403]
**Describe the question**
A clear and concise question about the functionality of pulley or a delegate method.

**Code snippets and helpful information**
Any code snippets, screenshots, recordings, or any other helpful information for addressing your question.

**Pulley Information (optional):**
 - Version: [e.g. 2.8.5]
 - Any customizations or tweaks: [e.g. Yes/No]
 - Did you Subclass: [e.g. Yes/No]

**Xcode Information (optional):**
 - Version: [e.g. 12]
 - Installation: [e.g. Cocoapods]
 - Interface Builder: [e.g. Yes/No]

**Comment by ulmentflam** [comment]
If you right click on the scene where you have the PulleyViewController you will see an outlet for the `primaryContentContainerView` and the `drawerContentContainerView`. Connect those to your embedded view controller and you should be good to go. See my screen shot below for more information on the location of the outlet in Xcode.


<img width="1920" alt="Screen Shot 2020-11-20 at 9 46 07 AM (2)" src="https://user-images.githubusercontent.com/6037314/99814684-4eba3380-2b17-11eb-9881-90660e6dce20.png">
