### ISSUE TITLE
[BUG] iPad panel mode problem

### ISSUE THREAD

**Issue by iGeX** [52inc/Pulley#409]
Hello

I faced problem with iPad panel mode when I open pulley in .closed mode by default. Panel is supposed to be hidden but I can see chunk of panel overlapping from outside.  I decided that it is bug in my rewrited code (I have rewritten it for pure Xamarin.Ios), but it appears in both libraries (I've written exactly the same Swift and Xamarin demos, all behavior is same). I've used iPad Pro (12.9-inch)(4th-generation) simulator running iOS 14.2.

**Comment by MarkKazakov** [comment]
I've also experienced the issue, submitted a PR with the fix.
https://github.com/52inc/Pulley/pull/410
