### ISSUE TITLE
Animation for changing drawers

### ISSUE THREAD

**Issue by Archivus** [52inc/Pulley#41]
First of all thank you for sharing this amazing library!

Would it be possible to more accurately imitate the animation in the iOS 10 Maps app when calling `setDrawerContentViewController`?

**Comment by brendan09** [comment]
If I recall, Apple Maps actually presents a new drawer over an existing drawer. That functionality isn't natively supported by Pulley, but could probably be accomplished with some clever uses of modal presentation and toggling the hidden setting of the presented drawer.

**Comment by Archivus** [comment]
I'll try and implement it myself and will submit a pull request then. In the meanwhile, I've slightly modified the animation duration of `setDrawerPosition` so it's faster on drag and slower otherwise (just like in Apple Maps). Would you like me to submit a pull request as well?

**Comment by brendan09** [comment]
Sure, that would be great. I'd love to consider including it.

**Comment by Archivus** [comment]
So what I ended up doing was embedding a Pulley View Controller within another one. I'll report back if anything misbehaves ☺️

**Comment by brendan09** [comment]
Ha, yeah. I figured it might end up being something like that. Hopefully it works out!

**Comment by Archivus** [comment]
I tried a custom `UIViewControllerAnimatedTransitioning`but that didn't work out too well. Eventually I just settled for the lazy man's solution. 
Finally, concerning the animation speeds, when dragging, the animation speed should stay at around 0.3s but when opening it via a swipe gesture, it should be closer to 0.5-0.6. I've also added the suggestion cell that pops up/hides if you're interested at all.

**Comment by brendan09** [comment]
Sure, I'd be happy to take a look and consider merging.

**Comment by mikegabriel** [comment]
@Archivus just wondering if you have any examples of this working?  I'm in early stages of layout planning and thought this might be ideal.

Thanks

**Comment by roccx** [comment]
You could also try to present modal view controllers in the drawerContentViewController, which will result in a more or less same animation behaviour like in Apple Maps. The dim effect could be added with a `UIPresentationController`.

## Try the following example:

`drawerContentViewController.definesPresentationContext = true`

### Configure modal presentation styles
`modalViewController.modalTransitionStyle = .coverVertical`
`modalPresentationStyle.modalPresentationStyle = .currentContext`

### Present view controller modally
`drawerContentViewController.present(modalViewController, animated: true, completion: nil)`

**Comment by Archivus** [comment]
Oh wow sorry haven't been on here in a while - @mikegabriel do you still need anything? It's all very simple: just follow the steps you did to setup the first drawer and it'll work like a charm
