### ISSUE TITLE
[BUG] There is a 20 pixel top inset for the PulleyPassThroughScrollView which doesn't accept user action

### ISSUE THREAD

**Issue by gerdjikov17** [52inc/Pulley#416]
**Describe the bug**
I noticed a bug that is also reproducable while testing on the Demo app of Pulley.
On the top of the drawer content view in panel mode there is a 20 pixel untappable space. If I inspect the view it's actually +20 pixels of height more than the one I return in the partialRevealDrawerHeight for example. This I think happens because of the bounceOverflowMargin variable that is added to the frame height. It's not allowed in panel mode so maybe it's good to check if the view is in panel mode before adding it to the frame.

**To Reproduce**
 - Did you experience this behavior on in the simulator, on a physical device, or both: Both
 - Can you reproduce the behavior in the Pulley Sample/Demo App: Yes
 - Steps to reproduce the behavior in the Pulley Sample/Demo App:
1. Start the demo app
2. Inspect the UI
3. Look at PulleyPassThroughScrollView
4. See height which is 20 less than the drawer content height.

**Expected behavior**
DrawerContentView to be the actual height that is return by the delegate.

**Screenshots or Recordings**
<img width="1512" alt="Screenshot 2021-07-09 at 12 56 24" src="https://user-images.githubusercontent.com/26312893/125062080-b0370e80-e0b6-11eb-9333-5a8795c2af4d.png">

**Pulley (please complete the following information):**
 - Version: 2.9.1
 - Any customizations or tweaks: No
 - Did you Subclass: No

**Xcode (please complete the following information):**
 - Version: 12.5.1
 - Installation: On Demo app
 - Interface Builder: N/A

**iOS Devices (please complete the following information):**
 - Device: iPad Pro 12.9 5th Gen
 - OS: iOS 14.5
 - Simulator: Yes

**Comment by gerdjikov17** [comment]
I found out that this change on line 1277 fixes the visual issue. I don't know if it'll break any other functionality
<img width="1512" alt="Screenshot 2021-07-09 at 13 16 17" src="https://user-images.githubusercontent.com/26312893/125063271-f0e35780-e0b7-11eb-9932-98a9d4b215e9.png">

Result:
<img width="1512" alt="Screenshot 2021-07-09 at 13 15 57" src="https://user-images.githubusercontent.com/26312893/125063284-f50f7500-e0b7-11eb-9c21-59b89f6063cf.png">

**Comment by ulmentflam** [comment]
@gerdjikov17 Your solution should work as `.pannel` and `.compact` modes don't require the bounce overflow margin. I would be happy to merge your PR if you would like to submit your change?

**Comment by ulmentflam** [comment]
Thank you, @gerdjikov17! Your PR has been merged into the main branch!
