### ISSUE TITLE
Strange lines on mac catalyst 16

### ISSUE THREAD

**Issue by michael-mansour** [52inc/Pulley#424]
**Describe the bug**

On Mac catalyst 16, lines delimiting the view appear (see capture). Previously (on mac catalyst 15) it never appeared.

<img width="1016" alt="Screenshot 2022-10-25 at 08 24 31" src="https://user-images.githubusercontent.com/9451389/197698459-bdb2db30-9a15-4d5a-bf6a-84e98e1c9c95.png">

**Pulley (please complete the following information):**
 - Version: 2.9.1

**Xcode (please complete the following information):**
 - Version: Xcode 14.0.1 (14A400)
 - Interface Builder: Yes

**iOS Devices (please complete the following information):**
 - Device: Mac
 - OS: macOS
 - Version Ventura 13.0
 - Simulator: N/A

**Comment by danielsaidi** [comment]
We also have this. Any easy workaround that doesn't require an SDK update?
