### ISSUE TITLE
'FLT_EPSILON' is deprecated, please use 'Float.ulpdOfOne' - Swift 3.1 warning

### ISSUE THREAD

**Issue by RamblinWreck77** [52inc/Pulley#43]
Pretty much the title, should be a quick fix

**Comment by brendan09** [comment]
The fix for this has been merged, but an update hasn't been pushed to the Pod yet. If you'd like the fix now, you can clone from master.

**Comment by RamblinWreck77** [comment]
Thanks!

**Comment by brendan09** [comment]
The podspec is now updated, so this should be available by updating your podfile (rather than using master).

Let me know if you have any issues. Thanks!
