### ISSUE TITLE
Navigation Controller Support

### ISSUE THREAD

**Issue by varunananddudeja** [52inc/Pulley#45]
I am trying to set pulley view controller as a root view controller of navigation controller.  I wish to manage the extra top 44 space of bar as Drawer Container VC flows on top of bar which i don't want. Could you please help me with this?

**Comment by brendan09** [comment]
You can adjust the inset from the top of the screen in the "Open" state by setting the -topInset property on the PulleyViewController.

**Comment by varunananddudeja** [comment]
Thanks for your reply. The primary content view also stays behind the navigation bar. I want that view also to start under top layout guide.

**Comment by brendan09** [comment]
That's up to the view controller you're using as the primary content, and not something PulleyViewController will handle for you.

**Comment by varunananddudeja** [comment]
Thanks, i got it!

**Comment by brendan09** [comment]
Great! If you have any more questions, feel free to create a new issue. I'm gonna go ahead and close this one since it's resolved. :)
