### ISSUE TITLE
Background dimming not working if setting -topInset

### ISSUE THREAD

**Issue by otshenri** [52inc/Pulley#46]
First of all, great library, thanks!

I wanted the drawer to open about half way and still make the background dim/darker. I tried using .partiallyRevealed state, but it didn't dim the background. 
Then I tried using .open state and setting the -topInset value, so that the drawer would open only half way. But then the background dimming stopped working at certain values (topInset 200+) depending on device screen size.

What to do, to achieve my goal of opening the drawer to half screen and still dim the background?

**Comment by brendan09** [comment]
If I recall, the dimming is calculated between the partiallyRevealed height and the topInset. you may try setting the partial reveal height very low (and not using it as a supported position) and then using a large top inset.

I'm just speculating, but it's worth a try.

**Comment by otshenri** [comment]
Nice, it worked, thanks a lot!
