### ISSUE TITLE
Bottom layout is not correct

### ISSUE THREAD

**Issue by mukulm24** [52inc/Pulley#50]
If we render a view controller on the drawer content. The bottom layout is below the screen so the interface gets cut at the bottom of the controller's view.

**Comment by brendan09** [comment]
That's intentional. Please see the README.

**Comment by brendan09** [comment]
> Important: Drawer Content views are made 20pt too long in order to account for the bounce animation. Make sure your drawer content view is aware that the bottom 20pts will be offscreen.

**Comment by mukulm24** [comment]
Can we modify that? Do we have a property in the library to change?

**Comment by brendan09** [comment]
No, it can't be modified. If it was reduced you'd see an edge appear when the bounce animation occurs. Your drawer VC just needs to be built with 20pt margins to the bottom. If you don't want to include it in your VC layout, you can have a parent VC that accounts for the margin and shows your VC as a child VC (inset from the bottom by 20). The alternative is that you get a really terrible cut-off showing during the drawer open / close animations.
