### ISSUE TITLE
 need to stop one gesture

### ISSUE THREAD

**Issue by QiuZhiFei** [52inc/Pulley#53]
The Apple Maps bottomView handles transitioning from the pan gesture to the scroll view scroll gesture in one smooth motion.  the user doesn't need to stop one gesture and start a new one in order to start scrolling the view.

**Comment by brendan09** [comment]
Unfortunately, that requires lower level access to UITableView and it’s gestures than UIKit publicly provides. It’s been explored by a handful of people, with no success. 

If you find a way to do it, I’d be happy to take a look, but as far as I know the closest someone has gotten involved disabling bouncing on the table view.

**Comment by QiuZhiFei** [comment]
Google maps have similar effects, i don't think that is a private API, i will continue to try, thx
