### ISSUE TITLE
drawer content stations bellow lowest stop

### ISSUE THREAD

**Issue by Raiden9000** [52inc/Pulley#54]
Summary:

The drawer is dropping and staying below where it is supposed to go.
When I start the app, the drawer is in the right position, but when I move the pulley up, let go, and then down all the way, it shows less than when it started.

What it should do:

The pulley should get back to the original position.

Details:

collapsedDrawerHeight = partialRevealDrawerHeight
and
supportedDrawerPositions = PulleyPosition.all

**Comment by brendan09** [comment]
> collapsedDrawerHeight = partialRevealDrawerHeight

This is not a supported setting.

There is math that relies on these numbers not being the same. If you don't need separate positions for collapsed and partial reveal, then use a supportedDrawerPositions array that omits the partial reveal position.

**Comment by Raiden9000** [comment]
I have tried 

collapsed position = X
partialRevealDrawerHeight = X + 1

supportedDrawerPositions = [PulleyPosition.collapsed,PulleyPosition.open]

and I still see the problem.

I have added a short video to show it:
https://youtu.be/RmiaGqME4SM

*Note, I am not using a TabController. I am using a tabbar on a normal UIViewController, so they have no interaction, one is simply on top of the other. I set the collapsed slider position to be 49 * 2.3 (49 is the size of the tabbar) so it can show.

**Comment by brendan09** [comment]
Can you test the code compiled against the iOS 10 SDK, running in an iOS 10 simulator? That looks like iOS 11, which has changed a lot of how layout guides and margins work. Pulley isn't currently ready to be built with the iOS 11 SDK.

**Comment by brendan09** [comment]
If it still happens on iOS 10, please provide a sample project and I'll see if I can figure out what it's doing and/or how to work around it.

**Comment by Raiden9000** [comment]
I see.

I can't go back to iOS 10, I tried and i had other issues I did not want to take care of. This is just a pet project. I will wait for this to be updated then, or I will attempt to fix if I have time.

Thank you though. I really like your slider, i've used several others and I will keep this one.

**Comment by Raiden9000** [comment]
I deployed on iOS 10.3 and yes, it works in that it doesn't go all the way to the bottom now.

Something else I noticed, even on 10.3, is that I am able to move the drawer from the mainContentVC.
So even though I am not touching the drawer I am able to move it up and down, and I can't move the tableView cells behind it.

**Comment by brendan09** [comment]
Good to hear it works properly (regarding the bottom) on 10.3 for you.

Try the demo project and see if there are any significant differences in your implementation. The demo project has a scrollable map behind it, and it scrolls without affecting the drawer. A tableview, etc. should scroll normally behind the drawer.

**Comment by Raiden9000** [comment]
Alright, so I see it doesn't like having the pulleycontroller not be the root view controller.
Setting it as root and it works, but now I need to add the tabbar into that view.

So here I have code to setup the pulley with a tabBar. I know someone had mentioned they wanted it in one of the resolved issues.

I subclassed PulleyViewController.swift as follows:

`
class PulleyTabBarController: PulleyViewController, UITabBarDelegate{
    var tabBar : UITabBar!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //ADD TABBAR--------------------------------------
        tabBar = UITabBar()
        tabBar.delegate = self
        tabBar.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(tabBar)
        NSLayoutConstraint.activate([
            tabBar.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            tabBar.trailingAnchor.constraint(equalTo: view.trailingAnchor),
            tabBar.bottomAnchor.constraint(equalTo: view.bottomAnchor)
            ])
        
        //ADD TABS-----------------------------------------
        let icon0 = UITabBarItem(title: "", image: UIImage(named: "homeIcon"), tag: 1)
        icon0.imageInsets = UIEdgeInsetsMake(0.5, 0, -0.5, 0)
        icon0.title = nil
        let icon1 = UITabBarItem(title: "", image: UIImage(named: "tabLibrary"), tag: 2)
        icon1.imageInsets = UIEdgeInsetsMake(0.5, 0, -0.5, 0)
        icon1.title = nil
        let icon2 = UITabBarItem(title: "", image: UIImage(named: "tabSearch"), tag: 2)
        icon2.imageInsets = UIEdgeInsetsMake(0.5, 0, -0.5, 0)
        icon2.title = nil
        let icon3 = UITabBarItem(title: "", image: UIImage(named: "tabSettings"), tag: 2)
        icon3.imageInsets = UIEdgeInsetsMake(0.5, 0, -0.5, 0)
        icon3.title = nil
        tabBar.items = [icon0, icon1, icon2, icon3]
        tabBar.selectedItem = icon0
    }
    
    public func tabBar(_ tabBar: UITabBar, didSelect item: UITabBarItem) {
        
        if tabBar.items?.index(of: item) == 0
        {
            print("Home tab selected")
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "switchingTabs"), object: 0)
            
        }
        else if tabBar.items?.index(of: item) == 1{
            print("Library tab selected")
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "switchingTabs"), object: 1)
        }
        else if tabBar.items?.index(of: item) == 2{
            print("Search tab selected")
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "switchingTabs"), object: 1)
        }
        else if tabBar.items?.index(of: item) == 3{
            print("Settings tab selected")
            NotificationCenter.default.post(name: NSNotification.Name(rawValue: "switchingTabs"), object: 1)
        }
    }
}
`

Then I have a ContainerView.swift file that switches the views for the tab. This container view is setup as the mainViewController for the pulley. Not fully implemented yet, but a start for someone.

`override func viewDidLoad() {
NotificationCenter.default.addObserver(self, selector: #selector(ContainerView.switchController(notification:)), name: Notification.Name(rawValue: "switchingTabs"), object: nil)

    func switchController(notification : NSNotification){
        let index = notification.object as! Int
        if index == 0{
            
        }
        else if index == 1{
            
        }
        else if index == 2{
            
        }
        else if index == 3{
            
        }
}`
