### ISSUE TITLE
Wrong drawer frame animation when switching drawer content view controller

### ISSUE THREAD

**Issue by roccx** [52inc/Pulley#55]
I have an issue with the animations when I call the 
`setDrawerContentViewController(controller:animated:)` 
method to switch drawer content view controllers.

The new content view controller has a initial frame of size `.zero` in the transition animation and is scaling up to the target layout.

Could it be possible that the `PulleyViewController` is accidentally animating the relayout of the view controller?

**Comment by brendan09** [comment]
PR is merged.

If you pass animated: true, then it'll animate the layout. It shouldn't if you pass 'false'.

**Comment by brendan09** [comment]
It looks like this occurs on iOS 11, but not iOS 10. I'm currently looking into the issue on iOS 11.

**Comment by brendan09** [comment]
@roccx Please try the swift-4 branch. It includes a full fix for the animation issue I replicated on iOS 11. If that doesn't fix it for you, please reopen the issue.
