### ISSUE TITLE
[Proposal] PulleyDrawerViewControllerDelegate methods should be all optional

### ISSUE THREAD

**Issue by zntfdr** [52inc/Pulley#57]
Hi everyone!
Thank you for making this quite useful library.

I've played with it and I believe that any class that would like to conform to ``PulleyDrawerViewControllerDelegate `` should not have to implement all the protocol functions.

It's simple to look into the source code and find what the default implementation for each methods is:
````swift
extension MyClass: PulleyDrawerViewControllerDelegate {
  func collapsedDrawerHeight() -> CGFloat {
    let kPulleyDefaultCollapsedHeight: CGFloat = 68.0
    return kPulleyDefaultCollapsedHeight
  }
  
  func partialRevealDrawerHeight() -> CGFloat {
    let kPulleyDefaultPartialRevealHeight: CGFloat = 264.0
    return kPulleyDefaultPartialRevealHeight
  }
  
  func supportedDrawerPositions() -> [PulleyPosition] {
    return PulleyPosition.all
  }
}
````

Still, I believe that if I wanted to change only the behavior of ``collapsedDrawerHeight()`` for example, I should be able to do just that.

This is just my opinion/suggestion, please feel free to dismiss it if it's not in line with your library development. 😄 

Cheers,
Federico

**Comment by brendan09** [comment]
Unfortunately, this delegate uses an array of an enum type (PulleyPosition), and arrays of enums can’t bridge to Objective-C. This means that the PulleyViewControllerDelegate can’t use the @objc tag, which is required to make it optional.

**Comment by zntfdr** [comment]
Hi @brendan09!
Thanks for the clarification, I completely understand 😊 

Cheers!
Federico
