### ISSUE TITLE
How to overlay a view on top of BOTH drawer and primary containers?

### ISSUE THREAD

**Issue by ivanmkc** [52inc/Pulley#58]
Great work with Pulley!

I have a view that lies above both the primary and drawer container views in my Storyboard.

However, at run-time, the view appears underneath (in the  view debugger) the containers, so I can't see them.

Is there any way to achieve this?

Thanks!

**Comment by brendan09** [comment]
Sure. So, I want to start by mentioning that using Pulley in Storyboards is a _bit_ of a hack. The view hierarchy in Storyboards doesn’t actually match what Pulley rebuilds internally, so I’m not surprised it doesn’t behave well in that circumstance.

But, there is a solution! You want to make a new view controller with a full screen container view, then use an embed segue with that container view to embed the Pulley View Controller that you have into that view controller. In that new parent view controller, you can put a view on top of the container view the Pulley VC is embedded in, and it should work properly.

If that wasn’t clear, let me know and I’ll make a quick sample project showing it.

Thanks!

**Comment by ShawnBaek** [comment]
@brendan09 Could you sending or updating sample project?

**Comment by brendan09** [comment]
Here is a zip file containing a sample project that does this: https://www.dropbox.com/s/hurzxag6tx64zbp/Pulley-Floating%20Content.zip?dl=0

It's done in the Storyboard, using a Container View in the new initial view controller I've added to the Storyboard. Anything 'above' the container view in that view controller will 'float' over the drawer. Be careful: Anything that is user interactive (for example a large UIView) will steal touches, even if it's transparent, unless you disable user interaction on the view. You obviously need user interaction enabled on controls, but I'd recommend disabling it on anything not essential. Reminder: If you disable user interaction on a view _containing_ controls then the controls will be disabled as well.

Let me know if you have any questions.

@ShawnBaek @ivanmkc

**Comment by ShawnBaek** [comment]
Hi, Thank you very much.

It really helps me a lot

Have a good day :)

나의 iPhone에서 보냄

2018. 2. 8. 오전 8:29, Brendan Lee <notifications@github.com> 작성:
