### ISSUE TITLE
How to enable scrolling in UITableView table when the content fits on the screen

### ISSUE THREAD

**Issue by mrfer** [52inc/Pulley#62]
Please help with the question.
This situation, when I open the DrawerViewController in the state .open, then scrolling is disabled, if the number of cells can fit into the screen sizes. And accordingly I can not catch the event here:

func scrollViewDidScroll(_ scrollView: UIScrollView) {
        self.searchBar.setShowsCancelButton(false, animated: false)
}

**Comment by brendan09** [comment]
Unfortunately, that’s how scrollviews embedded inside of other scrollviews works on iOS.

Your best option would be to find another place where you could call that line of code.
