### ISSUE TITLE
Access primaryContentViewController on prepare(for segue: UIStoryboardSegue, sender: Any?)

### ISSUE THREAD

**Issue by ivanicspeter92** [52inc/Pulley#66]
Hey! I would like to access the primaryContentViewController of the PulleyViewController because I would like to pass some data over to the view. This should be done on the `prepare(for segue: UIStoryboardSegue, sender: Any?)` method of the viewcontroller class, which presents Pulley modally (set up on storyboard).

I am facing the problem that the primaryContentViewController object on the appearing segue destination is nil and therefore I cannot pass data to it. Is there a way to get over this issue? I tried the same thing programmatically as well with no success. Here is my code (of the former attempt):

```
class MyVC: UIViewController {
    @IBOutlet weak var textfield: UITextField!
    
    @IBAction func tapped(_ sender: Any) {
        performSegue(withIdentifier: "toPulley", sender: textfield.text)
    }
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let primaryContentVC = ((segue.destination as? PulleyViewController)?.primaryContentViewController as? PrimaryContentViewController), let data = sender as? String {
            primaryContentVC.data = data
        }
    }
}
```

**Comment by brendan09** [comment]
Try calling “loadViewIfNeeded()” on pulley before you try to get that primary content view controller. It’ll make sure that all the embed segues in the storyboard have been processed.

**Comment by ivanicspeter92** [comment]
Thanks, it did the trick! Maybe it would be good to add this information to the readme, as it is not so self-evident. Cheers!
