### ISSUE TITLE
Problems conforming to delegates after update to 1.5.1 from 1.4

### ISSUE THREAD

**Issue by ivanmkc** [52inc/Pulley#67]
Hi,

I used updated to 1.5.1 and it broke my build.

<img width="1046" alt="screen shot 2017-08-17 at 10 01 00 am" src="https://user-images.githubusercontent.com/1586049/29404482-074f0b2c-8333-11e7-9327-f733763b7bf6.png">

This worked fine in 1.4. I've tried fixing by following it the XCode suggestions such as adding override or extending from PulleyPrimaryContentControllerDelegate instead but nothing I do works.

Thanks!

**Comment by brendan09** [comment]
Hello, the problem is that you’re implementing that protocol twice for that class. Make sure you only implement it once, and only say you’re implementing it once (either on the class creation, or on the extension creation, but not both).

**Comment by ivanmkc** [comment]
The problem appeared only after I updated to 1.5.1. The same code worked in 1.4.

**Comment by brendan09** [comment]
Yes, I understand. However, protocol inheritance changed some in (1.5.1). The error you’re receiving is that you’re marking your class as confirming to the same protocol twice. Patch releases X.X.1 will maintain compatibility, however point updates (X.1.X) may introduce compatibility issues, in this case with protocol inheritance. 

You’ll need to update your code to work with the new version, or specific ~1.4 as the version for Pulley in your Podfile.

**Comment by ivanmkc** [comment]
Ok I see, will take a look.

**Comment by brendan09** [comment]
No problem: When you take a look, I’d see if you’re implementing 2 Pulley protocols on the same class. (Even if they’re different) it’s possible that one of them inherits from the other now, so marking that you implement it isn’t necessary anymore.
