### ISSUE TITLE
Drawer Persists on screen after performing segue to another view.

### ISSUE THREAD

**Issue by alexjessecole** [52inc/Pulley#69]
My app has a the Pully Drawer incorporated but from the background content view controller when I perform a segue to a separate View controller the drawer remains on the screen of the new view controller. Am I doing something wrong or is this an issue?

**Comment by brendan09** [comment]
Depending on your setup, this could be a few things:

If your primary content VC is a navigation controller, and you’re pushing VCs inside of it, then the drawer will remain over it. If you don’t want that to happen, don’t put the navigation controller as the main content VC. 

Depending on your setup, you may need to have the segue on the Pulley VC itself and call the Pulley VC to segue.

If you’re doing a modal presentation, you can try changing its presentation style to “over fullscreen”.

**Comment by alexjessecole** [comment]
Thanks for the quick response so you were correct, my primary content VC was a navigation controller. Once I removed the navigation controller it all worked. I suppose this issue can be closed unless there is a way to keep the navigation controller?

**Comment by brendan09** [comment]
You can keep it, you’ll just need to put Pulley in the navigation controller, rather than the navigation controller in Pulley like you had it.

**Comment by alexjessecole** [comment]
Ah that works perfect! Thank you very much.
