### ISSUE TITLE
Custom UIControl gesture in Drawer

### ISSUE THREAD

**Issue by PomepuyN** [52inc/Pulley#71]
Here is my hierarchy:
```
PulleyDrawerViewController
  |
  --- MyController
           |
           --- UIScollview
                   |
                   ---UIStackView
                          |
                          --- custom UIControl listening for vertical gesture
```

The issue is that whenever I try to start the UIControl gesture, my ScrollView scroll is triggered. So I excluded my UIcontrols by overriding `touchesShouldCancel`for my UIScrollView. Now it works great when my scrollview is scrolled, but when not, the gesture is passed to Pulley's internal scrollview (that is private as you said in an other issue).
Do I have to fork / manual import the project to be able to modify the internal scrollview behavior or do you see anything else I can do to manage this case?

**Comment by brendan09** [comment]
@PomepuyN You should be able to accomplish this by implementing the delegate method `gestureRecognizer(_:shouldRequireFailureOf:)` for your custom UIControl gesture recognizer. You can return 'true' anytime this method is called for your gesture recognizer (or only sometimes, depending on your needs). This will make sure that other gesture recognizers (including those in Pulley's scrollview) don't interfere with your custom control.

https://developer.apple.com/documentation/uikit/uigesturerecognizerdelegate/1624229-gesturerecognizer

**Comment by PomepuyN** [comment]
Hi,
First thanks for the answer and sorry if my questions seem dumb (I'm pretty new to iOS development).
I am not really sure how to do that. My UIControl in fact uses `beginTracking`, `continueTracking`, `endTracking` and does not have a gesture recognizer attached.
By default, `UIControl` doesn't implement it and I am not sure how to add a `UIGestureRecognizer` to my control.
I can provide you a sample / source file Monday if you prefer.

**Comment by brendan09** [comment]
Ah, I see. Since that's a pretty specific behavior / implementation choice, you'll need to fork or manually import the project to make those changes if you want to continue tracking custom gestures in that way. If possible, I'd recommend considering if an existing UIGestureRecognizer subclass (or a custom one) could accomplish the same thing. This would allow you to use the delegate methods I described before.

**Comment by PomepuyN** [comment]
I finally chose to replace `beginTracking`, `continueTracking`, `endTracking` with two gesture recognizers as you advised (Pan and Tap for my needs) and it's working well now.  
I didn't even had to implement `gestureRecognizer(_:shouldRequireFailureOf:)`or even extend `UIScrollView` to set a custom behavior.
Thanks a lot for your help.

**Comment by brendan09** [comment]
Glad it worked for you! Happy to help.
