### ISSUE TITLE
Manual/programmatically change drawerPosition

### ISSUE THREAD

**Issue by Brain2success** [52inc/Pulley#72]
First of all thanks for the great work!!!

I want to mimic the iOS maps animation. If the drawer is in collapsed stated and you tab on the search bar the drawer goes automatically to the open state. 

How can I accomplish this?

I know in which function I should write it, but what code do I have to use?

**Comment by brendan09** [comment]
The example project does this, so you can look there for an example. The magic happens in DrawerContentViewController in the sample project, in the method: searchBarTextDidBeginEditing.

**Comment by Brain2success** [comment]
😊 Thank you so much! Totally missed that. Problem solved.
