### ISSUE TITLE
Any ideas on how to make the drawer view transparent/opacity (like the iOS map)?

### ISSUE THREAD

**Issue by ruilunli** [52inc/Pulley#73]
on the iOS map, the drawer view is a  a little transparent over the primary map view. Since the drawer view is view controller, is it possible to change the opacity of drawer VC?

**Comment by brendan09** [comment]
Unless you're using an 'older' iOS device, Maps does a slightly translucent (blurred see-through) effect. The Pulley demo project does this same effect, using UIVisualEffectView.

The drawer view controller is provided by the developer, so you can do whatever you want with it. However, Pulley adds a shadow...transparent things will be affected by that.
