### ISSUE TITLE
Can we modify drawerContentContainerView like below image 

### ISSUE THREAD

**Issue by ravikanthatstoryboard** [52inc/Pulley#77]
Can we design drawerContentContainerView 

> let rect = CGRect(x: progValue, y: 0, width: self.view.frame.size.width , height: self.view.frame.size.height)
> drawerContentContainerView.frame = rect
> 

Once we go top ,its should be come be full screen .

![drawercontentcontainerview](https://user-images.githubusercontent.com/19217975/30587801-144764b2-9d52-11e7-917c-f8d0e3c2fcac.png)

**Comment by sadanro100** [comment]
How did you get the drawer to have those margins on the sides?

**Comment by brendan09** [comment]
@sadanro100 That was a screenshot not taken from a product using Pulley. If you’d some tips on accomplishing an inset, please create a new issue and I’ll be happy to provide some guidance there. Thanks!

**Comment by sadanro100** [comment]
Doing that now! Thank you very much!
