### ISSUE TITLE
Possibility to disable certain states for the drawer

### ISSUE THREAD

**Issue by Alex293** [52inc/Pulley#8]
All is in the title :)

Nice work anyway i love using it !

My goal is to disable the full size for some drawers. I think the drawer delegate is the place to do this.

**Comment by brendan09** [comment]
Good suggestion! I'll look into it later today.

**Comment by brendan09** [comment]
@Alex293 Hello! I have a branch supporting the feature you've requested. It allows you to disable any of the 3 drawer state (or lock it to 1 specific one).

Please give it a try and let me know what you think. It should be stable, but it could use more testing before I merge it into master. 

Let me know if it works for your use case. I've updated the docs on that branch to include a message about how to use it. (Item 3 in the list at the bottom). If you have questions, feel free to post them here and I'll try to answer them the best I can. The example project is updated to support the feature as well.

Branch: https://github.com/52inc/Pulley/tree/feature/supported-drawer-stops

Thanks!

**Comment by Alex293** [comment]
Sorry for answering only now this is perfect, no bug for now. I'm closing this but I'll report any bugs here !
