### ISSUE TITLE
Swift 4 Support?

### ISSUE THREAD

**Issue by RamblinWreck77** [52inc/Pulley#80]
Hello! Can we get a quick update for xcode9/swift4 support?

It looks like all the library needs is a few auto-correct fixes. I can PR them if you like, but they should be super fast either way.

**Comment by brendan09** [comment]
@RamblinWreck77 Swift 4 support is now up on CocoaPods and on master. However, because it introduces support for Safe Areas, it is a breaking change that will require some small API changes.
