### ISSUE TITLE
iOS 11 / Swift 4 / Safe Areas Migration Discussion

### ISSUE THREAD

**Issue by brendan09** [52inc/Pulley#82]
Hello everyone!

I recently pushed Pulley 2.0 to CocoaPods, with support for Swift 4, Safe Areas, and the iPhone X. This required some breaking API changes to Pulley. Luckily, they weren't very big.

**As @funkenstrahlen mentioned below, most of the delegate methods have changed.** Xcode may not automatically tell you about this, so definitely take a look at the updated delegate method signatures and the new 'bottomSafeArea' parameter they pass you.

Please checkout the iOS 11 / Safe Area section in the updated README if you haven't already.

If you have problems / questions, please ask them in this thread and I'll try to help you the best I can.

Thanks!

**Comment by funkenstrahlen** [comment]
I just tried this and it works perfectly for me. Thank you a lot for all the time and effort you put into this!  😊

**Comment by drewpitchford** [comment]
@brendan09  Seeing a compile error with Swift 4 for PulleyViewController. Looks like a #selector method isn't exposed to ObjC.
![screen shot 2017-09-26 at 11 13 25 am](https://user-images.githubusercontent.com/12616043/30871262-d669a79a-a2ab-11e7-8f01-ec17e20cc80d.png)

**Comment by brendan09** [comment]
@drewpitchford The official Swift 4 version is v2.0 on CocoaPods (master branch). Please try using that and report back if you have issues.

**Comment by drewpitchford** [comment]
@brendan09  Thanks. I forgot to run pod repo update, hence it wasn't pulling 2.0.

**Comment by brendan09** [comment]
@drewpitchford No problem! I’ve heard some mixed reports on it compiling properly, so if you have any issue at all please let me know. Hoping to iron out any kinks that weren’t found in the sample projects ASAP.

**Comment by funkenstrahlen** [comment]
I just discovered a migration issue someone else might also run into.

My code did implement `func drawerPositionDidChange(drawer: PulleyViewController` delegate method.

I was wondering why it did not get called after upgrading to `2.0`. Xcode did not warn me that this delegate method does not exist any more and has been renamed to: `func drawerPositionDidChange(drawer: PulleyViewController, bottomSafeArea: CGFloat)`

This is no bug. Just leaving this here in case someone else is going to migrate and has this issue too.

**Comment by skeeJay** [comment]
After updating to Pulley `2.0`, the inset of the drawer in `.opened` mode looks correct to me. But when it is fully `.opened`, the background visual effect (and indeed, all the content of the drawer) looks like it is cut off about 20pts from the bottom of the screen within the drawer, even though the content like this table is fixed to the bottom of the drawer view. Is this something I need to adjust for manually?

![simulator screen shot - iphone x - 2017-10-01 at 02 26 15](https://user-images.githubusercontent.com/506096/31054748-b3826bb0-a687-11e7-98db-3e3533202667.png)

**Comment by brendan09** [comment]
The drawer view should extend 20 points below the bottom of the screen. Is this what you’re seeing? If so, that’s intentional (and mentioned in the README). It’s there so that when the drawer “bounces” you don’t see the bottom edge of the drawer.

If your seeing something else, please verify the same issue exists in the sample project (or create a demo with the problem) and I’ll take a look.

**Comment by skeeJay** [comment]
Was able to resolve my issue, which stemmed from the interplay of having the whole Pulley controller within another container......worked fine before Safe Area but needed adjustment after. Taking me some time to adapt to the Safe Area concept. But Pulley seems to be working as expected, so no concern there.....thanks for the help.

**Comment by brendan09** [comment]
Great! Glad to hear. Let me know if you encounter any issues.

**Comment by CareerFairPlus** [comment]
My apologies if I missed a step somewhere, but every time I run `pod install` the Pulley package that gets installed is set to use Swift v3.2, and then I have to manually change it to 4.0 to build properly.  According to Cocoapods I have Pulley v2.0 installed.

What am I doing wrong?
