### ISSUE TITLE
'getBottomSafeArea' is inaccessible due to 'private' protection level

### ISSUE THREAD

**Issue by eciftcioglu** [52inc/Pulley#83]
I am getting 13 errors of this type in PulleyViewController after installing via cocoapods.

**Comment by brendan09** [comment]
Ok, I’ll take a look at this today. Are you using Xcode 9?

**Comment by brendan09** [comment]
There’s at least 1 other report of this working for someone else (and it works in the sample project). If you can provide more info on what version of Xcode you’re using to build, and any other relevant info, I can help you get it resolved quickly.

Thanks!

**Comment by brendan09** [comment]
@eciftcioglu It looks like you're trying to compile it with Swift 3.x. Swift 4 changed how the private keyword works, and Pulley 2.0 relies on that behavior. You'll need to use Swift 4 and Xcode 9 for Pulley 2.0 to work for you.

Older versions of Pulley are available for previous versions of Swift, on branches. Let me know if you have any questions.

Thanks!

**Comment by eciftcioglu** [comment]
Thanks for the quick response. I'm using xcode9 but the swift version was unspecified. I'm going to try it by setting it to swift 4. I'll let you know. Thanks.

**Comment by brendan09** [comment]
@eciftcioglu Just checking in to see if your issue was resolved.

**Comment by eciftcioglu** [comment]
Yes no problem. I was somehow pulling the old version. Works like a charm.Thank you!

**Comment by charlag** [comment]
Hello, thanks for the awesome library!
We have this issue in our Swift 3 project and we need iPhone X support so we cannot use the old library version. The project is quite big and uses many libraries so we cannot move to the new Swift version immediately. Is it a possibility to make some methods in extensions non-private to maintain compatibility with both Swift versions? I think is relatively low. Thanks in advance.

**Comment by brendan09** [comment]
As long as you’re using Xcode 9, you can use Swift 4 CocoaPods in a Swift 3 project without issue. You’ll just need to update to the latest version of Pulley and make sure the Pulley target is set to use Swift 4. (This can be done with a post_install hook in your Podfile).

Changes won’t be made to Pulley to support Swift 3 (especially since Xcode 9 can support both Swift 3 and Swift 4 in the same project).

**Comment by charlag** [comment]
But then we have to switch all the pods to Swift 4 as well, if I understand correctly?

**Comment by brendan09** [comment]
You don’t have to switch all pods to Swift 4. You can use Swift 4 in only specific pods.

Checkout this StackOverflow answer for an example post_install hook that marks Swift 4 pods as using Swift 4. That will allow them to compile properly. 

https://stackoverflow.com/questions/46101625/using-cocoapods-mixed-swift3-and-swift4-pods

**Comment by charlag** [comment]
Wow, that's awesome!
Sorry for these stupid questions, I am not an iOS developer anymore but I help another developer so I've missed some things.
Thanks a lot!
