### ISSUE TITLE
Scroll View on DrawerContentViewController not working

### ISSUE THREAD

**Issue by felstell** [52inc/Pulley#85]
Hello, guys! Thanks for the your library! 

I have a one trouble. I was added scroll view on a DrawerContentViewController, but he not scroll. 
How i can enable scrolling on a DrawerContentViewController? What i need to do? 

And thanks for your work again!

**Comment by brendan09** [comment]
Scrollviews should work fine in Pulley (the sample project uses a tableview, for example). 

Make sure your scroll view is configured properly and has a contentSize large enough that scrolling will be enabled.

It also important to keep in mind that your drawer VC doesn’t resize based on what’s visible on screen, rather it’s always it’s largest size and simply moved up and down. If your scroll view frame is larger than the contentSize you have, it won’t scroll.

**Comment by felstell** [comment]
<img width="1123" alt="2017-09-29 10 53 37" src="https://user-images.githubusercontent.com/8091787/31007231-87cf941e-a508-11e7-8c31-b8905c45f5de.png">

I was added some indentation from border of View. Not working.

**Comment by brendan09** [comment]
Indenting the label from the edge of the view won't indent the drawer on Pulley.

However, your view constraints / drawer setup are outside the scope of what Pulley manages. You'll need to determine what isn't working correctly for your constraints.

Without seeing a screenshot or video of it running, there's unfortunately nothing I can do to answer your question.

Judging by your design, it's also important to keep in mind that the size of the container views / view controllers used for Pulley are _not_ respected. The primary one will always be full screen, and the drawer one will always be the height of the "tallest" position it can be in + 20pts.

**Comment by felstell** [comment]
This is screenshot of screen when drawerViewController is close
![simulator screen shot - iphone 8 - 2017-10-02 at 13 25 17](https://user-images.githubusercontent.com/8091787/31073596-40fe1a6e-a775-11e7-83a7-80077c7e2703.png)

...and this is screenshot when he is open 
![simulator screen shot - iphone 8 - 2017-10-02 at 13 25 19](https://user-images.githubusercontent.com/8091787/31073611-51e1ecb6-a775-11e7-8ea9-670e47ac773c.png)

I hope this screenshots will help you to understand my problem.
Scroll don't work of any position. I don't know what i doing wrong, and i don't understand what a problem with this design. Maybe you have some idea?

**Comment by felstell** [comment]
Oh. i'm sorry. That was my fault.

I was find conflict of any constraint, delete some of they, and now your library working correctly and fine.

Sorry for this. And thank you for your work)
