### ISSUE TITLE
Closing/Opening Pulley From Primary Content View Controller?

### ISSUE THREAD

**Issue by Henry-** [52inc/Pulley#88]
So when a user leaves the primary content I need the pulley to close, but calling PulleyPosition.closed in viewWillDisappear does not work and remains uncalled.

**Comment by brendan09** [comment]
To close the drawer, you can't just just invoke the enum. You'll need to use the `setDrawerPosition` API on Pulley, and have .closed as an allowed position for your drawer.

Using your reference to the Pulley view controller:

     pulleyVC.setDrawerPosition(position: .closed, animated: true, completion: nil)

If you don't have a reference to the Pulley VC, you can use this in your content VC:

     let pulleyVC = (self.super as? PulleyViewController)

You can then use the first line of code (you'll need to alter it to treat pulleyVC as an optional).

**Comment by brendan09** [comment]
@Henry- Just checking in to see if this solved your issue, or if you have any other questions.

**Comment by Henry-** [comment]
I was wondering if it was possible for me to set the pulley position to closed from code within the primaryContentViewController. 
Putting
` let pulleyVC = (self.super as? PulleyViewController)`
does not seem to work and gives me 

> Value of type '(NSObject) -> () -> PrimaryContentViewController' has no member 'super'

**Comment by Henry-** [comment]
![screen shot 2017-10-13 at 4 53 35 pm](https://user-images.githubusercontent.com/9007957/31566085-1e681002-b037-11e7-904e-bb7132731849.png)
Here is a screenshot of where I called the pulleyVC. I'm confused as well as this should work?

**Comment by brendan09** [comment]
Unfortunately that won't work, as you can't use 'self' or any of it's properties before initialization.

In addition, you don't want to keep a non-weak property referencing the Pulley view controller or you'll create a retain cycle that will cause memory leaks.

Inside of an IBAction (or anytime you want to change the drawer position) use the snippet I gave you verbatim. So, inside of a function you could do:

     (self.super as? PulleyViewController)?.setDrawerPosition(position: .closed, animated: true, completion: nil)

Whenever you want to close the drawer.

**Comment by brendan09** [comment]
@Henry- Just checking in to see if you resolved your issue. Let me know if you have any questions.
