### ISSUE TITLE
New drawer pop up animation

### ISSUE THREAD

**Issue by kiliankoe** [52inc/Pulley#89]
I absolutely ❤️ this library, thank you so much for creating/maintaining it! It's been a joy to integrate and makes my app so much more fitting with current iOS design.

I am wondering however what the best way would to be to copy Apple Maps' UI of popping a new drawer over an existing one? My app works relatively similar to Maps.app in that I have places that can be selected and their detail views are then shown in the drawer. Currently this crossfades in like described in the readme, but if at all possible I'd love to recreate Apple's animation.

Thanks in advance! 😊

**Comment by brendan09** [comment]
Thanks for the kind words!

Someone managed to recreate this effect (seemingly with good success), but I haven't tried it myself.

Here is what they did:

     drawerContentViewController.definesPresentationContext = true

Configure modal presentation styles for the new VC you want to show:

     modalViewController.modalTransitionStyle = .coverVertical
     modalViewController.modalPresentationStyle = .currentContext

Present view controller from the drawer VC:

     drawerContentViewController.present(modalViewController, animated: true, completion: nil)

They also rounded the top corners of their new VC so it looked like a card.

Let me know if this works for you!

**Comment by brendan09** [comment]
@kiliankoe Just checking in: Did this work for you? If so, I'm going to go ahead and close this issue.

**Comment by kiliankoe** [comment]
I had some issues, but I believe they were on my part. Need to play around with this a bit more, but thanks for your help! Should've gotten back to you on this, sorry about that.

But this can definitely be closed for now. If I have some issues I can't work around, I'll still be able to comment here 😊

**Comment by brendan09** [comment]
Sounds good!

**Comment by ethansinjin** [comment]
This is great!

Something I ran into while using this solution: If you set the presentation style of the first "nested" view controller to `.currentContext`, when dismissing it, the PulleyViewController's drawerViewController will be nil, resulting in an empty drawer.

In order to solve this issue, the `modalPresentationStyle` of the first view controller should be `.overCurrentContext`. Further nested VCs should be `.currentContext`.

**Comment by appsird** [comment]
Here is what I did:

- create a new container class in Main.storyboard
- create a new MarkerViewController class and assign to the embed VC
- assign an identifier to the new ViewController
- added the following lines to the DrawerContentViewController viewDidLoad:

         self.definesPresentationContext = true
        let markerView = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MarkerViewController")
        markerView.modalTransitionStyle = .coverVertical
        markerView.modalPresentationStyle = .currentContext    
        self.present(markerView, animated: true, completion: nil)
__

when running, no error, though nothing presented. I can forward the project as-is if needed

Would be extremely grateful if a fork is provided with this view integrated.

**Comment by brendan09** [comment]
You should present it from the existing drawer view controller, in response to a button press or other event.

You can’t do it in viewDidLoad, as the view / controller aren’t yet in the hierarchy.

A fork / Pulley customization isn’t necesssary to accomplish this, as it can be done with UIKit fairly simply. As a result, Pulley won’t be adding special functionality to support this. It’s a bit beyond the scope / goal of Pulley.

**Comment by appsird** [comment]
As per prior posting, the code was placed in runPrimaryContentTransition in response to the (+) button press for testing. as stated, this presents the view. though not a shorter view form used by Maps.

You mentioned prior:

>They also rounded the top corners of their new VC so it looked like a card.
 
So, these users must be somehow using a non-full view to achieve the desired effect. Any tips welcome.

**Comment by brendan09** [comment]
In order for the view to only fill the space of the drawer, you need to put this line in your drawerViewController (not the marker one):

‘self.definesPresentationContext = true’

**Comment by appsird** [comment]
Thanks much for the tips. Have this working now, effectively shares the current drawerViewController.
