### ISSUE TITLE
iPad support planned?

### ISSUE THREAD

**Issue by jwarhurst** [52inc/Pulley#94]
Hello, I was wondering if you've looked into iPad support. With large screen it floats the menu over the left side of the screen in Apple Maps.

**Comment by brendan09** [comment]
Hello, iPad support isn't currently planned. Some people _have_ used Pulley to recreate that floating menu, but it's something not officially supported by Pulley.

**Comment by akac** [comment]
To be fair, landscape on X is the same as iPad - so perhaps that should make the issue a higher priority :)

**Comment by brendan09** [comment]
@jwarhurst @akac  The master branch now includes support for this, in the form of mimicking the iPad Maps layout. It's not _identical_ to Maps, but it's fairly close and tweaking the options can probably get you the rest of the way there. (iPhone landscape, specifically, is different...but customizations by your drawer VC could likely make it work identically if that's a goal)

Right now it's more of a 'test' version, as it required a lot of changes. It should work, but I'm not confident enough to push it out to everyone yet. If you feel like giving it a try, I'm looking for feedback / bug-testing before pushing it out to CocoaPods. 

Looking forward to any feedback you may have. Thanks!

**Comment by brendan09** [comment]
Just dropping a quick note before I close this issue:

Version 2.2.0 is now up on CocoaPods, if you'd like to use it, and includes iPad support. You may need to 'pod repo update' before running 'pod update Pulley' in order to get it.
