### ISSUE TITLE
Create a several different classes for controllers

### ISSUE THREAD

**Issue by felstell** [52inc/Pulley#96]
Hello! 

In my project I need to create two variants of controller with your library. I was try to create class with other name, or subclass but it isn't work. 

How I can use your Pulley for two different types of controller in my project?

**Comment by brendan09** [comment]
Pulley shouldn’t be subclassed, duplicated, or altered. It’s meant to be used as-is. I’m not sure what issue you’re having, as there shouldn’t be any issue using Pulley as many times as you’d like. Can you be more specific?

**Comment by felstell** [comment]
Yes, i can.

I must create a two type of controllers. First - music player with history of tracks. This looks like this
![2017-10-26 10 43 48](https://user-images.githubusercontent.com/8091787/32040849-c69972a4-ba3a-11e7-80e4-05c0f962f9f9.png)
![2017-10-26 10 43 41](https://user-images.githubusercontent.com/8091787/32040853-cb17f9ea-ba3a-11e7-86e3-9ac9e7f98259.png)

And I also need to create controller to show news text. This looks like this
![2017-10-26 10 44 06](https://user-images.githubusercontent.com/8091787/32040871-dc33662e-ba3a-11e7-819c-75ab1a7b0448.png)

I hope use your library in both cases, but I don't know how do this right. 
Can you help me?

**Comment by brendan09** [comment]
You shouldn’t alter or subclass Pulley. Use it as-is and make custom view controllers that you can set for the primary content and drawer content view controllers that Pulley manages. Don’t alter or subclass Pulley itself.

**Comment by felstell** [comment]
I don't understand solution what you propose. You can show me example?

**Comment by brendan09** [comment]
The sample project included with Pulley demonstrates changing the 'content' and 'drawer' view controllers will Pulley.

You can create as many instances of PulleyViewController as you need, and change the content / drawer view controllers. However, you should _not_ subclass, duplicate, or extend Pulley View Controller itself. It's meant to be used as-is.
