### ISSUE TITLE
Content doesn't immediately scroll when pulled to 100%

### ISSUE THREAD

**Issue by cameroncooke** [52inc/Pulley#97]
Unlike the Apple Maps sheet when pulling on the content in Pully and reaching the top of the screen the content doesn't automatically start scrolling instead you have to lift your finger and then scroll again.

In the video below what you don't see is that in Pully I had to release my finder and start a new gesture to get the content scrolling when pulled to 100% whereas in iOS Maps you don't which makes more sense as you're already making a scrolling gesture to reveal more content the scroll view is just an extension of that.

![ezgif com-optimize](https://user-images.githubusercontent.com/630601/31999308-b7172fde-b98a-11e7-8ede-6fc8a266b7b0.gif)

**Comment by brendan09** [comment]
This is a known issue. However, I’ve deemed this as something I don’t intend to fix as it would require trying to take advantage of internal gesture recognizors of the scrollview...which aren’t meant to be publicly accessible. 

It’s possible it could be rigged to behave this way using scrollview delegates, however Pulley doesn’t actually provide the drawer content so I can’t tightly couple the drawer contents to the drawer behavior the way Apple does.

If anyone finds a good way to handle this, I’m happy to consider a PR. However, as of right now it’s something I don’t plan to address.

**Comment by cameroncooke** [comment]
`UIScrollView` does expose its gesture recognizer though: https://developer.apple.com/documentation/uikit/uiscrollview/1619425-pangesturerecognizer

Also I would argue that the fact that the `UIScrollView` delegate lets you adjust the behavior on scroll would indicate that Apple don't mind you doing this.

**Comment by brendan09** [comment]
You can access the gesture recognizes, but you can’t become their delegate to receive all the events. They’re available so you can require them to fail, or control how they interfere with your own.

It’s not that they _mind_, however: Pulley doesn’t provide or manage the drawer content. As a result, Pulley doesn’t  have control over the scrollview subclass in question (or even know it exists), which is what makes the delegate approach infeasible.

**Comment by cameroncooke** [comment]
Could the pan gesture be handed over to the content view maybe? I know you can have two pan gesture recognizes and then use a delegate to manage who has priority would it not just be a matter of making the Pully gesture recognizer stop handling events when the sheet is 100%? 

Just thinking out loud. Maybe I'll have a play.

**Comment by brendan09** [comment]
Pulley uses a scrollview, not gesture recognizes directly. I think it would be subject to the same “can’t become the delegate without potentially breaking the scrollview” problem.

I do welcome you to give it a try. If you find a way to do it without reliance on the drawer content VC, I’ll be incredibly happy since this is a common request. I’m happy to merge it in if an appropriate solution can be found. However, I haven’t yet found a good way unfortunately.

**Comment by cameroncooke** [comment]
Yeah I totally agree and it should be that way. Pully shouldn't know or really care about what the content view is doing. Just wondering if there is a way to still achieve this without knowing about the existence of any content scroll view.

If you're using a pan gesture to make pully pull the pane up is there a way that the event could continue to fire against the child view and be picked up by any scroll view automatically (i.e. handing over the event) that way pully wouldn't need to know anything about the content view. 

Ok leave it with me, I'm not even sure it's possible. I would be interested to see how Apple are doing it.

**Comment by cameroncooke** [comment]
Ok I'll take a look, looks like a fun project.

**Comment by brendan09** [comment]
My guess is that it’ll be something 100% implemented in the drawer content. Somewhere that you can get access to the table view gesture recognizes and stop them when you reach the top so that Pulley’s take over.

**Comment by cameroncooke** [comment]
Out of interest was there a reason Pully wasn't implemented using iOS presentation APIs instead of the custom container view controller approach? 

 It kind of limits where it can be used especially for apps that already have a fairly complex controller hierarchy. I kind of see the sheet as a modal view controller that contains another view controller.

**Comment by brendan09** [comment]
It achieves more “natural” and accurate scrollview-feel (scrolling, edge bounces, deceleration, etc) which is almost impossible to recreate accurately.

I also never originally intended Pulley to be presented Modally. It was created more like the classic “side drawer”, where it assumed that it would be the root view controller of the window, and never be modally presented. It would then manage 1 active drawer VC and 1 active content VC. I’ve since fixed some issues related to modally presenting it, but that wasn’t my original intention.

**Comment by cameroncooke** [comment]
I see that makes sense. I think for what we need a solution built on UIPresentationController and related APIs would be preferable.

--

**Comment by brendan09** [comment]
Yeah, if you're looking for modal presentation then I'd definitely look at UIPresentationController solutions.
